Eonsang
CodeSoom/react-week5-assignment-1 pull request #1
Opened 2020-06-29 15:20 UTC by eonsang

thunk 적용 전까지 작업했습니다!
비동기 관련한 테스트케이스는 작성을 못햇는데, 추가적으로 공부해서 붙여보도록 하겠습니다!

2020-06-30 00:45 UTC, hannut91 requested changes
TDD도 잘해주셨고 테스트도 전체적으로 다 좋네요! 계속 진행해주세요 ㅎㅎ

2020-06-30 00:45 UTC, hannut91 commented on src/Categories.test.jsx
> +  it('props로 받은 category를 보여준다..', () => {
`props로 받은`이란 것은 드러내지 않아도 괜찮을 것 같아요. 카테고리 목록을 보여준다라고만 해도 괜찮을 것 같아요.

2020-06-30 00:45 UTC, hannut91 commented on src/Categories.test.jsx
> +  it('카테고리 버튼을 클릭 할 수 있다.', () => {
어떤 행위를 했을 때 어떤 변화가 일어나는지에 대해 테스트 이름을 지어보시면 좋을 것 같아요.

2020-06-30 00:45 UTC, hannut91 commented on src/Categories.test.jsx
> +    useSelector.mockImplementation((selector) => selector({ categories }));
`it`안에는 `Given, When, Then`에서  `When`에 해당하는데 지금 `Given`도 같이 들어간 것 같아요. 분리해주면 좋을 것 같습니다.

2020-06-30 00:45 UTC, hannut91 commented on src/reducer.test.js
> +      };
`initialState`를 사용하는 곳이 많이 보이네요. 반복되거나, 비슷한 모양이 계속 보인다면 중복을 제거해야한다는 신호입니다!

2020-06-30 00:45 UTC, hannut91 commented on src/reducer.js
> +  if (type === 'SELECT_REGION') {
`if`나 `switch`를 사용하지 않고 이 문제를 해결할 수 있을까요?

2020-07-01 07:58 UTC, eonsang commented
작성을 하다보니 `api`와 `redux thunk`로 작성된 액션에 대한 테스트 케이스를 작성하는거에 감이 안와서요!

[리덕스 문서](https://redux.js.org/recipes/writing-tests#async-action-creators)를 참조해서 작성하고 잇는데 추가적으로 참고해 볼만한 자료가 잇을까요??

2020-07-01 08:44 UTC, hannut91 commented
API에 대해서는 Mocking하여 테스트를 작성합니다. 액션에 대한 역할은 API를 호출하여 받은 결과를 새로운 액션으로 dispatch 하는 것인데, 여기서 API가 올바르게 동작하는지 테스트하는 것은 액션에서의 테스트의 역할에서 벗어납니다.

마찬가지로 API 테스트는 API가 올바르게 동작하는지는 클라이언트에서 관심사가 아니므로 Mocking하여 테스트를 진행합니다. 저는 이렇게 해봤어요. 정답은 아니니 참고만 해주세요.

```js
import { requestRegions, setRegions } from './actions';

import { fetchRegions } from './api';

import REGIONS from '../fixtures/regions';

jest.mock('./api');

describe('requestRegions', () => {
  const dispatch = jest.fn();

  beforeEach(() => {
    dispatch.mockClear();
  });

  context('when successfully fetch', () => {
    beforeEach(() => {
      fetchRegions.mockResolvedValue(REGIONS);
    });

    it('dispatch setRegions', async () => {
      await requestRegions()(dispatch);

      expect(dispatch).toBeCalledWith(setRegions(REGIONS));
    });
  });

  context('when fail to fetch regions', () => {
    beforeEach(() => {
      fetchRegions.mockRejectedValue(new Error('Fail to fetch'));
    });

    it('do not dispatch setRegions', async () => {
      await requestRegions()(dispatch);

      expect(dispatch).not.toBeCalled();
    });
  });
});
```

2020-07-01 13:55 UTC, hannut91 requested changes

2020-07-01 13:55 UTC, hannut91 commented on src/actions.js
> +  };
테스트를 먼저 작성해서 원하는 것이 정확히 무엇인지 정의하고 난 후 코드를 작성해보면 좋을 것 같아요. 그러면 구현하기 전에 불확실한 것들에 대해서 더 미리 생각해볼 수 있고 테스트가 있기 때문에 더 안전하게 코드를 구현할 수 있을거에요.

2020-07-01 13:55 UTC, hannut91 commented on src/actions.js
> +};
이것도 테스트를 먼저 작성한 후에 구현을 하시면 좋을 것 같아요

2020-07-01 13:55 UTC, hannut91 commented on src/App.jsx
>      }
`선택된 지역과 선택된 카테고리가 존재할 때`라는 것을 이 컴포넌트가 정의하고 있어요. 이 책임을 누가가지고 있는게 좋을까요?

2020-07-01 13:55 UTC, hannut91 commented on src/reducer.test.js
>      const expectState = {
초기의 상태를 반환하도록 테스트를 작성해주셨네요. 테스트 이름에도 있는 것 처럼 `initialState`라는 이름을 사용하면 테스트를 이해하는데 더 좋을까요?

2020-07-01 13:55 UTC, hannut91 commented on src/Categories.test.jsx
> +  useSelector.mockImplementation((selector) => selector({ categories }));
GIVEN WHEN THEN 에 맞춰서 테스트를 작성해주셨네요. dispatch나 handleClick을 테스트할 떄 다른 곳에서 동일하게 이 것을 사용한다면 의도치 않은 결과가 발생할 수 있어요. 각 테스트가 실행될 때 마다 초기화해주는게 더 안전합니다.

```js
const dispatch = jest.fn();
const handleClick = jest.fn();

beforeEach(() => {
  dispatch.mockClear();
  handleClick.mockClear();

  useDispatch.mockImplementation(() => dispatch);
  useSelector.mockImplementation((selector) => selector({ categories }));
});
```

2020-07-05 13:46 UTC, hannut91 approved these changes
고생많으셨습니다. 과제를 항상 일등으로 제출하시고 부지런 하신 것 같아요 ㅎㅎ 다만 아쉬운 점은 리뷰에 대한 피드백에 대해서 더 개선하면 좋을 것 같아요. 지금 현재 결과물이 만족하지 않고 더 좋게 만들 수 있지 않을까? 고민을 더 많이 해보시면 좋을 것 같습니다

2020-07-05 13:47 UTC, hannut91 commented
이번 과제를 진행하면서 무엇을 배우셨나요? 다음 과제에서 더 신경써서 진행하고 싶으신 것이 있으신가요?

2020-07-13 14:12 UTC, merged