[5주차-과제1] 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #10
Opened 2020-07-01 17:48 UTC by sogoagain

안녕하세요, 트레이너님 :)
5주차 과제 리뷰 요청 드립니다.

이전에 피드백 주신 것을 생각해 커밋 단위를 최대한 쪼갰습니다.
하나의 단위 테스트에 대해 커밋을 진행하고 이를 구현해 나갔습니다.

이번 과제에서는 구현 전에 요구사항을 면밀히 살펴야 한다는 것을 느꼈습니다.
과제 예시 이미지를 보니 식당을 조회한 뒤 다른 지역을 누르면 식당 리스트가 초기화되는 것처럼 보였습니다.
그래서 음식 종류를 선택했을 경우에만 식당을 조회하고 지역을 선택하면 조회된 식당 목록을 초기화하도록 구현했습니다.
그런데 e2e 테스트에서 실패하여 살펴보니 서버에서 전달받은 데이터가 빈 데이터였기에 빈 식당 리스트가 출력되는 것이었네요.
앞으론 예시 이미지뿐만 아니라 e2e 테스트를 통해서도 요구사항을 분석해야겠다는 생각이 들었습니다.

감사합니다!

2020-07-02 01:08 UTC, hannut91 requested changes

2020-07-02 01:08 UTC, hannut91 commented on src/services/api.test.js
> +    }));
`mockResolvedValue`를 사용하면 더 간단하게 표현할 수 있을 거에요

See also
  - https://jestjs.io/docs/en/mock-function-api#mockfnmockresolvedvaluevalue

2020-07-02 01:08 UTC, hannut91 commented on src/App.test.jsx
> +    expect(dispatch).toBeCalledTimes(6);
왜 `6`인지 모르겠어요. 왜 5가 되면 안되나요? 이렇게 아무 의미 없는 글자를 Magic literal이라고 불러요.

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2020-07-02 01:08 UTC, hannut91 commented on src/CategoryButtonListContainer.jsx
> +  }, []);
컴포넌트가 만들어질 때 카테고리를 불러오도록 해주셨네요. 카테고리를 불러오는 책임은 누구에게 있는 걸까요?

2020-07-02 01:08 UTC, hannut91 commented on src/CategoryButtonListContainer.jsx
> +export default function CategoryButtonListContainer() {
`CategoryButtonListContainer`는 안에서 버튼을 사용한다는걸 내포하고 있네요. 이 컴포넌트가 어떤역할을 하고 있나요? 카테고리 목록을 관리하는게 이 컴포넌트의 역할일 것 같아요. 그러면 `CategoriesContainer`가 더 적절할 것 같아요.

2020-07-02 01:08 UTC, hannut91 commented on src/CategoryButtonListContainer.test.jsx
> +    expect(dispatch).toBeCalledTimes(3);
왜 3인지 모르겠어요

2020-07-02 01:08 UTC, hannut91 commented on src/CategoryButtonListContainer.test.jsx
> +    expect(dispatch).toBeCalledTimes(5);
왜 5 인지 모르겠어요

2020-07-02 01:08 UTC, hannut91 commented on src/utils.test.js
> +});
`util`은 region과 완전히 아무 상관이 없어야해요.

2020-07-02 01:08 UTC, hannut91 commented on src/utils.js
> +const check = ({ id, name }, checkedId) => {
`checkedId`가 무엇을 나타내는지 이해하기 어렵네요.

이건 어떤가요? 참고만 해주세요.

```js
const check = (obj, id) => {
  if (obj.id !== id) {
    return obj;
  }

  return {
    ...obj,
    name: obj.name.replace(CHECK_SYMBOL, '') + CHECK_SYMBOL,
  }
}
```

2020-07-02 01:08 UTC, hannut91 commented on src/utils.test.js
> +});
```js
describe('check', () => {
  let obj;

  context('with equal id', () => {
    beforeEach(() => {
      obj = {
        id: 1,
        name: 'some name',
      };
    })

    it('returns obj updated name', () => {
      const result = check(obj, id);

      expect(result.name).toBe(`${name}${CHECK_SYMBOL}`);
    });
  });

  context('with already has symbol obj', () => {
    beforeEach(() => {
      obj.name = `some name${CHECK_SYMBOL}`;
    });

    it('returns has symbol name obj', () => {
      const result = check(obj, id);

      expect(result.name).toBe(`${name}${CHECK_SYMBOL}`);
    });
  })

  context('with not equal id', () => {
    beforeEach(() => {
      obj = {
        id: 1,
        name: 'some name',
      };
    });

    it('returns obj updated name', () => {
      const result = check(obj, 1004);

      expect(result.name).toBe(name)
    });
  })
});
```

2020-07-02 15:14 UTC, sogoagain commented on src/services/api.test.js
> +    }));
훨씬 가독성도 좋고 사용하기도 편리하네요.
공식 레퍼런스를 자주 참고해야겠네요.

2020-07-02 15:15 UTC, sogoagain commented on src/App.test.jsx
> +    expect(dispatch).toBeCalledTimes(6);
안 그래도 이 부분을 어떻게 테스트할까 고민하다 일단 리뷰요청 드렸어요.
몇 번 호출되었는지가 아니라 어떤 액션이 dispatch 되는지 테스트하여 클릭할 때 어떤 일이 발생하는지 한눈에 파악할 수 있도록 수정했습니다!

2020-07-02 15:20 UTC, sogoagain commented on src/CategoryButtonListContainer.jsx
> +  }, []);
생각해보았는데요, 카테고리가 있는 컴포넌트보다 상위에 있는 컴포넌트에서 불러오는 게 맞는 것 같습니다. 카테고리 컴포넌트는 카테고리 데이터가 준비된 뒤에 그것을 이용하는 것이 조금 더 좋은 방향이라 생각했는데 맞을까요?
`<App />` 컴포넌트에서 카테고리를 가져오도록 수정했습니다.

2020-07-02 15:22 UTC, sogoagain commented on src/CategoryButtonListContainer.jsx
> +export default function CategoryButtonListContainer() {
그렇네요. 내부적으로 `<ButtonList />`를 사용한다는 것에 관심을 가지다 보니 이름에 구현을 드러내 버렸네요. `<CategoryButtonListContainer />` 뿐만 아니라 `<RegionButtonListContainer />` 컴포넌트도 각각 `<CategoriesContainer />`, `<RegionsContainer />` 로 이름을 변경했습니다.

2020-07-02 15:22 UTC, sogoagain commented on src/CategoryButtonListContainer.test.jsx
> +    expect(dispatch).toBeCalledTimes(3);
클릭할 때 어떤 일이 발생하는지 한눈에 파악할 수 있도록 수정했습니다.

2020-07-02 15:22 UTC, sogoagain commented on src/CategoryButtonListContainer.test.jsx
> +    expect(dispatch).toBeCalledTimes(5);
클릭할 때 어떤 일이 발생하는지 한눈에 파악할 수 있도록 수정했습니다.

2020-07-02 15:23 UTC, sogoagain commented on src/utils.test.js
> +});
네! util로 추출한 이상 기존 데이터와 별개로 조금 더 포괄적인 범위의 테스트가 이루어지는 게 맞는 것 같아요. 작성해주신 코드를 참고해 수정했습니다.

2020-07-02 15:25 UTC, sogoagain commented on src/utils.js
> +const check = ({ id, name }, checkedId) => {
와, 너무 좋습니다. 참고만 하시라고 하셨지만... 이보다 좋은 코드가 생각이 나질 않아 위와 같이 수정했어요.
`Destructuring assignment`를 사용해야겠다는 생각에 빠져버려 객체 그 자체를 사용하면 더 좋은 코드가 나올 수 있다는 것을 간과해버렸네요.
감사합니다!

2020-07-03 01:43 UTC, hannut91 requested changes
전체적으로 테스트에 Given같이 들어가 있어서 이해하기 어려운 것 같아요. 따로 분리해주면 가독성이 더 좋아질 것 같습니다

2020-07-03 01:43 UTC, hannut91 commented on src/services/api.test.js
> +  );
이렇게 해도될 것 같아요
```js
global.fetch = jest.fn().mockResolvedValue({
  async json() {
    return data;
  }
});
```

2020-07-03 15:39 UTC, sogoagain commented on src/utils.js
> +const check = ({ id, name }, checkedId) => {
수정한 코드가 제 의도와는 조금 다른 것이 있어 테스트 코드를 추가로 작성하고 로직을 일부 수정했습니다.

2020-07-03 15:40 UTC, sogoagain commented
> 전체적으로 테스트에 Given같이 들어가 있어서 이해하기 어려운 것 같아요. 따로 분리해주면 가독성이 더 좋아질 것 같습니다

테스트 코드를 전체적으로 보며 given을 줄이고자 노력했습니다.
특히, mocking 하는 작업들을 테스트 초입부에서 공통으로 관리하도록 수정했어요.

2020-07-03 15:42 UTC, sogoagain commented on src/services/api.test.js
> +  );
아하! async 키워드가 Promise를 반환하도록 하는 것이니 위와 같이 훨씬 간단히 변경할 수 있네요.
또 하나 배웁니다. 감사합니다!

2020-07-04 01:47 UTC, hannut91 requested changes

2020-07-04 01:47 UTC, hannut91 commented on src/App.test.jsx
> +    expect(dispatch).toBeCalledWith(getRegionsAction);
액션을 Mocking하게 되면 어떤 값이 들어오든 무조건 통과하네요 어차피 getRegionsAction이 아무런 값도 반환하지 않기 때문에요

```js
const fn = () => {}

expect(dispatch).toBeCalledWith(fn());
```

제대로 테스트가 되고 있는건지 잘 모르겠어요.

App이 실행되었을 때 getRegions 액션이 실행됐다라는 것을 확인하고 싶으시다면 다음과 같이 하는게 좋을 것 같아요.

```js
beforeEach(() => {
  dispatch.mockClear();

  getRegions.mockClear();
  getCategories.mockClear();
});

it('fetch regions', () => {
  renderApp();

  expect(getRegions).toBeCalled();
  expect(getCategories).toBeCalled();
});
```

2020-07-04 09:58 UTC, sogoagain commented on src/App.test.jsx
> +    expect(dispatch).toBeCalledWith(getRegionsAction);
트레이너님, 다시 한번 확인해주실 수 있으실까요?

해당 부분은 특정 action이 실행되었을 때 반환되는 함수를 mocking 한 것이기 때문에, 해당 함수를 인자로 dispatch가 실행된 것을 검증하면 액션이 실행되었다는 것과 같다고 해석할 수 있을 것 같습니다.

또한 제가 확인한 결과
```javascript
expect(dispatch).toBeCalledWith(getRegionsAction);
```
위 코드를 아래와 같이 변경했을 때는 테스트에 실패합니다.
```javascript
expect(dispatch).toBeCalledWith(() => {});
```

2020-07-04 16:35 UTC, sogoagain commented on src/App.test.jsx
> +    expect(dispatch).toBeCalledWith(getRegionsAction);
> 액션을 Mocking하게 되면 어떤 값이 들어오든 무조건 통과하네요 어차피 getRegionsAction이 아무런 값도 반환하지 않기 때문에요
> 
> ```js
> const fn = () => {}
> 
> expect(dispatch).toBeCalledWith(fn());
> ```
> 
> 제대로 테스트가 되고 있는건지 잘 모르겠어요.
> 
> App이 실행되었을 때 getRegions 액션이 실행됐다라는 것을 확인하고 싶으시다면 다음과 같이 하는게 좋을 것 같아요.
> 
> ```js
> beforeEach(() => {
>   dispatch.mockClear();
> 
>   getRegions.mockClear();
>   getCategories.mockClear();
> });
> 
> it('fetch regions', () => {
>   renderApp();
> 
>   expect(getRegions).toBeCalled();
>   expect(getCategories).toBeCalled();
> });
> ```

리뷰 해주신 내용에 대해 고민해보니 `<App />` 컴포넌트를 포함해 `Container` 컴포넌트들에서 액션을 과도하게 테스트 하고 있다고 생각이 들었습니다.
테스트 코드가 복잡하다고 의견주신 것에 공감하여 수정해보았습니다!
감사합니다.

2020-07-05 02:00 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 좋은 코드를 작성하려는 노력이 많이 보여서 너무 좋네요. 아샬님의 과제 풀이 영상을 통해 꼭 복습해 보세요.

2020-07-05 02:00 UTC, hannut91 commented on src/actions.test.js
> +    fetchRestaurants.mockImplementation(async () => restaurants);
여기도 아마 `mockResolvedValue`를 사용해도 될거에요.

`fetchRegions.mockResolvedValue(regions)`

2020-07-05 02:00 UTC, hannut91 commented
추가로 이번 과제에서는 어떤 것을 배우셨나요? 다음 과제에 시도해보고 싶으신 것이 더 있으신가요?

2020-07-05 04:09 UTC, sogoagain commented on src/actions.test.js
> +    fetchRestaurants.mockImplementation(async () => restaurants);
앗! 그렇네요. `mockImplementation`이 너무 강력하다 보니 이 함수를 먼저 사용하게 되는 것 같네요.
jest가 제공하는 다른 'Mock Functions'으로 대체할 수 없는지 확인하는 습관을 들여야겠습니다.
감사합니다.

2020-07-05 04:10 UTC, sogoagain commented
> 고생하셨습니다 ㅎㅎ 좋은 코드를 작성하려는 노력이 많이 보여서 너무 좋네요. 아샬님의 과제 풀이 영상을 통해 꼭 복습해 보세요.

넵! 복습해보도록 하겠습니다.
일주일 간 꼼꼼히 리뷰 해주셔서 감사합니다. :)

2020-07-05 04:22 UTC, sogoagain commented
> 추가로 이번 과제에서는 어떤 것을 배우셨나요? 다음 과제에 시도해보고 싶으신 것이 더 있으신가요?

- Fact (했던 것)
  - 서버와의 통신을 통해 데이터를 가져와 Application을 개발했습니다.
  - 이를 위해 'redux-thunk'를 사용해 action을 구성했습니다.
  - TDD 사이클 단위로 커밋을 진행하며 개발했습니다.

- Feelings (느낀 것)
  - TDD 사이클을 지키는 것이 만만치 않음을 다시 한번 느꼈습니다.
  - 과제를 진행하던 초기에 요구사항을 오해해 잘못된 방향으로 구현했는데 이를 올바르게 돌리는데 꽤 큰 노력이 필요했습니다.
  - mocking을 너무 세세히 하다 보니 구현 위주로 테스트가 진행되는 것이 아닌지 생각이 들었습니다.

- Finding (배운 것)
  - `mockResolvedValue`를 비롯해 jest에서 지원하는 다양한 mock fucntions에 대해 알게 되었습니다.
  - 'redux-thunk'로 비동기 액션을 처리하는 방법에 대해 학습했습니다.
  - 테스트 코드는 다른 사람이 쉽게 읽을 수 있도록 작성해야 한다는 것을 다시금 깨달았습니다.

- Affirmation(할 것)
  - `mockImplementation`을 사용할 때 jest가 제공하는 다른 'Mock Functions'으로 대체할 수 없는지 확인하는 습관을 들여야겠습니다.
  - 구현을 테스트하는 것이 아닌 인터페이스를 테스트하기 위해 계속해서 수련하겠습니다.
  - 과제를 진행할 때 5일 단위 작업으로 쪼개어 하루에 한번 씩 코드리뷰 요청을 할 수 있도록 진행하겠습니다.

2020-07-05 13:43 UTC, hannut91 commented
회고 너무 좋네요. ㅎㅎㅎ 저는 리뷰하면서 좋았던 점은 코드를 개선하기 위해서 엄청 노력하신게 보여서 좋았어요. 코드도 직접 실행해가며 개선해볼려고 저도 노력했고 제안도 해봤습니다. 오히려 극단적으로 뭔가 하면서 더 배우는게 많은 것 같아요. 저도 예전에 DynamoDB로 테이블 Join을 만들고 별 말도 안되는 이상한걸 했는데 그러면서 DynamoDB에 대해 더 배우게 됐어요. 많은 시도를 해보면서 비교해가면서 더 좋은것을 찾아가시면 좋을 것 같아요. 고생많으셨습니다.

2020-07-05 13:43 UTC, merged

2020-07-05 14:32 UTC, sogoagain commented
> 회고 너무 좋네요. ㅎㅎㅎ 저는 리뷰하면서 좋았던 점은 코드를 개선하기 위해서 엄청 노력하신게 보여서 좋았어요. 코드도 직접 실행해가며 개선해볼려고 저도 노력했고 제안도 해봤습니다. 오히려 극단적으로 뭔가 하면서 더 배우는게 많은 것 같아요. 저도 예전에 DynamoDB로 테이블 Join을 만들고 별 말도 안되는 이상한걸 했는데 그러면서 DynamoDB에 대해 더 배우게 됐어요. 많은 시도를 해보면서 비교해가면서 더 좋은것을 찾아가시면 좋을 것 같아요. 고생많으셨습니다.

좋게 봐주셔서 감사해요. 저도 리뷰 받으면서 섬세히 리뷰해 주시는 것이 느껴져서 너무 좋았습니다. 물론 수정에는 고통이... 뒤따랐지만요. ㅎㅎ :)
조언해 주신 대로 극단적인 실험을 많이 그리고 자주 해보도록 하겠습니다. 이번 한 주도 감사했습니다!