코드숨 5주차 과제
CodeSoom/react-week5-assignment-1 pull request #106
Opened 2022-07-04 11:43 UTC by Jongveloper

안녕하세요 트레이너님!
우선은 강의를 계속 돌려보고 있습니다!
기초적인 리덕스를 연결하는 작업만 우선 진행하였고
순차적으로 과제 진행하겠습니다!

2022-07-04 12:13 UTC, daadaadaah commented
좋습니다!👍 일하면서 과제하시느라 힘드실텐대, 코드숨 기간 동안만이라도 바짝 공부해봅시당!👊
계속 작업해진행해주세요🚀

2022-07-04 12:15 UTC, Jongveloper commented
카테고리 테스트를 먼저 작성하고 커밋을 못했네요...!
하지만 expect부분을 검증하지 않고 실수로
reducerHandler를 먼저 작성해서 TDD에서는 벗어났던 것 같습니다!
테스트 코드를 먼저 작성하기는 하지만 검증을 안하면 의미가 없는데...!
이 부분 유의하며 과제 진행하겠습니다!
이번같은 실수는 하지 않도록 하겠습니다!
아직은 익숙치 않아서 실수를 하네요!! ㅠㅠ

2022-07-04 12:19 UTC, daadaadaah commented
지금처럼 commit 메시지 빠진거나 수정하고 싶은 거 있을 때, git 을 좀더 공부해보면 좋아요!
과제 빨리 끝내거나 시간 나시면 git commit 메시지 취소, 삭제, 수정 등등 다양한 git 명령어 공부해보세요!
오늘도 열코하세용🔥

2022-07-05 11:56 UTC, Jongveloper commented
안녕하세요 트레이너님!
ㅎㅎㅎㅎ리뷰요청드립니다!
TDD로 구현을 하려니 아직 익숙치않아 어렵네요! ㅎㅎㅎ
항상 감사합니다!

2022-07-06 01:56 UTC, daadaadaah reviewed
1. 테스트가 통과 된 후에도 리팩터링 작업(코드에 중복이 없는지 또는 fixture로 관리할 수 있는지)을 진행해보세요! 
2. "작업별"로 commit 메시지 관리해보도록 노력해봅시당! 사소한 작업이라도 분리해서 commit 메시지를 남겨주세용!
3. 이번에는 UI 컴포넌트 -> Container 컴포넌트 작업하시는 순서(=상향식)로 진행하셨는데, 레스토랑 목록은 하향식으로 한번 도전해보세요!

2022-07-06 01:56 UTC, daadaadaah commented on src/store/reducer.test.js
> +      { id: 1, name: '한식' },
저는 테스트 데이터가 배열일 경우, 테스트 데이터를 2~3개정도로 하는 편입니다!

2022-07-06 01:56 UTC, daadaadaah commented on src/components/Category.test.jsx
> +    };
1. 객체보다 배열에 어울리는 변수명인 것 같아요!
2. `categories` 라는 테스트용 데이터가 다른 테스트에서도 쓰이는데, 제가 이런 데이터를 어떻게 관리하면 좋다고 했을까요?ㅎㅎ

2022-07-06 01:56 UTC, daadaadaah commented on src/components/Category.jsx
> +export default function Category({ categories }) {
복수형으로 네이밍하시는게 좀더 적절할 것 같아요!

2022-07-06 01:56 UTC, daadaadaah commented on src/store/reducer.test.js
> +  describe('setCategories', () => {
맥락 구분을 위해 한줄 띄어줍시당!

2022-07-06 01:59 UTC, daadaadaah commented on src/container/RegionsContainer.test.jsx
> +    ],
`regions`, `categories` 이런 테스트용 데이터가 다른 테스트에서도 쓰이는데, 제가 이런 데이터를 어떻게 관리하면 좋다고 했을까요?ㅎㅎ

2022-07-06 07:01 UTC, Jongveloper commented on src/components/Category.jsx
> +export default function Category({ categories }) {
아하 ㅎㅎ 감사합니다 리팩토링 진행하겠습니다!

2022-07-06 07:01 UTC, Jongveloper commented on src/store/reducer.test.js
> +  describe('setCategories', () => {
넵!ㅎㅎ

2022-07-06 07:03 UTC, Jongveloper commented on src/container/RegionsContainer.test.jsx
> +    ],
fixture로 빼는 것을 생각했는데 ㅎㅎ 아직은 중복적으로 사용하지 않는데
(나중에 사용할 것을 알지만) 최대한 중복적인 부분을 없애는 경험을 하고싶어
중복이 될 때 fixture로 뺄 생각이었는데 ㅎㅎㅎ...ㅠㅠㅠ
처음부터 뺄 걸 그랬네요! ㅎㅎㅎ
앞으로는 중복될 것 같은 테스트 데이터는 미리 fixture로 빼고 진행하겠습니다!ㅎㅎㅎㅎ
항상 좋은 피드백 감사합니다!

2022-07-06 08:05 UTC, daadaadaah commented on src/container/RegionsContainer.test.jsx
> +    ],
오호! 생각하고 계셨었군요! 다행이이예요ㅎㅎ
미리 빼는 걸 의도한 건 아닙니당!
제가 코멘트 드린 이유는 
현재 작업 내역 전체를 보면 regions 등의 테스트 데이터가 RegionsContainer.test.jsx에서는 중복되게 사용하고 있지 않지만, 여러 곳(=다른 테스트 파일들)에서 사용하고 있기 때문이예요!
이 점 참고하셔서 PR 날려주세요🚀

2022-07-06 10:55 UTC, Jongveloper commented on src/container/RegionsContainer.test.jsx
> +    ],
앗 넵 ㅎㅎ 감사합니다!!

2022-07-06 13:49 UTC, Jongveloper commented
안녕하세요 트레이너님!
코드리뷰 요청드립니다!
ㅎㅎ 강의를 여러번 다시 보느라 조금 PR이 늦었습니다!
항상 감사합니다!

2022-07-06 15:11 UTC, daadaadaah reviewed
아샬님의 강의 여러번 보신거 너무 좋아요!👍 늦더라도 데일리 PR 계속 날려주시는 점도 너무 좋구요! 👏
비동기 액션들에 대한 테스트 추가해주시면서 작업해주시면 될 것 같아요!
날이 더워 체력적으로 힘드실텐대, 지치지 마시구~ 이번주도 같이 화아팅해봐용🔥  
작업별로 Commit 남기시는 거 잊지마시구요!ㅎㅎ다음 PR 기다리고 있을게요🚀

2022-07-06 15:11 UTC, daadaadaah commented on src/App.test.jsx
> +  });
복수형이므로, forEach 사용해서 여러개가 보이는 걸로 테스트해도 좋을 것 같아요!

2022-07-07 10:51 UTC, Jongveloper commented on src/App.test.jsx
> +  });
앗 그 방법이 있는데 ㅎㅎ 제가 생각이 짧았네요!
항상 좋은 피드백 감사합니다!

2022-07-07 13:17 UTC, daadaadaah commented
계속 작업중이신가용?ㅎㅎ 작업 다 완료되시면, 코멘트 남겨주세용😄

2022-07-07 14:42 UTC, Jongveloper commented
안녕하세요 트레이너님!
리뷰요청 드립니다!
작업시간이 너무 늦어져 죄송합니다..!
항상 감사합니다!

2022-07-08 09:19 UTC, daadaadaah requested changes
수고하셨어요! 👏
리뷰어가 드리는 피드포워드에 대해 한번 "왜 이런 피드포워드를 줄까"에 대해 고민해보는 시간을 가져보시는 것도 좋을 것 같아요!ㅎㅎ다음 PR 기대하고 있을게요🚀

2022-07-08 09:19 UTC, daadaadaah commented on src/__mocks__/api.js
> +export const fetchCategories = jest.fn(async () => categories);
여기서, 데이터를 고정적으로 넣어주게 되면, 테스트 코드 작성할 때, 어떤 문제가 발생할까요? 🤔 
간단하게 아래처럼 표현하는 것과 차이점에 대해 한번 생각해보세요!
```js
export const fetchRegions = jest.fn();
export const fetchCategories = jest.fn();
```

2022-07-08 09:19 UTC, daadaadaah commented on src/components/Categories.test.jsx
> +    expect(container).toHaveTextContent('한식');
여러개가 보이는 테스트이므로, forEach 사용해서 여러개가 보이는 걸로 테스트해도 좋을 것 같아요!

2022-07-08 09:19 UTC, daadaadaah commented on src/components/Regions.test.jsx
> +    expect(container).toHaveTextContent('대구');
여러개가 보이는 테스트이므로, forEach 사용해서 여러개가 보이는 걸로 테스트해도 좋을 것 같아요!

2022-07-08 09:19 UTC, daadaadaah commented on src/container/CategoriesContainer.test.jsx
> +  useSelector.mockImplementation((selector) => selector({
맥락 구분해주세요!

2022-07-08 09:19 UTC, daadaadaah commented on src/container/CategoriesContainer.test.jsx
> +  it('categories API를 호출합니다.', () => {
api 호출 보다 "어떤 액션을 dispatch 한다"라고 표현하는게 더 좋을 것 같아요!

2022-07-08 09:19 UTC, daadaadaah commented on src/container/CategoriesContainer.test.jsx
> +    });
밑에 41번째 줄의 테스트와 이 테스트로 기대하는 것은 동일한 것 같아요!
둘 중에 하나를 수정해주는게 좋을 것 같아요!

2022-07-08 09:19 UTC, daadaadaah commented on src/container/RegionsContainer.test.jsx
> +  useSelector.mockImplementation((selector) => selector({
맥락 구분해주세요!

2022-07-08 09:19 UTC, daadaadaah commented on src/container/RegionsContainer.test.jsx
> +  });
[CategoriesContainer.test.jsx](https://github.com/CodeSoom/react-week5-assignment-1/pull/106/files#diff-7c8ba870ca216e11eebe1862181aadcbcf1d2d1e0ecc6c86ef1811ea8f7ee8d8)에 드린 코멘트 참고해서 수정해주세요!

2022-07-08 09:19 UTC, daadaadaah commented on src/store/reducer.test.js
> +      ];
fixture에 있는 데이터를 활용해도 좋을 것 같아요!

2022-07-08 09:19 UTC, daadaadaah commented on src/store/reducer.test.js
> +      ];
fixture에 있는 데이터를 활용해도 좋을 것 같아요!

2022-07-08 09:19 UTC, daadaadaah commented on src/services/api.test.js
> +});
각 api를 통해 어떤 상황을 확인해보고 싶으신지 한번 생각해보세요!
api가 호출되면 어떤 상황이 벌어질까요? 
```js
describe('fetchCategories', () => {
    it('(fetchCategories 호출하여 기대하는 결과)', () => {
    })
})
```

2022-07-08 09:19 UTC, daadaadaah commented on src/services/api.js
> +export const baseURL = 'https://eatgo-customer-api.ahastudio.com';
export 해주시는 이유가 혹시 테스트 코드에서 사용하기 때문인가용?ㅎㅎ

2022-07-08 09:19 UTC, daadaadaah commented on src/services/api.test.js
> +      }));
`mockResolvedValue`를 활용하면, 좀더 간단히 표현할 수 있어요!

2022-07-08 12:10 UTC, Jongveloper commented on src/__mocks__/api.js
> +export const fetchCategories = jest.fn(async () => categories);
앗 한번 어떤 문제가 생길지 생각해보겠습니다!

2022-07-08 12:10 UTC, Jongveloper commented on src/components/Categories.test.jsx
> +    expect(container).toHaveTextContent('한식');
헉 이런 실수를...! 리팩토링하겠습니다!

2022-07-08 12:10 UTC, Jongveloper commented on src/container/CategoriesContainer.test.jsx
> +  useSelector.mockImplementation((selector) => selector({
헉..리팩토링하겠습니다!

2022-07-08 12:11 UTC, Jongveloper commented on src/container/CategoriesContainer.test.jsx
> +  it('categories API를 호출합니다.', () => {
아아 표현이 애매했네요! 리팩토링하겠습니다!

2022-07-08 12:12 UTC, Jongveloper commented on src/store/reducer.test.js
> +      ];
앗..이부분을 수정을 못했네요!
좋은 피드백 감사합니다!

2022-07-08 12:12 UTC, Jongveloper commented on src/store/reducer.test.js
> +      ];
앗..이부분을 수정을 못했네요!
좋은 피드백 감사합니다!

2022-07-08 12:13 UTC, Jongveloper commented on src/services/api.test.js
> +});
앗 호출을 하여 받아오는건데 명확하지 못한 표현이었던 것 같습니다 감사합니다!

2022-07-08 12:13 UTC, Jongveloper commented on src/services/api.js
> +export const baseURL = 'https://eatgo-customer-api.ahastudio.com';
앗 맞습니다..!

2022-07-08 12:13 UTC, Jongveloper commented on src/services/api.test.js
> +      }));
앗...! ㅎㅎ 한번 자료 찾아보겠습니다 감사합니다!

2022-07-08 12:15 UTC, daadaadaah commented on src/services/api.js
> +export const baseURL = 'https://eatgo-customer-api.ahastudio.com';
api.test.js 수정해보시고, export 계속 필요한지에 대해 한번 생각해보세요!ㅎㅎ

2022-07-08 12:16 UTC, Jongveloper commented on src/services/api.js
> +export const baseURL = 'https://eatgo-customer-api.ahastudio.com';
넵!! ㅎㅎ 전체적으로 리팩토링 할 부분이 있는 것 같습니다! ㅎㅎ
리팩토링진행하겠습니다!
감사합니다!

2022-07-08 13:50 UTC, Jongveloper commented
안녕하세요 트레이너님! 
mockResolvedValue 부분이 이해가 잘 되지않습니다..
매개변수로 resolve되었을 때 기댓값을 넣어주면 되는걸까요!?

2022-07-08 16:18 UTC, Jongveloper commented
안녕하세요 트레이너님!
오늘은 늦어도 너무 늦을 것 같아 따로 DM을 드리지 못했습니다...!
내일 과제 완성할 수 있도록 ㅎㅎㅎ열심히 진행하겠습니다
항상 감사합니다!

2022-07-09 03:11 UTC, daadaadaah commented
작업중이신가요?ㅎㅎ

2022-07-09 03:12 UTC, Jongveloper commented
> 작업중이신가요?ㅎㅎ

ㅠㅠ오전에 작업하다가 잠시 급한일이 생겨서...!
저녁부터 다시 과제 진행할 예정입니다!!ㅠㅠ

2022-07-09 03:22 UTC, daadaadaah commented
> > 작업중이신가요?ㅎㅎ
> 
> ㅠㅠ오전에 작업하다가 잠시 급한일이 생겨서...! 저녁부터 다시 과제 진행할 예정입니다!!ㅠㅠ

아핫!ㅎㅎㅎ짬내서 작업을 진행하셨군요! 잘하셨어요👍👍👍
다만, 다음에는 작업이 완료되었으면, 완료되었다는 코멘트 하나만 남겨주시면 좋을 것 같아요!😃

2022-07-09 03:24 UTC, Jongveloper commented
> > > 작업중이신가요?ㅎㅎ
> 
> > 
> 
> > ㅠㅠ오전에 작업하다가 잠시 급한일이 생겨서...! 저녁부터 다시 과제 진행할 예정입니다!!ㅠㅠ
> 
> 
> 
> 아핫!ㅎㅎㅎ짬내서 작업을 진행하셨군요! 잘하셨어요👍👍👍
> 
> 다만, 다음에는 작업이 완료되었으면, 완료되었다는 코멘트 하나만 남겨주시면 좋을 것 같아요!😃

앗 어제는 너무 늦게 완료될 것 같아ㅠㅠ 따로 dm을 못드렸습니다ㅠㅠ 이번 주에 좀 자주 늦는 것 같아 너무 죄송해서요..!ㅠㅠ
작업 완료되면 꼭 코멘트 남기겠습니다!
항상 감사합니다!

2022-07-09 04:03 UTC, daadaadaah requested changes
매일 조금씩 PR 올려주시는거 너무 잘하고 계세요!ㅎㅎ
남은 주말에도 힘내서 과제 완성시켜 봅시당👊

2022-07-09 04:03 UTC, daadaadaah commented on src/App.test.jsx
> +  });
API 호출은 어디서 하는지 생각해보시고, App 입장에서 무엇을 하는지를 테스트에 표현해주세요!

2022-07-09 04:03 UTC, daadaadaah commented on src/container/CategoriesContainer.test.jsx
> +jest.mock('../store/async-actions');
비동기 액션을 mock 해주시는 이유가 무엇인가용?ㅎㅎ

2022-07-09 04:03 UTC, daadaadaah commented on src/services/api.test.js
> +});
아직 수정 작업이 안되신거죵?ㅎㅎ
https://github.com/CodeSoom/react-week5-assignment-1/pull/106#discussion_r916614995
코멘트 참고해서 수정해주세요~

2022-07-09 04:03 UTC, daadaadaah commented on src/store/async-actions.test.js
> +});
`redux-mock-store`를 활용하면, dispatch 시에 어떤 action이 호출되었는지까지 확인할 수 있어서, 좀더 의도를 드러낼 수 있어요~ 한번 활용해봅시당!ㅎㅎ

2022-07-09 12:59 UTC, Jongveloper commented on src/container/CategoriesContainer.test.jsx
> +jest.mock('../store/async-actions');
비동기 액션을 mock하지 않으면 테스트가 깨지더라구요!ㅠㅠ
혹시 다른 방법이 있을까요!?

2022-07-09 13:00 UTC, Jongveloper commented on src/services/api.test.js
> +});
엇..분명 바꿨는데..ㅠㅠ 제가 바꿨다 생각하고 변경을 안했나봅니다!
변경하겠습니다!

2022-07-09 13:00 UTC, Jongveloper commented on src/store/async-actions.test.js
> +});
앗 넵 자료 찾아보고 활용해보겠습니다!

2022-07-09 14:42 UTC, Jongveloper commented
안녕하세요 트레이너님!
트레이너님이 피드백 주신 것 반영하여 리팩토링하고 과제 완료하였습니다!
항상 좋은 피드백 주셔서 과제를 완성할 수 있었던 것 같습니다!
항상 감사합니다!
getActions 부분 자료를 찾아보았는데 명확하게 설명하는 자료를 못찾아서...
혹시 실례가 안된다면 이 부분에 대해 참고자료 부탁드려도 될까요..?!

2022-07-10 00:56 UTC, daadaadaah commented
> getActions 부분 자료를 찾아보았는데 명확하게 설명하는 자료를 못찾아서...
혹시 실례가 안된다면 이 부분에 대해 참고자료 부탁드려도 될까요..?!

getActions의 어떤 자료가 필요하신거예요??ㅎㅎ

2022-07-10 01:35 UTC, daadaadaah requested changes
> getActions 부분 자료를 찾아보았는데 명확하게 설명하는 자료를 못찾아서...
혹시 실례가 안된다면 이 부분에 대해 참고자료 부탁드려도 될까요..?!

getActions의 어떤 자료가 필요하신거예요??ㅎㅎ redux-mock-store 자료 말씀하신 건가용?ㅎㅎ
https://github.com/reduxjs/redux-mock-store

2022-07-10 01:35 UTC, daadaadaah commented on src/components/Regions.jsx
> +        regions.map(({ id, name }) => (
이건 객체 구조 분해 입니다! 
RORO 패턴에 대해 다시 공부해보세요!

2022-07-10 01:35 UTC, daadaadaah commented on src/services/api.test.js
> +    it('getRegions api주소와 함께 fetch됩니다.', async () => {
우리가 `fetchCategories`로 기대하는 것은 무엇인지에 대해 다시 생각해보세요!
예를 들어, 주소를 가져오는 `getAddress`라는 함수를 테스트 하고 싶을 때, it문을 "return address" 이렇게 작성할 것 같아요! 테스트도 마찬가지로 getAddrees 결과, 실제 return 값이 address인지 확인할 것 같구요!ㅎㅎ

```js
const address = "서울";
const result = await getAddress();
expect(result).tobe(address);

```

2022-07-10 01:35 UTC, daadaadaah commented on src/services/api.test.js
> +});
테스트 자체도 수정이 필요합니다!ㅎㅎ

2022-07-10 01:35 UTC, daadaadaah commented on src/components/Categories.test.jsx
> +  const defaultCategory = categories[0].id;
> 5397e71f70152386c5fea3a6c595a829b708b9e2 질문에 대한 답변

region과 다르게 id를 사용해서 그런 것 같아요! 이런 문제가 똑같이 발생하기 위해서는 변수명을 어떻게하는게 좋을까요?
`const defaultRegion = regions[0].name;`

2022-07-10 01:42 UTC, daadaadaah commented on src/container/RestaurantsContainer.test.jsx
> +  const selectedCategory = categories[0].id;
통일성 있게 관리해주시는게 좋을 거 같아요! 어디서는 name으로 관리하고 어디서는 id로 관리하면 헷갈릴 것 같아서요!

2022-07-10 01:48 UTC, Jongveloper commented on src/components/Regions.jsx
> +        regions.map(({ id, name }) => (
앗 제가 객체 구조 분해를 RORO로 혼동하고 있었던 것 같습니다.
RORO패턴에 대해 다시 공부하겠습니다!
좋은 피드백 감사합니다!

2022-07-10 01:48 UTC, Jongveloper commented on src/services/api.test.js
> +    it('getRegions api주소와 함께 fetch됩니다.', async () => {
앗 피드백 감사합니다!
피드백 참고하여 리팩토링 진행하겠습니다!

2022-07-10 01:49 UTC, Jongveloper commented on src/components/Categories.test.jsx
> +  const defaultCategory = categories[0].id;
아아 네네!
ㅎㅎㅎ 좋은 피드백 감사합니다
테스트가 깨질 때 스샷을 같이 첨부하겠습니다 감사합니다!

2022-07-10 01:50 UTC, Jongveloper commented on src/container/RestaurantsContainer.test.jsx
> +  const selectedCategory = categories[0].id;
아하!! 참고하여 리팩토링 하겠습니다 좋은 피드백 감사합니다!

2022-07-10 01:56 UTC, daadaadaah commented on src/container/CategoriesContainer.test.jsx
> +jest.mock('../store/async-actions');
`__mocks__` 폴더에 `async-action.js` 파일 하나 만들어서 mocking이 필요한 것들 추가해주시면 좋을 거 같아요!

2022-07-10 09:20 UTC, Jongveloper commented
안녕하세요 트레이너님!
트레이너님이 주신 피드백 반영하여 과제 완성하였습니다!
트레이너님 덕분에 과제 완성할 수 있었던 것 같습니다
항상 감사합니다!

2022-07-11 00:59 UTC, daadaadaah approved these changes
이번주도 수고하셨어요!🔥

2022-07-11 01:01 UTC, daadaadaah commented on src/container/CategoriesContainer.test.jsx
> +jest.mock('../store/async-actions');
이렇게 mocking 해주실 때, `api`랑 `redux-react mocking`한 것처럼 `__mocks__`폴더에 `async-action.js` 하나 만들어서 mocking하는 함수 넣어주시고, 테스트 코드에서 mockImplement 해주셔야됩니당!ㅎㅎ

2022-07-11 01:01 UTC, merged