[Kyh196201] 5주차 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #109
Opened 2022-07-05 11:54 UTC by kyh196201

트레이너님 안녕하세요!

리뷰 요청드립니다.

RegionsContainer와 reducer에 대한 일부 테스트 코드를 작성했고, 컴포넌트를 구현했습니다.

사실 이전 주차 두번째 과제에서 피드백 받아야할 부분 같은데, 지금 제가 구현하고 있는 순서가 맞는지 잘 모르겠습니다. 😂

2022-07-06 03:21 UTC, daadaadaah reviewed
아침에 짬내서 작업 더 진행해주셨네용!! 잘하셨어요👍 commit 메시지도 작업별로 명확히 구분해주시구👍
비동기 액션들에 대한 테스트 추가해주시면서 작업해주시면 될 것 같아요!

2022-07-06 03:21 UTC, daadaadaah commented on src/containers/RegionsContainer.test.jsx
> +      expect(container).toHaveTextContent(region.name);
regions 라는 복수형 답게 반복문으로 돌려서 여러개 확인해도 괜찮을 것 같아요!

2022-07-06 03:21 UTC, daadaadaah commented on src/containers/RegionsContainer.test.jsx
> +  given('regions', () => []);
`given`은 Context아래에 위치 하는게 코드를 이해하는 데 더 도움될 것 같아요!

```jsx
  context('without regions', () => {
    given('regions', () => []);

    it('nothing renders', () => {
      const { queryAllByRole } = renderRegionsContainer();

      expect(queryAllByRole('listitem')).toHaveLength(0);
    });
  });
```

2022-07-06 03:21 UTC, daadaadaah commented on src/components/Regions.jsx
> +            {region.name}
완성된 화면을 보면, 지역과 카테고리를 "클릭"하면, 해당 레스토랑이 나오는 기능이라서, button 요소가 필요할 것 같아요!ㅎㅎ

2022-07-06 03:21 UTC, daadaadaah commented on src/containers/RegionsContainer.test.jsx
> +      expect(queryAllByRole('listitem')).toHaveLength(0);
`listitem` 만 봤을 때, 어떤 리스트인지 정확히 알기 어려울 것 같아요! 어떻게 변경하는게 좋을까요?

2022-07-06 10:26 UTC, kyh196201 commented on src/containers/RegionsContainer.test.jsx
> +      expect(container).toHaveTextContent(region.name);
넵 ! ㅎㅎ `forEach`를 이용해서 모든 regions가 렌더링되었는지 확인하는 코드로 수정했습니다 🙌

2022-07-06 10:31 UTC, kyh196201 commented on src/containers/RegionsContainer.test.jsx
> +  given('regions', () => []);
앗 반드시 최초로 한 번 선언해줘야하는 줄 알았습니다 ㅎㅎ..

각 context 아래에 위치 하는게 더 의미를 파악하기 쉽네요! 감사합니다 🙏🙏

2022-07-06 10:31 UTC, kyh196201 commented on src/components/Regions.jsx
> +            {region.name}
Region 컴포넌트를 구현하면서 수정하겠습니다 감사합니다 ㅎㅎ !!

2022-07-06 11:33 UTC, kyh196201 commented
트레이너님 피드백 주신 내용 수정완료했습니다!

비동기 액션에 대한 테스트를 추가하라고 하셔서 `async-actions.js`에 있는 `loadRegions` 함수에 대한 테스트를 작성했는데, 트레이너님이 말씀하신걸 제가 맞게 이해한건지 모르겠네요 😂

그리고 `Regions` 컴포넌트 테스트에서 `listitem` role로 엘리먼트를 검색하는 방법 말고 다른 방법이 어떤게 있나요? 잘 모르겠습니다 ㅠㅠ

혹시 [TestId](https://haeguri.github.io/2020/12/21/clean-up-jest-mock/) 이거 사용하면 될까요??

2022-07-06 11:34 UTC, kyh196201 commented on src/containers/RegionsContainer.test.jsx
> +      expect(queryAllByRole('listitem')).toHaveLength(0);
이 부분은 잘 모르겠습니다 😂

Dom에 직접 접근하는 것은 안좋을 것 같고, [ByTestId](https://testing-library.com/docs/queries/bytestid#api)이 api를 사용하면 될까요??

2022-07-06 14:13 UTC, daadaadaah reviewed
> 그리고 Regions 컴포넌트 테스트에서 listitem role로 엘리먼트를 검색하는 방법 말고 다른 방법이 어떤게 있나요? 잘 모르겠습니다 ㅠㅠ
혹시 [ByTestId](https://haeguri.github.io/2020/12/21/clean-up-jest-mock/) api를 사용하면 될까요??

간단하게 "지역이름이 안보인다" 라고 해도 괜찮고, 
```jsx
     REGIONS.forEach((region) => {
        expect(container).not.toHaveTextContent(region.name);
      });
```

만약 실제 서비스라면, regions이 없는 상황이 어떤 경우인지에 대해 생각해보면, api 통신이 원활하게 이루어지지 않은 경우라서, 사용자에게 "지역을 불러오지 못했습니다." 등이 보인다라고 해도 괜찮을 것 같아요!

2022-07-06 14:13 UTC, daadaadaah commented on src/containers/RegionsContainer.test.jsx
> +    regions: given.regions,
테스트용 데이터는 fixture에 있는 데이터를 활용하는게 좋아요!
다른 테스트에서도 마찬가지로 적용해주세요!ㅎㅎ

2022-07-06 14:13 UTC, daadaadaah commented on src/containers/RegionsContainer.test.jsx
> +      given.regions.forEach((region) => {
테스트용 데이터는 fixture에 있는 데이터를 활용하는게 좋아요!
다른 테스트에서도 마찬가지로 적용해주세요!ㅎㅎ

2022-07-06 14:13 UTC, daadaadaah commented on src/store/async-actions.test.js
> +      await dispatcher(dispatch);
굳이 변수화 하지 않아도 될 것 같아요!

```jsx
      await  loadRegions()(dispatch);
```

2022-07-06 14:13 UTC, daadaadaah commented on src/store/async-actions.test.js
> +    it('calls setRegions action and dispatch', async () => {
"dispatch setRegions" 이렇게 간단히 써주셔도 될 것 같아요!

2022-07-06 14:13 UTC, daadaadaah commented on src/store/async-actions.test.js
> +      fetchRegions.mockResolvedValue(REGIONS);
BeforeEach로 관리하는게 더 좋을 것 같아요!
```jsx
      beforeEach(() => {
        fetchRegions.mockResolvedValue(REGIONS);
      });
```

2022-07-07 03:05 UTC, daadaadaah commented on src/store/async-actions.test.js
> +      expect(dispatch).toBeCalledWith(setRegions(REGIONS));
`redux-mock-store`를 사용해서 실제로 어떤 `actions`을 호출하는지 확인할 수 있어요! 한번 사용해봅시당!
참고 : https://github.com/reduxjs/redux-mock-store

2022-07-07 08:47 UTC, kyh196201 commented
트레이너님 오늘은 시간이 부족해서 피드백 주신 내용 수정하고, 테스트 몇개만 추가했습니다 😂

내일 코멘트에 남겨주신 라이브러리 적용하고, 추가 테스트 및 기능 구현하겠습니다 감사합니다 🙌

2022-07-07 13:16 UTC, daadaadaah reviewed
잘했습니당! 바쁘신 일정 중에 조금씩이라도 PR 날려주시는거 너무 좋아요👍
계속 진행해주세요🔥🔥🔥

2022-07-07 13:16 UTC, daadaadaah commented on src/components/Region.test.jsx
> +  const renderRegion = (region) => render((<Region region={region} onClick={handleClick} />));
사소한 거지만 props가 여러 개일 경우, 세로 정렬이 읽기 더 편한 것 같아요!

2022-07-08 12:02 UTC, kyh196201 commented
트레이너님 지역 관련된 테스트 코드랑 기능 구현 거의다 완료해가네요!

그리고 질문이 있습니다.

---

1. 선택된 지역인지 판단하는 로직이 어디에 위치하면 좋을지 궁금합니다.

Region 컴포넌트는 `selected` props를 전달받고,
이 `selected`는 Regions 컴포넌트에서 계산해서 내려주고 있는데, Region 컴포넌트 내부에서 선택되었는지를 판단하는게 더 좋을까요??

2. Regions 컴포넌트가 `selectedRegionId`라는 props를 받고 있는데, state에서는 `regionId`라고 선언해서 사용하고 있습니다. 
Regions 컴포넌트에는 선택된 지역 ID라는 의미를 강조하고 싶어서 props 명을 저렇게 설정했는데, 두 변수명을 맞추는게 좋을까요??

3. 선택된 지역이 있을 경우 '(V)' 문구가 렌더링되었는지 확인하기 위해서 Regions와 Region에서 아래처럼 테스트 코드를 작성했습니다.
혹시 더 좋은 방법이 있는지 트레이너님의 생각이 궁금합니다!

- Regions

```javascript
expect(container).toHaveTextContent('(V)');
```

2022-07-09 03:08 UTC, daadaadaah requested changes
지역 관련 코드가 거의 완성되어가고 있네요!👍 남은 주말에 다른 기능도 완성시켜봅시당!🚀🚀🚀

그리고, 컴포넌트나 함수 만드실 때, `default function parameter` 많이 활용하시는 것 같은데, 자신만의 기준을 가지고 활용해보시는게 좋을 거 같아요! redux에서의 state 초기값이랑 UI 컴포넌트에서의 `default function parameter`의 초기값을 깜박하고 다르게 넣어주면, 버그가 발생할 수도 있을 것 같아서요!


> 1. 선택된 지역인지 판단하는 로직이 어디에 위치하면 좋을지 궁금합니다.
Region 컴포넌트는 `selected` props를 전달받고, 이 `selected`는 Regions 컴포넌트에서 계산해서 내려주고 있는데, Region 컴포넌트 내부에서 선택되었는지를 판단하는게 더 좋을까요??

- 말씀하시는 선택된 지역인지 판단하는 로직이 아래 코드 말씀하시는거 맞나용?ㅎㅎ
```jsx
const isSelected = (region) => region.id === selectedRegionId;
```
- 어떤 로직이 어디에 있으면 좋을지를 판단할 때에는 각 컴포넌트의 관심사가 무엇인지에 대해 생각해보고 결정할 것 같아요! 지금 Region 컴포넌트는 그냥 자기가 선택 받았는지 여부만 알면 되므로, 그 상태만 props로 내려주면 될 것 같아요! 또한, 이와 관련해서 redux에서 `regionsId`로 선택된 region을 관리하고 있으니, 이 상태를 활용해보세요!


> 2. Regions 컴포넌트가 `selectedRegionId`라는 props를 받고 있는데, state에서는 `regionId`라고 선언해서 사용하고 있습니다. 
Regions 컴포넌트에는 선택된 지역 ID라는 의미를 강조하고 싶어서 props 명을 저렇게 설정했는데, 두 변수명을 맞추는게 좋을까요??

- selectedRegionId로 sync를 맞춰주는 것이 좋을 것 같아요! state에서 `regionId`만 있으면, 언제 필요한 상태인지라는 의문이 생겨요!

> 3. 선택된 지역이 있을 경우 '(V)' 문구가 렌더링되었는지 확인하기 위해서 Regions와 Region에서 아래처럼 테스트 코드를 작성했습니다.
혹시 더 좋은 방법이 있는지 트레이너님의 생각이 궁금합니다!

```javascript
expect(container).toHaveTextContent('(V)');
```

그냥 `(V)` 표시보다 `서울(V)` 이런식으로 구체적으로 적는게 좋을 것 같아요!

2022-07-09 03:08 UTC, daadaadaah commented on src/components/Regions.jsx
> +              selected={isSelected(region)}
props 네이밍은 `isSelected` 이고, function 네이밍은 `selectRegion`이런건 어떠신가요?

2022-07-09 03:08 UTC, daadaadaah commented on src/store/reducer.js
> +  regionId: null,
그냥 `regionId`라고 하면, 어떨 때 필요한 `regionId`이지? 라는 생각이 들어요!
좀더 의도를 드러내봅시당!ㅎㅎ

2022-07-09 03:08 UTC, daadaadaah commented on src/containers/RegionsContainer.jsx
> +        onClickRegion={handleClickRegion}
`selectedRegionId` props로 redux의 `regionId`를 활용해보시는 건 어떠신가요?

2022-07-10 08:11 UTC, kyh196201 commented on src/components/Regions.jsx
> +              selected={isSelected(region)}
감사합니다! 항상 이벤트 핸들러를 props로 전달할 때 `on`을 붙여야된다는 고정관념?이 있었는데 `selectRegion`이 훨씬 의미도 드러나고 좋은 것 같습니다 감사합니다 🙌

2022-07-10 08:14 UTC, kyh196201 commented on src/containers/RegionsContainer.jsx
> +        onClickRegion={handleClickRegion}
앗 이 부분도 아직 구현하지 못한 코드였는데, 추가했습니다 감사합니다 ㅎㅎ

2022-07-10 12:26 UTC, kyh196201 commented
트레이너님 이번 한 주도 너무 감사했습니다! 😊

피드백 주신 내용 적용하고, 나머지 추가 기능 구현했는데, 커버리지 테스트가 아직 통과를 못했네요 이 부분은 마저 리팩토링 진행하겠습니다!!

알려주신 `redux-mock-store`는 결국 적용을 못해봤습니다 ㅠㅠ

2022-07-10 16:14 UTC, daadaadaah commented on src/components/Regions.jsx
> +              selected={isSelected(region)}
제가 의도한 건 `isSelected`을 `selectRegion`변경하는 걸 말하는 거였는데, 설명이 부족했네용😅

2022-07-11 01:08 UTC, daadaadaah commented on src/components/Regions.jsx
> +              selected={isSelected(region)}
`onSelectRegion`을 의도한건대ㅎㅎ제가 설명이 부족했네용😂 다음에는 좀더 명확하게 코멘트드리도록 하겠습니당!

2022-07-11 01:19 UTC, daadaadaah reviewed
이번주도 수고하셨어요! 이번주 돌아보면서 주간회고 한번 작성해보세요~ 😃

2022-07-11 01:19 UTC, daadaadaah commented on src/App.test.jsx
> +jest.mock('./store/async-actions');
이렇게 mocking 해주실 때, ` __mocks__`폴더 하나 만들어서 mocking하는 함수 넣어주시고, 테스트 코드에서 mockImplement 해주셔야됩니당!ㅎㅎ

2022-07-11 14:19 UTC, kyh196201 commented on src/components/Regions.jsx
> +              selected={isSelected(region)}
아닙니다 트레이너님 ㅎㅎ 항상 좋은 피드백 너무 감사해요😊

2022-08-01 08:13 UTC, merged