레스토랑 조회 구현 (비동기)
CodeSoom/react-week5-assignment-1 pull request #116
Opened 2022-08-31 12:12 UTC by 0-Chan

안녕하세용..!

시작이 반 이라고 생각하고.. 초기 부분 PR 요청드립니다.ㅎㅎ

강의 보고 만든 완성본을 참고하여 맨땅에서 시작하려니 어떻게 방향을 잡아야할지 헤매고 있네욥.

암튼 이번 주 최선을 다해서 끝까지 :red_circle: -> :green_circle: -> :recycle: 반복반복 정진 하겠습니다!!!

2022-08-31 13:51 UTC, daadaadaah commented
시작이 반이죵! 빠른 PR 잘 하셨어요👍
1. 테스트 먼저 작성하시는 습관이 아직 익숙하지 않으신것 같아요!
예를 들어, [🟢 Add both Containers test](https://github.com/CodeSoom/react-week5-assignment-1/pull/116/commits/7410aff9aad7426509511aa358644fd51f7de583)은 [✨ Add Regions and Categories to container](https://github.com/CodeSoom/react-week5-assignment-1/pull/116/commits/45570a2b6d03b1811ce4e57eb1656c1cea8a2a59) 커밋보다 먼저 작성했어야 된다고 생각해요!
이제부터라도 커밋 메시지를 봤을 때, 🔴 -> 🟢 -> ♻️  순서가 되도록 작업을 진행해봅시당!

2. 작업 단위도 좀더 작게 쪼개서 진행하는게 좋을 것 같아요!
예를 들어, [Add Regions / Categories tests](https://github.com/CodeSoom/react-week5-assignment-1/pull/116/commits/4095ee73cf7e580cb739c2258e2dc6bd881abcba) 이 커밋 보다 작은 커밋 2개로 날리는게 좋겠죵??

계속 작업 진행해주세요!ㅎㅎ

2022-08-31 14:25 UTC, daadaadaah requested changes

2022-08-31 14:25 UTC, daadaadaah commented on src/Buttons.test.jsx
> +});
1. describe에는 테스트 대상을 표현해주는 거예요! 지금 테스트 대상은 Buttons 입니다!
Regions와 Categories 컴포넌트는 현재 구현이 안되어있어요! 만약, 이를 테스트 하고 싶으면, 이 컴포넌트를 만들고, 이 컴포넌트에 대한 테스트를 작성해주셔야할 것 같아요!ㅎㅎ

2. Buttons 컴포넌트를 재활용하는 것과 Button 컴포넌트를 재활용하는 것 중 어느 것이 좀더 활용도 높은 컴포넌트일지 한번 생각해보세요!

2022-09-01 06:54 UTC, 0-Chan commented on src/Buttons.test.jsx
> +});
> 2. 어느 것이 좀더 활용도 높은 컴포넌트일지 한번 생각해보세요!

엄.. Buttons를 재활용한 이유는 같은 역할을 하는 컴포넌트의 갯수를 줄이면 좋지 않을까 생각해서 만들었는데요.

이유는 잘 모르겠지만 느낌상 Regions, Categories를 되살리는게 나을 것 같다는 생각이 드네요...

2022-09-01 12:20 UTC, daadaadaah commented
계속 작업중이신건가용?ㅎㅎ

2022-09-01 12:27 UTC, 0-Chan commented
> 계속 작업중이신건가용?ㅎㅎ

앗.. 일단 컴포넌트 단은 멈춘 상태입니다.

그리고 reducer 쪽 테스트를 이제 작성하려 하고 있습니다!!

2022-09-01 12:33 UTC, daadaadaah commented
> > 계속 작업중이신건가용?ㅎㅎ
> 
> 앗.. 일단 컴포넌트 단은 멈춘 상태입니다.
> 
> 그리고 reducer 쪽 테스트를 이제 작성하려 하고 있습니다!!

작업 완료하시고 코멘트 남겨주세요! 이후에 리뷰해드릴게요~!

2022-09-01 12:36 UTC, 0-Chan commented
> > > 계속 작업중이신건가용?ㅎㅎ
> > 
> > 앗.. 일단 컴포넌트 단은 멈춘 상태입니다 . . .
> 
> 작업 완료하시고 코멘트 남겨주세요! 이후에 리뷰해드릴게요~!

감사합니닷..:sob: 빠르게 작성하고 코멘트 드리겠습니다!!

2022-09-01 13:12 UTC, 0-Chan commented
> > > > 계속 작업중이신건가용?ㅎㅎ
> > > 
> > > 
> > > 앗.. 일단 컴포넌트 단은 멈춘 상태입니다.
> > > 그리고 reducer 쪽 테스트를 이제 작성하려 하고 있습니다!!
> > 
> > 
> > 작업 완료하시고 코멘트 남겨주세요! 이후에 리뷰해드릴게요~!
> 
> 감사합니닷..sob 빠르게 작성하고 코멘트 드리겠습니다!!

일단 selectedRegion 이라는 액션을 만들어서 :red_circle: -> :green_circle: 까지 완료 했습니다!

여기 까지 작업하고 이후에 마저 리팩터링 하도록 하겠습니다..ㅎㅎ 

시간 주셔서 감사해요 ㅜㅜ 아직 미숙해서 금방금방 하기가 어렵네요. 
(특히 컴포넌트 구조가 너무나도 헷갈리는 상태입니다.)

2022-09-01 13:55 UTC, daadaadaah requested changes
마지막 커밋 2개 TDD로 작성하신 거 잘하셨어요!👍

아샬님이 어떤 순서로 했는지 되새겨보시면서 따라해보시는 것도 좋아요!ㅎㅎ

2022-09-01 13:55 UTC, daadaadaah commented on src/reducer.test.js
> +} from './actions';
이거 자체도 없는게 RED로 볼 수 있을 것 같아요!
아직 selecteRegion을 안 만든 상태이니!

2022-09-01 13:55 UTC, daadaadaah commented on src/App.test.jsx
> +  context('render App', () => {
context 빼도 괜찮을 것 같아요!

2022-09-01 13:55 UTC, daadaadaah commented on src/Button.test.jsx
> +const appComponent = (item, selected) => render(
`appComponent`라고 하면, 이 코드를 처음 본 동료가 `AppComponent`랑 착각할 수 있을 것 같아요! 함수가 하는 일이 드러나게 네이밍해봅시당!

2022-09-01 13:55 UTC, daadaadaah commented on src/Button.test.jsx
> +    key={item}
key는 왜 필요한거죵?

2022-09-01 13:55 UTC, daadaadaah commented on src/Categories.jsx
> +            <button type="button">
여기서도 `Button` 컴포넌트를 활용할 수 있지 않을까용?ㅎㅎ

2022-09-01 13:55 UTC, daadaadaah commented on src/Regions.test.jsx
> +  });
context는 상반된 상황에서 사용하는 것입니당! context를 사용하고 싶으시면, `without selected region` 상황도 테스트 코드로 작성해주시는게 좋을 것 같아요! 8번째 줄 테스트를 수정하셔도 될 것 같구~

2022-09-01 13:55 UTC, daadaadaah commented on src/Categories.test.jsx
> +describe('<Categories />', () => {
작성하신 `Region` 테스트 참고해서 수정해봅시다! 데이터가 categories랑 regions 라는 것만 빼면 비슷한 상황을 기대하고 테스트하는 방식이니~

2022-09-02 04:08 UTC, 0-Chan commented on src/App.test.jsx
> +  context('render App', () => {
대비 되는 내용도 없는데 거추장스러운 context 였네요! 삭제 했습니다.

2022-09-02 04:09 UTC, 0-Chan commented on src/Regions.test.jsx
> +  });
Line 8 테스트를 without를 넣어서 수정하였습니다.^^

2022-09-02 04:10 UTC, 0-Chan commented on src/reducer.test.js
> +} from './actions';
아 그렇군요. RED 와 GREEN의 차이를 쪼끔 알 것 같습니다..

2022-09-02 04:38 UTC, 0-Chan commented on src/Button.test.jsx
> +const appComponent = (item, selected) => render(
앗 그 생각은 못했네요. 이름을 `renderButton` 으로 명시적으로 하는 일을 드러내 보았습니다.

2022-09-02 04:40 UTC, 0-Chan commented on src/Button.test.jsx
> +    key={item}
지우고 테스트 해봤더니.. 전혀 쓸모 없는 key 였습니다. 지웠습니다!

2022-09-02 09:17 UTC, 0-Chan commented on src/Categories.test.jsx
> +describe('<Categories />', () => {
넵 참고하여 적용 해보았습니다.

더 나아가 given2를 써서 리팩토링 하였는데요.
1. 테스트 중 바뀌는 부분을 더 명시적으로 만들고,
2. `no-shadow` eslint 문제를 해결하였습니다.

2022-09-02 11:46 UTC, 0-Chan commented
일단 Red -> Green 으로 작업 중 error를 해결하지 못한 상태에서 커밋 하였습니다.

제가 <CategoriesContainer /> 테스트 까진 잘 짰다고 생각했는데요.
그 이후에 `useSelector`의 mockImplementaion을 적용하려니까 <App /> 부터 시작해서 api, actions, reducer 까지.. 건들이게 되었는데요.

어디서 부터 제 TDD 과정이 잘못 된걸까요 ㅜㅜㅜ..
그리고 테스트 중 아래와 같은 error가 발생하는데.. 
![image](https://user-images.githubusercontent.com/50035753/188132838-ddbe6a0b-0983-4b7d-8bb9-be441c8bb170.png)
일단 내일 까지 최대한 잡아보도록 하겠습니다.. 감사합니다..

2022-09-02 13:59 UTC, daadaadaah requested changes
코멘트 드린 부분 작업하실 때, 작업단위로 커밋이 잘 들어가서 리뷰하기 편했습니당! ㅎㅎ 또한, 에러난 상태지만 커밋하신 점 너무 잘하셨어요!👍
아마 제가 코멘트 드린 부분에서 에러해결에 대한 힌트를 얻으실 수 있을 거예요!ㅎㅎ

> 처음 의도는 테스트에 useSelector.mockImplementaion를 해놓고 대충 jsx에서도 useSelector 쓰면 되겠지 하는 생각 이었습니다.
> 그런데 웬걸 App 부터 시작해서 api, actions, reducer 까지.. 모두 테스트를 짜지도 않은 상태에서 건들이게 되었습니다.
> 아직 리액트 구조에 익숙하지 않아서 그런 것 같은데요.. 어디서 부터 테스트를 짰어야 올바른 접근 이었을까요..?

음... 어떻게 했어야 된다고 생각하셨는데, 어떻게 진행한게 아쉬웠는지  좀더 설명해주실 수 있나요?

2022-09-02 13:59 UTC, daadaadaah commented on src/App.test.jsx
> +    categories: {},
App 쪽 테스트 작성중이신 것 같은데, `categories`가 객체가 아니라 배열이라는 거 체크하시구 진행해주세요!ㅎㅎ

2022-09-02 13:59 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +import categories from '../__fixtures__/data';
categories를 fixtures에서 default export로 해주셨을까요? export로 해주셨을까요?ㅎㅎ

2022-09-02 13:59 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +jest.mock('../__mocks__/react-redux');
아샬님은 아래처럼 써주셨을 거예요!
```js
jest.mock('react-redux');
```

2022-09-03 10:30 UTC, 0-Chan commented on src/CategoriesContainer.test.jsx
> +import categories from '../__fixtures__/data';
앗..아앗... 잘 보고 작성 했어야 하는데 :smiling_face_with_tear: 짚어주셔서 감사합니다..!

2022-09-03 10:31 UTC, 0-Chan commented on src/CategoriesContainer.test.jsx
> +jest.mock('../__mocks__/react-redux');
넵 그렇네요..! 축약해서 작성 하였습니다.

2022-09-03 12:03 UTC, 0-Chan commented
> 코멘트 드린 부분 작업하실 때, 작업단위로 커밋이 잘 들어가서 리뷰하기 편했습니당! ㅎㅎ 또한, 에러난 상태지만 커밋하신 점 너무 잘하셨어요!+1 아마 제가 코멘트 드린 부분에서 에러해결에 대한 힌트를 얻으실 수 있을 거예요!ㅎㅎ
> 

이전에 git 작업이 익숙하지 않아 중구난방으로 커밋을 드리긴 한 것 같네요 :sweat_smile:
앞으로 계속 신경써서 작업 단위로 커밋 드리도록 하겠습니다.

 > > 처음 의도는 테스트에 ...
> > 아직 리액트 구조에 익숙하지 않아서 그런 것 같은데요.. 어디서 부터 테스트를 짰어야 올바른 접근 이었을까요..?
> 
> 음... 어떻게 했어야 된다고 생각하셨는데, 어떻게 진행한게 아쉬웠는지 좀더 설명해주실 수 있나요?

처음 계획은 Down->Top 구조로 `Buttons` 같은 작은 컴포넌트 부터 시작해서 점점 큰 쪽으로 테스트를 작성 해가며 완성 시키려고 했었습니다.

그런데 하다보니 뭔가 이곳 저곳을 다 건들인다는 느낌이 들어서요.

2022-09-03 14:20 UTC, daadaadaah requested changes
1. 하루하루 발전하고 계시는 모습을 보니 너무 좋습니당!👏
2. `loadRegions`는 다음 PR에 추가해주시나용?

> 처음 계획은 Down->Top 구조로 Buttons 같은 작은 컴포넌트 부터 시작해서 점점 큰 쪽으로 테스트를 작성 해가며 완성 시키려고 했었습니다.
> 그런데 하다보니 뭔가 이곳 저곳을 다 건들인다는 느낌이 들어서요.
- 상향식이든 하향식이든 틀린 방식은 없어요! 둘다 상황에 맞게 개발자 취향에 맞게 하시면 됩니당!
- 이곳 저곳 건든다는 말씀이 하위컴포넌트 추가할 때마다 다른 컴포넌트의 테스트들에서 에러가 나서 그부분도 수정해줘야 하는 것을 말씀하시는건가용?ㅎㅎ

2022-09-03 14:20 UTC, daadaadaah commented on src/App.test.jsx
> +  }));
맥락 구분을 위해 한줄씩 띄어줍시당!ㅎㅎ

2022-09-03 14:35 UTC, 0-Chan commented
> 1. 하루하루 발전하고 계시는 모습을 보니 너무 좋습니당!👏
> 
> 2. `loadRegions`는 다음 PR에 추가해주시나용?
> 
> 
> 
> > 처음 계획은 Down->Top 구조로 Buttons 같은 작은 컴포넌트 부터 시작해서 점점 큰 쪽으로 테스트를 작성 해가며 완성 시키려고 했었습니다.
> 
> > 그런데 하다보니 뭔가 이곳 저곳을 다 건들인다는 느낌이 들어서요.
> 
> - 상향식이든 하향식이든 틀린 방식은 없어요! 둘다 상황에 맞게 개발자 취향에 맞게 하시면 됩니당!
> 
> - 이곳 저곳 건든다는 말씀이 하위컴포넌트 추가할 때마다 다른 컴포넌트의 테스트들에서 에러가 나서 그부분도 수정해줘야 하는 것을 말씀하시는건가용?ㅎㅎ
> 
> 

감사합니다.ㅎㅎ 일단 loadRegions는 actions에 추가한 상태입니다.

아아 개발자가 상황에 맞게 작업하면 되는거군요. 그리고 네 다른 테스트들이 깨지는 경우가 생겨서 그렇습니다.

2022-09-03 16:33 UTC, daadaadaah commented
> 아아 개발자가 상황에 맞게 작업하면 되는거군요. 
- 이번주에는 하향식으로 해봤으니, 다음주는 상향식으로 도전해보세요! 다양한 시도를 언제나 좋습니다! 

> 그리고 네 다른 테스트들이 깨지는 경우가 생겨서 그렇습니다.
- 다른 테스트 깨지는게 나쁜게 아니라 테스트가 주는 좋은 신호예요!ㅎㅎ여기에 이런게 필요해~ 하면서 개발자에게 알려주는 것이거든용!ㅎㅎ
좋은 경험하신겁니당!ㅎㅎ

2022-09-04 13:04 UTC, daadaadaah commented
계속 작업중이신건가요? 완료되신건가요?

2022-09-04 13:08 UTC, 0-Chan commented
> 계속 작업중이신건가요? 완료되신건가요?

흑... 거의 다 했는데요. 지금 `loadRestaurants` 를 띄우는 부분에서 막혀서 해결 중 이었습니다.
버튼을 누르면 regionName과 categoryId 둘 다 undefined 가 뜨고 있어서요... (현재 로컬 작업 중입니다.)

2022-09-04 13:18 UTC, daadaadaah commented
작업 다 완료되시면 코멘트 남겨주세요~ 그 이후에 리뷰해드릴게요!ㅎㅎ

그리고, 9시 이후에 계속 작업중이시면, 미리 코멘트 남겨주시는게 좋을 것 같아요😊
리뷰어 입장에서 언제 리뷰해드려야 하는지 고민이고, 리뷰도중에 코드가 수정되면 다시 또 봐야되는 불편함이 있어요😭

2022-09-04 13:24 UTC, 0-Chan commented
> 작업 다 완료되시면 코멘트 남겨주세요~ 그 이후에 리뷰해드릴게요!ㅎㅎ
> 
> 그리고, 9시 이후에 계속 작업중이시면, 미리 코멘트 남겨주시는게 좋을 것 같아요blush 리뷰어 입장에서 언제 리뷰해드려야 하는지 고민이고, 리뷰도중에 코드가 수정되면 다시 또 봐야되는 불편함이 있어요sob

앗.. 그렇군요.. 앞으로 가능한 9시 이전에 끝내고 만약 진행 중이라면 코멘트를 꼭 남기겠습니다.. 죄송합니다ㅜㅜ

2022-09-04 14:49 UTC, 0-Chan commented on src/App.test.jsx
> +  }));
넵 중간중간 띄워서 보기좋은 코드를 만들었습니다!

2022-09-05 03:41 UTC, daadaadaah requested changes
이번주도 수고많으셨습니당!ㅎㅎ다음주에도 화이팅해봐요!👊

2022-09-05 03:41 UTC, daadaadaah commented on src/Button.test.jsx
> +import { region, category } from '../__fixtures__/data';
맥락 구분을 위해 한줄 띄어줍시당!

2022-09-05 03:41 UTC, daadaadaah commented on src/actions.test.js
> +});
테스트 마다 독립적이게 동작하기 위해서 store를 테스트마다 어떻게 해주는게 좋을까요?

2022-09-05 03:41 UTC, daadaadaah commented on src/Button.test.jsx
> +const renderButton = (item, selected) => render(
RORO 패턴을 이용해도 괜찮을 것 같아요!

참고: https://www.freecodecamp.org/news/elegant-patterns-in-modern-javascript-roro-be01e7669cbd/

2022-09-05 03:41 UTC, daadaadaah commented on src/App.test.jsx
> +jest.mock('../__mocks__/react-redux');
이렇게 간단히도 써줄 수 있어요!
```js
jest.mock('react-redux');
```

2022-09-05 03:41 UTC, daadaadaah commented on src/App.test.jsx
> +  };
fixtureState로 따로 빼주신 특별한 이유가 있으신가요? useSelector에 데이터들 바로 넣어줘도 되거든용!ㅎㅎ

2022-09-05 03:41 UTC, daadaadaah commented on src/Button.test.jsx
> +      const { container } = renderButton({ region, selected });
renderButton 매개변수 형태 다시 한번 체크해봅시당!

2022-09-05 03:41 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +      expect(typeof dispatch.mock.calls[1][0]).toBe('function');
좀더 간단하게 표현하는 방법은 없을까요?

2022-09-05 03:41 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +        selectedRegion: region,
`KOREAN_FOOD`처럼 `region`도 1개의 데이터를 명시적으로 표현해주시면 좋을 것 같아요!

2022-09-05 03:41 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +    it('load restaurants', () => {
`render restaurants`로 써주시면, 통일감 있을 것 같아요!

2022-09-05 03:41 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +        expect(dispatch).toBeCalledWith(selectCategory(category));
행위-기대 라는 다른 맥락을 가지고 있으므로, 한줄 띄어줍시당!

2022-09-05 03:41 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +      expect(container).toHaveTextContent(KOREAN_FOOD.name);
이 테스트 결과는 어떤 의도에서 작성해주신건가용?ㅎㅎㅎ

2022-09-05 03:41 UTC, daadaadaah commented on src/Regions.test.jsx
> +    it('renders region with check mark(V)', () => {
맥락 구분 해주시구~ `selectedRegion` 변수화 하지 않고 그냥 `regions[0]`을 사용해도 좋을 것 같아요! 아니면 ` KOREAN_FOOD` 처럼 데이터를 명시적으로 드러내주고 사용해주셔도 되구요!

2022-09-05 03:41 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +    });
given을 활용해봅시당!👊 (다른 테스트코드에서도 마찬가지구요!)

2022-09-05 04:02 UTC, merged