5주차 - 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #122
Opened 2022-11-09 08:05 UTC by yxxnhx

# 목표
레스토랑 조회 구현하기

### 구현사항
- [ ] 레스토랑 지역 불러오기
- [ ] 레스토랑 카테고리 불러오기
- [ ] 레스토랑 목록 불러오기
- [ ] 지역, 카테고리 선택 시 체크표시 나오기
- [ ] 지역, 카테고리 모두 선택 시 해당 레스토랑 목록 나타내기

### 진행사항 
안녕하세요 트레이너님!

2022-11-10 07:28 UTC, daadaadaah requested changes
> 현재 API를 호출까지는 해놓은 상태입니다. 이제 각각의 지역과 목록을 체크하면 그에 맞는 레스토랑이 나올 수 있게 하는 방법에 대하여 고민 중입니다

- 좋습니다! 빠르게 PR 날려주시면서 진행상황까지 코멘트에 남겨주신 점 너무 잘하셨어요👏 
차근차근 하나씩 해봅시당!👊

2022-11-10 07:28 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +      ],
잘 만들어 놓으신 fixture를 활용해봅시다!ㅎㅎ(다른 테스트에도 fixture를 적용해볼만한 곳이 없을까 한번 체크해보세요~)

2022-11-10 07:28 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +  it('목록이 랜더링된다', () => {
어떤 목록인지도 같이 적어주시면, 더 좋을 것 같아요!ㅎㅎ

2022-11-10 07:28 UTC, daadaadaah commented on src/RegionsContainer.test.jsx
> +  it('지역이 랜더링된다', () => {
지역 보다 지역 목록 등 복수형이라는 의도를 더 들어내주는게 좋을 것 같아요!ㅎㅎ

2022-11-10 07:28 UTC, daadaadaah commented on src/reducer.test.js
> +  });
`목록`이라는 의도를 좀더 드러나게 테스트 내용을 표현해주시는게 좋을 것 같아요!

2022-11-10 13:42 UTC, yxxnhx commented on src/CategoriesContainer.test.jsx
> +      ],
앗 넵! 수정하겠습니다

2022-11-10 13:43 UTC, yxxnhx commented on src/RegionsContainer.test.jsx
> +  it('지역이 랜더링된다', () => {
넵 복수형으로 수정하겠습니다!

2022-11-10 13:43 UTC, yxxnhx commented on src/reducer.test.js
> +  });
넵 의도를 드러낼 수 있도록 목록을 추가하여 수정하겠습니다

2022-11-10 13:49 UTC, yxxnhx commented
# 진행사항
현재 지역과 카테고리를 선택 시 (V)까지 나타낼 수 있도록 하였습니다.
이제 이 선택된 지역과 카테고리를 받아서 레스토랑 목록이 보일 수 있도록 진행중입니다.

## 질문사항
``` jsx
const isSelected = (category) => {
    if (isSelected === null) {
      return false;
    }

    return category.id === selectedCategoryId;
  };
```
현재 선택한 카테고리의 id를 카테고리의 id로 넘기고 만약 선택한 것이 아닐 때는 false를 반환하도록 하였습니다.

``` jsx
  context('카테고리 아이디가 없을 시', () => {
    it('"V"가 랜더링되지 않는다', () => {
      const category = categoryList[0];
      const { container } = renderCategories({
        categories: category,
        selectedCategoryId: null,
      });

      expect(container).not.toHaveTextContent('(V)');
    });
  });
```
그래서 아이디가 없을 시에는 (V)가 없다고 테스트를 하였는데 테스트 커버리지에서 해당 부분이 테스트가 되지 않았다고 합니다
그렇다면 말 그대로 테스트 코드에 toBeFalsy가 있어야 하는건가요?
아니면 다른 방법이 있을까요?😢

2022-11-11 07:05 UTC, daadaadaah requested changes
> 테스트 커버리지에서 해당 부분이 테스트가 되지 않았다고 합니다

테스트 커버리지 상태를 같이 보여주시면 답변에 도움될 것 같아요!ㅎㅎ

2022-11-11 07:05 UTC, daadaadaah commented on src/Categories.jsx
> +    if (isSelected === null) {
`selectedCategoryId` 상태를 활용해서 선택 유무 판별할 수 있을 것 같은데, isSelected라는 함수로 빼신 이유가 궁금합니다!

2022-11-11 07:05 UTC, daadaadaah commented on src/Categories.test.jsx
> +  context('카테고리 데이터가 없을 시', () => {
`데이터` 라는 용어를 빼도 의도 전달에 문제가 없을 것 같아요! 대신 카테고리 목록이라 표현해주시는건 어떠신가여?ㅎㅎ

2022-11-11 07:05 UTC, daadaadaah commented on src/Categories.test.jsx
> +  context('카테고리 아이디가 있을 시', () => {
`선택한 카테고리 아이디가 잇을 시` 라고 표현하는게 좀더 적절해보이는데, 어떻게 생각하세여?ㅎㅎ

2022-11-11 07:05 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +  context('카테고리를 클릭 시', () => {
context는 대비되는 상황에서 사용하는게 적절해요! 지금은 대비되는 상황이 없으니 그냥 it문에 표현해주셔도 될 것 같아요!ㅎㅎ

2022-11-11 07:05 UTC, daadaadaah commented on src/Category.test.jsx
> +  context('카테고리를 선택하면', () => {
지금 현재 props로 내려준 상태에 대해 테스트 하는 것이므로, 테스트 코드에 선택한다는 의미가 담긴 표현이 없습니다. 그래서, `선택된 카테고리가 있으면` 이 좀더 적절하지 않을까 하는데, 어떻게 생각하시나요?

2022-11-11 07:05 UTC, daadaadaah commented on src/Regions.test.jsx
> +  context('카테고리 데이터가 없을 시', () => {
it문이 빠졌어요!

2022-11-11 08:06 UTC, yxxnhx commented on src/Categories.jsx
> +    if (isSelected === null) {
선택된 것을 조금 더 명확하게 해주고 싶어서 따로 빼서 확인하는 함수를 만들어서 사용을 했는데 굳이 필요가 없다면 그냥 `isSelected` 자리에 그대로 `selectedCategoryId`를 넣어서 사용하는 것이 더 옳은 것일까요?

2022-11-11 08:09 UTC, yxxnhx commented on src/Categories.test.jsx
> +  context('카테고리 데이터가 없을 시', () => {
아 그렇군요! 데이터 대신 목록으로 수정하겠습니다~!

2022-11-11 08:09 UTC, yxxnhx commented on src/Categories.test.jsx
> +  context('카테고리 아이디가 있을 시', () => {
아 그렇네요 카테고리 전체는 다 아이디가 있으니까요ㅠㅠ 수정하겠습니다!

2022-11-11 08:11 UTC, yxxnhx commented on src/CategoriesContainer.test.jsx
> +  context('카테고리를 클릭 시', () => {
아하 그렇군요! 수정하겠습니다~!

2022-11-11 08:14 UTC, yxxnhx commented on src/Category.test.jsx
> +  context('카테고리를 선택하면', () => {
그렇네요! 선택이 되었다는 표현이 조금 더 정확한 것 같아요!

2022-11-11 08:18 UTC, yxxnhx commented on src/Regions.test.jsx
> +  context('카테고리 데이터가 없을 시', () => {
아이고.. 넵 바로 수정하겠습니다~!

2022-11-11 08:18 UTC, yxxnhx commented
> > 테스트 커버리지에서 해당 부분이 테스트가 되지 않았다고 합니다
> 
> 테스트 커버리지 상태를 같이 보여주시면 답변에 도움될 것 같아요!ㅎㅎ

2022-11-11 08:30 UTC, yxxnhx commented
# 진행사항
레스토랑 목록을 불러와서 해당하는 레스토랑 목록이 화면에 나타날 수 있도록 하였습니다
현재 테스트 코드를 작성 중입니다.

### 스크린샷
![Nov-11-2022 17-25-22](https://user-images.githubusercontent.com/50559373/201298041-01756f8e-0e60-4699-97db-41c436599f0a.gif)

### 질문사항
<img width="609" alt="image" src="https://user-images.githubusercontent.com/50559373/201298761-7f7dfdb2-5f91-49c2-bc53-a1848335fce6.png">

테스트 커버러리지에서 20번째 줄, 아무것도 반환하지 않는 부분의 테스트를 위하여

<img width="703" alt="image" src="https://user-images.githubusercontent.com/50559373/201298451-159933fe-43d0-414f-a88f-ffb6c5173524.png">

위와 같이 RestaurantsContainer에서 선택된 카테고리나 지역이 없을 시에는 dispatch가 실행되지 않은 부분을 테스트를 추가하려 위와 같이 작성을 하면 이미 함수가 호출되었다고 계속 에러가 납니다
왜 그런 것일까요?ㅠㅠ


그리고 actions의 loadRestaurnts 혹은 api의 fetch를 테스트를 하기 위해서 하다가 계속 막혀서 다른 분들이 것을 참고하려 보니 다른 라이브러리를 사용해서 store을 mock으로 사용할 수 있게 하시던데 다른 라이브러리를 꼭 깔아야만 하는건가요?

2022-11-12 07:47 UTC, yxxnhx commented
# 진행사항
actions에서 loadRegions, loadCategories, loadRestaurants까지 테스트 마쳐 테스트 커버리지까지 통과한 상태입니다
위에서 질문한 dispatch가 호출되지 않는다 대신 loadRestaurants가 호출되지 않는다로 조건을 수정하여 코드를 정리하였습니다

### 질문사항
``` jsx
  useEffect(() => {
    if (selectedRegion === null || selectedCategoryId === null) {
      return;
    }

    dispatch(loadRestaurants(selectedRegion, selectedCategoryId));
  }, [selectedRegion, selectedCategoryId]);
```
그런데 제가 생각하기에는 selectedRegion, selectedCategoryId가 모두 null이면 dispatch가 호출되지 않을 것이라고 생각하였는데 호출을 하는 것일까요?ㅠㅠ

2022-11-12 10:40 UTC, daadaadaah commented on src/Categories.jsx
> +            isSelected={isSelected(category)}
props명과 함수명이 같으면 혼동스러울 것 같아요!

2022-11-12 10:40 UTC, daadaadaah commented on src/Categories.jsx
> +    if (isSelected === null) {
아니요! 그냥 의도가 궁금했어요! 그런데, `selectedCategoryId`로 넘겨주고,  만드신 함수를 Category에서 만들어서 사용해주면, Categories와 Category 각각 의도가 좀더 드러나지 않을까 하는데, 어떻게 생각하시나여?

2022-11-12 10:44 UTC, daadaadaah requested changes
> 그런데 제가 생각하기에는 selectedRegion, selectedCategoryId가 모두 null이면 dispatch가 호출되지 않을 것이라고 생각하였는데 호출을 하는 것일까요?ㅠㅠ

1. 일단 실제 코드의 `selectedCategoryId`이랑 테스트 코드의 `selectedCategory` 먼저 체크해보시는 걸 추천 드립니다.
2. 실제로 호출이 되는지, 그럼 왜 호출이 되는지를 알기 위해 각각의 데이터를 console로 찍어보셨나요? 
3. 추가로, `beforeEach`와 `jest.clearAllMocks();`에 대해서 공부해보세요!

2022-11-12 10:44 UTC, daadaadaah commented on src/RestaurantsContainer.test.jsx
> +        selectedCategory: null,
`selectedCategoryId `랑 `selectedCategory`랑 다른 값을 다루는 변수인가요?

2022-11-13 05:52 UTC, yxxnhx commented on src/Categories.jsx
> +            isSelected={isSelected(category)}
앗 그렇겠네요 반영하여 수정하겠습니다!

2022-11-13 05:53 UTC, yxxnhx commented on src/RestaurantsContainer.test.jsx
> +        selectedCategory: null,
앗 제가 변수명을 통일시키지 못했네요 수정하겠습니다

2022-11-13 05:58 UTC, yxxnhx commented
# 진행사항
`beforeEach`와 `jest.clearAllMocks();`를 활용하여 dispatch가 호출되지 않는 조건으로 일어났던 에러를 해결하였습니다!
그리고 트레이너님 조언을 토대로 Categories와 Regions에서는 각각의 목록 데이터만, Category, Region에서는 데이터를 받아 선택하는 여부를 관리할 수 있게 관심사를 분리하여 그에 맞게 테스트 파일의 조건도 수정해주었습니다.
그리고 이전에 `selectedRegion`, `selectedCategoryId`를 기본값을 `null`을 주었을 때 지역을 선택하지 않고 카테고리만 선택하였을 때 카테고리에 해당하는 식당 목록이 보이는 에러를 잡기 위해 `null`에서 빈값 `''`으로 수정하여 에러를 수정하였습니다.

2022-11-14 05:59 UTC, daadaadaah approved these changes
이번주도 수고 많으셨습니다!ㅎㅎ다음주도 같이 힘내봐요!👊

2022-11-15 12:04 UTC, merged