5주차 과제 - 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #123
Opened 2022-11-09 12:11 UTC by sejineeee

## 내용

api를 호출하는 함수를 먼저 구현해서 커밋하였습니다.

2022-11-10 07:34 UTC, daadaadaah requested changes
한주한주 새로운 개념을 익히시는거 어렵죠ㅠㅠ이전 개념도 여전히 새로운대, 거기에 추가로 또 새로운 개념을 익혀야하니ㅜㅜ그래도, 하나하나 차근차근 하다보면, 금새 익숙해지실 겁니당!ㅎㅎ 다음 PR 기다리고 있을게요~🚀

2022-11-10 07:34 UTC, daadaadaah commented on src/reducer.test.js
> +    it('지역에 대한 데이터를 받아온다.', () => {
reducer 관점에서 표현해주시는게 좋아요! 테스트 대상이 Reducer 이니까요!

2022-11-10 12:12 UTC, sejineeee commented
## 내용
현재 Regions, Categories api 호출 함수를 구현해놓은 상태입니다!
그리고 지금은 해당 버튼을 눌렀을 때, 선택된 정보를 store에 저장하기 위한 액션을 구현하는 중입니다.
아직 테스트는 덜 구현된 상태입니다...😭

2022-11-11 06:15 UTC, daadaadaah requested changes
좋습니다! 나머지 구현하시고 또 PR 날려주세요👊

2022-11-11 06:15 UTC, daadaadaah commented on src/Categories.test.jsx
> +})
한줄 띄어주세요!

2022-11-11 09:15 UTC, sejineeee commented
## 내용
아직 RestaurantContainer, Restaurant, api에 대한 테스트를 진행하지 못한 상황입니다!
reducer에 대한 테스트도 아직 완성되지 못한 상황입니다!
test 파일을 먼저 작성하고, 컴포넌트를 작성해야 되지만... 계속 하다 보면, 저도 모르게 컴포넌트 파일을 먼저 만들고 있습니다 😭
그러고 컴포넌트 파일에 맞게 테스트를 맞추게 돼요ㅠㅠ

## 질문
<img width="1004" alt="스크린샷 2022-11-11 오후 5 57 00" src="https://user-images.githubusercontent.com/86041335/201305524-508b16cd-7e4b-4aee-a23b-0e9211b7230d.png">
<img width="585" alt="스크린샷 2022-11-11 오후 5 58 24" src="https://user-images.githubusercontent.com/86041335/201305534-88691c29-3739-4822-8e96-577bc6773967.png">

"지역과 카테고리를 선택했을 때,  선택된 값에 체크표시가 붙는다" 이렇게 테스트 한 부분이 제 의도와 다르게 테스트가 되어서 고민입니다.
하나씩 다른 방식으로 테스트 해보았는데, 둘 다 동일하게 오작동을 해서 어떤 부분을 고쳐야 될 지 잘 모르겠습니다!
`fireEvent.click` 전에 `not.toBeCalled()`를 해줬는데,

2022-11-12 10:17 UTC, daadaadaah requested changes
> test 파일을 먼저 작성하고, 컴포넌트를 작성해야 되지만... 계속 하다 보면, 저도 모르게 컴포넌트 파일을 먼저 만들고 있습니다 😭

- 아샬님도 테스트 파일이랑 구현 파일 왔다갔다 하면서 TDD 하십니다! 다만, 지금은 훈련중이므로, 의도적으로 테스트 먼저 작성해보시는 걸 권해드립니다!ㅎㅎ이게 습관이 되면, 언제 테스트 먼저 작성해야하는지, 언제 구현 코드 먼저 작성해야하는지 선택적으로 할 수 있기 때문이예요!ㅎㅎ

> "지역과 카테고리를 선택했을 때, 선택된 값에 체크표시가 붙는다" 이렇게 테스트 한 부분이 제 의도와 다르게 테스트가 되어서 고민입니다.
- 리뷰에 관련 내용 남겨드렸습니다!
> 추가적으로 토요일날 작업하여 올렸습니다. 하지만 RestaurantContainer에서 선택된 지역과 카테고리가 있을 경우 dispatch가 호출되는지 테스트 해주고 싶었으나 이렇게 오류가 나타난 상태입니다! useSelector 부분을 잘못한 것인지 잘 모르겠습니다...😭
- 리뷰에 관련 내용 남겨드렸습니다!

2022-11-12 10:17 UTC, daadaadaah commented on src/Regions.test.jsx
> +  });
Regions의 관심사가 무엇일까요?
클릭에 따른 상태 변화를 담당하는 컴포넌트 인가요? 아니면 props로 내려준 상태를 보여주는 컴포넌트인가요?

2022-11-12 10:17 UTC, daadaadaah commented on src/RestaurantContainer.test.jsx
> +  });
it문에 useSelector와 renderRestaurantContainer() 넣어주시고 한번 테스트해보세요!(밑에 테스트도 같이 수정해주세요!)

2022-11-12 10:17 UTC, daadaadaah commented on src/RestaurantContainer.test.jsx
> +    expect(container).toHaveTextContent('레스토랑 정보가 존재하지 않습니다.');
여기에는 useSelector가 빠져있네용? 어느 상황에서 테스트 하고 싶으셨나요?

2022-11-12 10:17 UTC, daadaadaah commented on src/reducer.test.js
> +    it('지역 데이터를 저장한다.', () => {
describe와 It문에 나온 내용을 한 문장으로 만들었을 때 자연스러운 문장이 되도록 작성해주시는게 좋아요! 지금 상황에서 `setRegions는 지역 데이터를 저장한다.` 로 읽히는데, `setRegions는 지역 목록을 변경한다.`가 좀더 적절하지 않을까 하는데, 어떻게 생각하시나여?

2022-11-12 10:17 UTC, daadaadaah commented on src/RestaurantContainer.jsx
> +  }));
24번줄이랑 통합해서 하나의 useSelector로 가져오셔도 됩니다!ㅎㅎ

2022-11-12 10:17 UTC, daadaadaah commented on src/RegionsContainer.jsx
> +    selectedRegionName: state.selectedRegion,
용어를 통일해주시는게 좋아요!

2022-11-12 10:53 UTC, sejineeee commented on src/Regions.test.jsx
> +  });
props로 내려준 상태를 보여주는 컴포넌트입니다!!

2022-11-12 11:23 UTC, daadaadaah commented on src/Regions.test.jsx
> +  });
그럼, props로 무엇을 내려주었고, 그로 인해 UI가 어떻게 보이는지에 대해 테스트하셔야 할 것 같아요!
지금 selectedRegionName으로 '대전'을 내려주면, '대전✅' 로 보여서 '대전'을 클릭할 수 없지 않을까요?

2022-11-13 08:40 UTC, sejineeee commented
## 내용
안녕하세요! 마지막인데...async action에 대한 테스트를 마무리 못 해서 너무 아쉽습니다!
일단 구현해보려고 해봤으나, 에러가 많이 났습니다... 😭
![스크린샷 2022-11-13 오후 5 38 25](https://user-images.githubusercontent.com/86041335/201513264-7c4628ab-5b03-478f-9c79-deb9ec826d97.png)
![스크린샷 2022-11-13 오후 5 38 18](https://user-images.githubusercontent.com/86041335/201513265-452bf5db-f48d-4ec5-b8c8-27733c00a058.png)

다른 분들의 코드를 보고 이해해보고 싶었으나... 이해가 잘 되지 않아서 문제예요!
혹시 비동기를 test 하기 위해서는 어떤 키워드를 알아야 되는지, 혹시 좋은 글이 있다면 공유해주시면 감사하겠습니다!!
이번 한 주도 정말 감사합니다!! 🙌🏻

2022-11-14 06:20 UTC, daadaadaah requested changes
> 다른 분들의 코드를 보고 이해해보고 싶었으나... 이해가 잘 되지 않아서 문제예요!
혹시 비동기를 test 하기 위해서는 어떤 키워드를 알아야 되는지, 혹시 좋은 글이 있다면 공유해주시면 감사하겠습니다!!
- 다른 분들 코드 중에서 redux-mock-store도 있어서, 이해하기 어려울 수 있는데, 예전에 제가 한 [코드]( https://github.com/CodeSoom/react-week5-assignment-1/pull/9/files#diff-0c891c925105fe84e46525d7c883d3abee5142b2177b964bf1060126086c9a47
) 한번  보실래여? redux-mock-store 안쓰고 했거든요!

2022-11-14 06:20 UTC, daadaadaah commented on src/services/api.test.js
> +      }));
중복되는 코드를 어떤 걸 활용해서 묶어줄 수 있을까여?ㅎㅎ

2022-11-15 12:04 UTC, merged