week5-레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #124
Opened 2022-11-10 22:27 UTC by hyeji07

2022-11-11 06:12 UTC, daadaadaah requested changes
좋습니다! 나머지 진행하시고, PR 날려주세요~🚀

2022-11-11 06:12 UTC, daadaadaah commented on src/CategoriesContainer.test.jsx
> +      ],
fixture를 잘 만들어 놓으셨으니, 한번 활용해봅시다!ㅎㅎ(다른 테스트에서도 fixture를 활용해볼 수 있는 부분이 있는지도 한번 체크해보세요!)

2022-11-11 06:12 UTC, daadaadaah commented on src/reducer.test.js
> +    it('Categories가 변경된다', () => {
다른 테스트랑 통일감 있게 한글로 표현해보시는건 어떠신가여?ㅎㅎ

2022-11-11 06:12 UTC, daadaadaah commented on src/reducer.test.js
> +    it('지역이 변경된다', () => {
`지역 목록`이 변경된다고 하는게 좀더 적절하지 않을까 하는데, 어떻게 생각하시나여? (다른 테스트도 마찬가지로요!)

2022-11-12 09:59 UTC, hyeji07 commented on src/reducer.test.js
> +    it('지역이 변경된다', () => {
네넵 수정하였습니다!👍

2022-11-12 10:02 UTC, hyeji07 commented on src/reducer.test.js
> +    it('Categories가 변경된다', () => {
넵 한글로 수정하였습니다!

2022-11-12 12:01 UTC, daadaadaah commented
계속 진행해주세요~🚀

2022-11-13 01:44 UTC, hyeji07 commented
강의를 보면서 작성중인데 계속 에러가 납니다..ㅠㅠㅠ강의를 계속 돌려봐도 코드를 같게 작성한 것 같은데 에러가 나는 이유를 모르겠어요 ㅠ

2022-11-13 08:09 UTC, hyeji07 commented
action.js 에서 아래 사진과 같이 한 함수에 didispatch(setRegions(regions)); + dispatch(setCategories(categories)); 를 한꺼번에 불러온 경우, action.test.js 에서 test코드를 어떻게 작성해야하는 지 잘 모르겠습니다.ㅠ
다른 사람들의 코드를 살펴보아 redux-mock-store 를 설치하여 작성하였는데, 설치하지 않고 Test코드가 가능한가요...?
![image](https://user-images.githubusercontent.com/108104436/201512144-bddb9dc0-48d9-4931-a524-4fc5004220fd.png)

2022-11-14 06:07 UTC, daadaadaah requested changes
이번주는 완성하지 못하셨지만, 그래도 회고 남기신 점 너무 잘하셨어요! 👍 다음주도 같이 힘내봐요👊

> action.js 에서 아래 사진과 같이 한 함수에 didispatch(setRegions(regions)); + dispatch(setCategories(categories)); 를 한꺼번에 불러온 경우, action.test.js 에서 test코드를 어떻게 작성해야하는 지 잘 모르겠습니다.ㅠ
- 맞게 잘 작성해주셨어요!👏

> 다른 사람들의 코드를 살펴보아 redux-mock-store 를 설치하여 작성하였는데, 설치하지 않고 Test코드가 가능한가요...?
- redux-mock-store를 사용하지 않고도 가능합니다!ㅎㅎ

2022-11-15 12:04 UTC, merged