5주차 레스토랑 조회 구현하기 PR 요청합니다.
CodeSoom/react-week5-assignment-1 pull request #125
Opened 2023-01-02 21:54 UTC by Ubermensch0608

안녕하세요 트레이너님!

아직 완성하지 못 했지만 레스토랑 조회 구현하기 PR올립니다. 
단계적으로 앱을 만들어 보면서 커밋, TDD, redux 등 익숙해지고 싶어서 우선 커밋과 TDD에 집중해보았습니다.
기능적으로는 문제 없이 동작하고 App에서 모든 로직을 다루고 있습니다.  

이후에 redux를 이용한 상태관리 및 redux-thunk 적용할 계획입니다. 
감사합니다!

2023-01-03 13:47 UTC, daadaadaah requested changes
아직 완성하지 못했지만 먼저 PR 날리신 점 너무 잘하셨어요!👏
- TDD를 지금 연습하고 있는 단계이니 의도적으로 commit 메시지도 `XX 테스트 - XX 구현 코드 - XX (리팩토링)` 등의 형식으로 작성해보시는거 어떠세요? 또한, commit 작성하실 때, 작업단위를 좀더 작게 쪼개보는 연습을 하는게 좋을 것 같아요!
- 지금 작성해주신 https://github.com/CodeSoom/react-week5-assignment-1/pull/125/commits/c61de612b2658cda87661324121ccc8ffee625d6 을 보면, `RegionsContainer 테스트 코드 작성`이라고 되어 있는데, 테스트 코드 뿐만 아니라 `RegionsContainer` 구현 코드도 들어가 있고, 다른 코드들도 들어가 있어요!

2023-01-03 13:47 UTC, daadaadaah commented on src/Category.test.jsx
> +    it('액션이 실행된다.', () => {
it문 하나로 표현하면 테스트의 의미가 달라질까요?

2023-01-03 13:47 UTC, daadaadaah commented on src/Regions.test.jsx
> +    it('리스트는 렌더한다.', () => {
describe-context-it 문에 있는 문장을 하나의 문장으로 했을 때, 자연스럽게 작성하는 것이 좋습니다.
지금 작성해주신대로 한문장을 만들면, `Region은 지역 리스트가 있을 때 리스트는 렌더한다.`라는 문장이 만들어지는데, 어떤가요? 어색하다면 어떻게 표현하는게 좋을까요? (다른 테스트도 한번 살펴봐주세요!)

2023-01-03 13:47 UTC, daadaadaah commented on src/Regions.test.jsx
> +      ];
`regions`이라는 데이터는 다른 테스트에서도 사용되고 있어요. 이런 데이터들을 `fixture`라고 합니다. 이런 데이터들을 `fixtures`라는 폴더를 하나 만들어서 관리하면 어떨까요? (추가로 fixture로 관리할 수 있는 다른 데이터는 없는지 한번 살펴봅시다!)

2023-01-03 13:47 UTC, daadaadaah commented on src/CategoriesContainer.jsx
> +      };
이렇게 하시는 이유가 API에는 `checked`가 없어서 그러신가요?

2023-01-03 13:47 UTC, daadaadaah commented on src/App.jsx
> +  }, [regions, categories]);
이부분은 redux와 redux-thunk를 사용해서 좀더 간단한 코드로 바꿔봅시다!

2023-01-04 12:59 UTC, daadaadaah requested changes
계속 진행해주세요!
https://github.com/CodeSoom/react-week5-assignment-1/pull/125/files#r1060595357 이거 답변 부탁드려요!ㅎㅎ

2023-01-04 12:59 UTC, daadaadaah commented on src/fixtures/restaurants.js
> +const restaurants = [{ id: 1, name: '야미야미' }];
여러개라는 의도가 드러나게 2~3개 정도 데이터로 만드시는 걸 추천드립니다.

2023-01-04 12:59 UTC, daadaadaah commented on src/App.jsx
> +  // }, []);
나중에 주석 내용이 필요하더라도, PR 날리실 때는 정리해서 날리시는 걸 추천드려요!

2023-01-04 23:40 UTC, Ubermensch0608 commented on src/Category.test.jsx
> +    it('액션이 실행된다.', () => {
말씀해주신 점 고민해보고 describe 중첩이 필요 없다고 판단하여 수정했습니다!

2023-01-04 23:41 UTC, Ubermensch0608 commented on src/Regions.test.jsx
> +    it('리스트는 렌더한다.', () => {
다시 보니 완전한 문장으로 느껴지지 않아 전반적으로 설명문 수정해봣습니다 :)

2023-01-04 23:42 UTC, Ubermensch0608 commented on src/Regions.test.jsx
> +      ];
Fixture 폴더로 나누어 조금 더 깔끔하게 관리할 수 있게 해봤습니다.

2023-01-04 23:42 UTC, Ubermensch0608 commented on src/CategoriesContainer.jsx
> +      };
네 데이터를 프론트에서 사용하기 쉽게 하려고 가공한 것인데 혹시 이런 방식이 데이터 관리에 좋지 않을까요?

2023-01-04 23:43 UTC, Ubermensch0608 commented on src/App.jsx
> +  }, [regions, categories]);
네 아직 redux와 thunk이용은 자유롭게 하기 어렵지만 노력해보고있습니다!

2023-01-04 23:44 UTC, Ubermensch0608 commented on src/App.jsx
> +  // }, []);
넵 주석 같이 필요 없는 데이터는 최대한 정리 후 보내도록 하겠습니다!

2023-01-04 23:45 UTC, Ubermensch0608 commented on src/fixtures/restaurants.js
> +const restaurants = [{ id: 1, name: '야미야미' }];
넵 다른 과제에서도 그렇게 적용해보도록 하겠습니다~

2023-01-06 14:21 UTC, daadaadaah requested changes
조금씩 PR 날려주시는 모습 너무 좋습니다!👏
다음 PR 기다리고 있을게요~

2023-01-06 14:21 UTC, daadaadaah commented on src/RestaurantsContainer.test.jsx
> +  });
expect가 빠져있네요?ㅎㅎ

2023-01-06 14:21 UTC, daadaadaah commented on src/store/reducer.js
> +
앞에 과제들에서 if문이 많아졌을 때, 어떤걸 활용해서 코드를 간단히 했었나요?

2023-01-06 14:22 UTC, daadaadaah commented on src/CategoriesContainer.jsx
> +      };
아니요! 그냥 궁금해서 물어봤습니다. redux에서 관리하신 걸로 리팩토링 하신 것도 잘하셨어요!👍

2023-05-30 15:11 UTC, merged