레스토랑 조회 구현하기 - 예비
CodeSoom/react-week5-assignment-1 pull request #13
Opened 2020-07-02 17:31 UTC by kwonmory

흠.. 동작은 하는데.. 연습 없이 바로 해서 그런지 완전 똥망같네욬ㅋㅋㅋㅋㅋㅋㅋ;;

테스트에 신경을 못써서 커버리지가 아주... 심각한데.. 늦은 시간이 되어서 이만하고 검토 받고 다시해봐야겠네요..;;

2020-07-02 17:32 UTC, kwonmory commented
리팩토링도 명시하고 한게 없는거 같네요;;

2020-07-03 00:51 UTC, hannut91 requested changes
전체적으로 TDD도 잘해주셨고 코드 구현도 잘해주셨습니다. 아쉬운 점은 DOM을 직접 다루려는 행위와 테스트에서 중복이 많이 발생했다는 점이에요. 이 부분만 개선하면 좋을 것 같습니다.

2020-07-03 00:51 UTC, hannut91 commented on src/App.jsx
> +      && restaurants.length > 0
`restaurants`의 길이가 0일 경우 `map`함수는 동작하지 않으므로 이 것은 확인안하셔도 돼요. 우리가 0에 무엇을 곱해도 0인 것 처럼 빈 배열에는 map이나 filter, reduce등 아무 일도 일어나지 않습니다.

2020-07-03 00:51 UTC, hannut91 commented on src/RestaurantCategories.jsx
> +          </button>
`data-name`과 `data-id`를 사용하는 것보다 onClick에서 값들을 넘겨주는게 좋을 것 같아요

여기서 어떻게 하고 있는지 보시면 좋을 것 같습니다

See also
  - https://reactjs.org/docs/forms.html#handling-multiple-inputs

2020-07-03 00:51 UTC, hannut91 commented on src/RestaurantCategories.test.jsx
> +      ];
중복되어 사용되는 테스트용 데이터들은 `fixture`로 분리하면 좋을 것 같아요

2020-07-03 00:51 UTC, hannut91 commented on src/RestaurantCategories.test.jsx
> +      );
테스트에서 반복적으로 사용되고 있는데 중복되는 것들을 함수로 분리하면 좋을 것 같아요.

```js
const handleClick = jest.fn();

const renderRestaurantCategories = (categories, selected) => {
  return (
    <RestaurantCategories
      categories={categories}
      onClick={handleClick}
      selected="한식"
    />
  );
}

beforeEach(() => {
  handleClick.mockClear();
});
```

2020-07-03 00:51 UTC, hannut91 commented on src/RestaurantCategoriesContainer.jsx
> +  } = useSelector((selector) => ({
`selector`가 아니라 `state`가 더 적절할 것 같아요

2020-07-03 00:51 UTC, hannut91 commented on src/reducer.js
> +export default function reducer(state = inistialState, action) {
`if`나 `switch`없이 이 문제를 해결할 수 있을까요?

2020-07-03 00:51 UTC, hannut91 commented on src/reducer.test.js
> +      expect(state.restaurants).toHaveLength(2);
`expect(state.restaurants).toEqual(restaurants);`라고 하면 의도가 더 드러날 것 같아요

2020-07-05 08:17 UTC, kwonmory commented on src/RestaurantCategories.test.jsx
> +      );
오 이것도 해보겠습니다. mockClear() 처음 봤네요.. 다양한게 있네요.

2020-07-05 08:19 UTC, kwonmory commented on src/reducer.js
> +export default function reducer(state = inistialState, action) {
앗.. 이거 과제 풀이에서 해결하는 방법 봤습니당.. 배운건 적용해봐야곘죵~ ㅋㅋㅋ

2020-07-05 14:14 UTC, hannut91 approved these changes
고생하셨습니다. 다음 과제에서는 테스트에 필요한 데이터들을 fixture로 분리하여 테스트를 더 간결하게 하면 좋을 것 같아요. 그리고 테스트에 필요한 데이터를 준비하는 것과 실제 테스트를 분리하여 가독성을 높이면 좋을 것 같아요

2020-07-05 14:14 UTC, hannut91 commented on src/App.jsx
> +  const { restaurants } = useSelector((state) => ({
레스토랑 상태를 앱 컴포넌트가 관리하고 있네요. 이것도 레스토랑 컨테이너가 관리하도록 관심사의 분리를 하면 좋을 것 같아요

2020-07-05 14:14 UTC, hannut91 commented on src/RestaurantCategories.test.jsx
> +    it('change category', () => {
테스트에 명시되어 있는 것처럼 실제 테스트에는 카테고리를 변경하고 있지 않은 것 같아요

2020-07-05 14:14 UTC, hannut91 commented on src/RestaurantCategoriesContainer.jsx
> +    dispatch(changeCategory(categories.find((v) => v.name === event.target.name)));
클릭 이벤트 객체를 돌려주는 대신에 바로 카테고리를 넘겨주면 굳이 카테고리 목록에서 찾지 않아도 될 것 같아요

2020-07-05 14:14 UTC, hannut91 commented on src/RestaurantCategoriesContainer.test.jsx
> +      }));
테스트를 하기 위해 필요한 작업들이 실제 테스트 대상이 들어갈 공간에 같이 위치해서 테스트를 이해하는데 어려운 것 같아요. it밖으로 분리하면 테스트가 실행되기 위한 필요조건(Given) 과 실제 실행되는(When)과 기대하는 (Then)이 명확하게 보일거에요

2020-07-05 14:14 UTC, hannut91 commented on src/reducer.test.js
> +        {
태스트에 필요한 데이터들을 fixture로 분리하면 좋을 것 같아요

2020-07-05 14:15 UTC, hannut91 commented
이번 과제를 통해서 무엇을 배우셨나요? 다음 과제에서 더 신경써서 개발하고 싶은게 있으신가요?

2020-07-07 11:40 UTC, merged