과제 5 - 1차 PR
CodeSoom/react-week5-assignment-1 pull request #14
Opened 2020-07-03 10:13 UTC by min-w-park

안녕하세요, 

구조적으로 문제가 있을 경우 다시 다 지우고 돌아가는거에 주저하다보니
어느 순간 리팩토링하는데 테스트가 먼저 작성되지 않기도 하네요. 
코드의 재작성을 두려워하지 않아야겠습니다..

region을 선택하는데 있어서 접근을 처음부터 잘못했네요.

일단 1차 PR 합니다. 계속 작업 해서 올릴게요.

2020-07-03 13:45 UTC, wholemann requested changes
계속 진행해주시면 될 것 같아요ㅎㅎ

일단 TDD 규칙을 잘 지켜서 굉장히 작게 테스트를 추가하고 작게 구현하고를 잘 반복 하셨습니다.

그리고 테스트에서 잘못된 부분을 리팩토링으로 고친 걸 보아 깨달음을 얻으셨군요.

질문은 언제든 DM 주세요ㅎㅎ

2020-07-03 13:45 UTC, wholemann commented on src/App.test.jsx
> +  it('should display regions', () => {
it('renders regions', ...)

요즘은 should를 잘 안 쓰는 추세에요.

2020-07-03 13:45 UTC, wholemann commented on src/reducer.test.js
> +      expect(state.regions).not.toHaveLength(0);
```suggestion
      expect(state.regions).toHaveLength(1);
```

여긴 명시적으로 길이 1을 해줘도 좋을 것 같네요.

2020-07-03 13:45 UTC, wholemann commented on src/Regions.test.jsx
>  describe('App', () => {
이곳은 App에 대한 테스트는 아니죵ㅎㅎ

2020-07-03 13:45 UTC, wholemann commented on src/Regions.test.jsx
> -    expect(container).toHaveTextContent('서울(V)');
잘하셨네요. 이건 컴포넌트의 관심사는 아닙니다. 체크 여부는 리덕스에서 관리할 상태죠.

2020-07-06 14:39 UTC, wholemann requested changes
피드백 사항에 대해 반영이 안 된 부분들이 조금 아쉬움으로 남습니다.

일단은 올라온 피드백 영상을 바탕으로 Test를 모두 통과시키신 뒤 PR주시면

다시 한번 보도록 할게요:)

2020-07-06 14:39 UTC, wholemann commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn((selector) => selector({}));
```suggestion
export const useSelector = jest.fn();
```

2020-07-07 16:18 UTC, min-w-park commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn((selector) => selector({}));
피드백 감사드려요.! 
사실 API 테스트를 잘 모르겠어서 남겨뒀었습니다.. 

여전히 각 컴포넌트의 관심사의 범위가 정확히 어디까지인가의 경계를 명확히 구분 테스트 하는게 어렵네요.
관련해서 어떤식으로 생각 하는게 도움이 될까요? 

지난주는 몸이 좀 안좋아서 사실 열심히 못했네요..! 
트레이너님도 몸 관리 잘 하시길 바랍니다..!

2020-07-07 23:49 UTC, wholemann commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn((selector) => selector({}));
항상 '이건 누구의 책임인가?'를 고민하는 게 좋습니다.

그건 테스트 코드로 먼저 의도를 표현해보는 게 좋아요.

'이걸 과연 얘가 처리하는 게 맞을까?' 란 생각이 들죠.

일단 테스트 코드 작성이 고통스럽다면 뭔가 잘못되고 있음을 의심해봐야 합니다.

2020-09-12 06:36 UTC, merged