Async
CodeSoom/react-week5-assignment-1 pull request #15
Opened 2020-07-03 16:23 UTC by kc7851

아직 갈길이 머네요... ㅜㅜ

2020-07-04 03:57 UTC, hannut91 requested changes
좋네요 ㅎㅎㅎ TDD하실 때 리팩터링을 빠트리지 마시고 꼭하세요 ㅎㅎ

2020-07-04 03:57 UTC, hannut91 commented on src/App.test.jsx
> +    categories: [
테스트용 데이터를 fixture라고 부르는데 따로 파일로 분리하면 좋을 것 같아요

2020-07-04 03:57 UTC, hannut91 commented on src/App.test.jsx
> +    selected: {},
selected는 true 혹은 false만 담고 있을 것 같아요. 선택된 카테고리 혹은 선택된 지역을 표시하고 싶으셨던 거죠

2020-07-04 03:57 UTC, hannut91 commented on src/App.test.jsx
> +    expect(getByText(/서울/)).not.toBeNull();
regions를 이용해서 표현하면 어떨까요?

2020-07-04 03:57 UTC, hannut91 commented on src/App.test.jsx
> +    expect(getByText(/한식/)).not.toBeNull();
여기도 categories를 이용해서 표현해주는건 어떨까요?

2020-07-04 03:57 UTC, hannut91 commented on src/CategoriesContainer.test.jsx
> +  const dispatch = jest.fn();
dispatch가 테스트 여러곳에서 쓰일경우 초기화하지 않으면 문제가 발생할 수 있어요 

```js
beforeEach(() => {
  dispatch.mockClear
});
```

2020-07-05 02:10 UTC, hannut91 requested changes

2020-07-05 02:10 UTC, hannut91 commented on src/App.test.jsx
> +  });
App 컴포넌트에서 액션 테스트하는 것은 따로 분리하는게 좋을 것 같아요.

2020-07-05 02:10 UTC, hannut91 commented on src/Categories.jsx
> +export default function Categories({ selected, categories, onClick }) {
`selected`는 true, false만 가질 것 처럼 보여요. selectedCategoryId는 어떨까요?

2020-07-05 02:10 UTC, hannut91 commented on src/Categories.test.jsx
> +    it('(V)가 표시되지 않는다..', () => {
`..` 점이 2개 들어가 있네요

2020-07-05 02:10 UTC, hannut91 commented on src/CategoriesContainer.test.jsx
> +      expect(getByText(/분식/)).not.toBeNull();
여기도 `fixture`를 사용하면 간단하게 표현이 가능하겠죠?

2020-07-05 02:10 UTC, hannut91 commented on src/RegionsContainer.test.jsx
> +      });
`regExp`라는 변수이름이 코드를 이해하는데 도움이 되지 않는 것 같아요. 우변이 이미 충분히 설명하고 있죠. 그리고 이름만 사용한다면 디스트럭처링을 바로 해도 괜찮을 것 같아요.

```js
regions.forEach(({ name }) => {
  expect(getByText(RegExp(name)).toBeInTheDocument();
});
```

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.7-rename-variable

2020-07-05 02:10 UTC, hannut91 commented on src/reducer.js
> +export default function reducer(state = initialState, action) {
`if`나 `switch` 없이 이 문제를 해결할 수 있을까요?

2020-07-05 06:21 UTC, kc7851 commented on src/App.test.jsx
> +  });
actions.test.js 로 분리하면 되겠죠??

2020-07-05 06:22 UTC, kc7851 commented on src/Categories.jsx
> +export default function Categories({ selected, categories, onClick }) {
selectedCategoryId 이게 좀 더 명확해 보이네요

2020-07-05 06:22 UTC, kc7851 commented on src/RegionsContainer.test.jsx
> +      });
오 아주 좋네요!

2020-07-05 06:22 UTC, hannut91 commented on src/App.test.jsx
> +  });
넵

2020-07-05 06:24 UTC, kc7851 commented on src/reducer.js
> +export default function reducer(state = initialState, action) {
객체로 만들어서 분리하네요. ㅎㅎ 이거.. 어디서 본거같아서 예전에 10주 프로젝트할때 했던 리액트 네이티브코드 찾아보니 그렇게 했었네요. 아샬님 frontEnd TDD repo에 있는거 보고서. 그리고 redex-thunk도 사용하고 비동기 액션도 사용했던데, 아예 기억이 안났었네요 ㅜㅜ

2020-07-05 08:21 UTC, kc7851 commented
utils에 get이나 equal에 object를 넘겨주지 않았는데, return에서 어떻게 obj를 사용할 수 있나요?

useSelector((state)) => state.regions)에서
useSelector(get('regions')) 이렇게 바뀐건데... 함수의 인자로 넘어오는 객체가 자동으로 들어가는건가요?

2020-07-05 13:38 UTC, hannut91 approved these changes
고생하셨습니다! TDD를 하실 때 리팩터링을 꼭 같이 하면 좋을 것 같습니다. 구현에 대한 것은 막힘없이 잘 하셔서 코드의 표현력만 더 신경쓰시면 좋을 것 같아요

2020-07-05 13:38 UTC, hannut91 commented on src/actions.test.js
> +    it('regions를 fetch 한다.', async () => {
regions룰 fetch하는지에 대해서 테스트에서 하나도 드러나지 않는 것 같아요. setRegions액션이 실행된다로 이름을 변경하던지 아니면 실제로 fetch하는지 테스트를 변경하던지 하면 좋을 것 같아요

2020-07-05 13:38 UTC, hannut91 commented on src/actions.test.js
> +    const withoutCategoryIdStore = mockStore({
카테고리 아이디 없이 실행한다는 것은 우변 코드에서 이메 충분히 설명하고 있는 것 같아요. 간단하게 store라고만 해줘도 될 것 같아요.

2020-07-05 13:38 UTC, hannut91 commented on src/actions.test.js
> +    const withoutCategoryIdStore = mockStore({
그리고 여기 위치가 이상하네요 컨텍스트 안에 들어가야 할 것 같아요

2020-07-05 13:38 UTC, hannut91 commented on src/actions.test.js
> +    const withSelectedStore = mockStore({
얘도 컨텍스트안에 들어가야 할 것 같아요

2020-07-05 13:39 UTC, hannut91 commented
이번 과제를 진행하면서 무엇을 배우셨나요? 다음 과제에서 더 신경써서 하고 싶으신게 있나요?

2020-07-05 14:46 UTC, kc7851 commented
5주차 비동기 회고

# 배운 점
1. Promise와 async-await의 사용법을 배웠습니다. 
2. 비동기 액션을 사용하는 방법을 배웠습니다.
3. api를 이용하여 data를 가져오는 방법을 배웠습니다.
4. 리뷰를 통해 fixtures 사용을 배웠습니다.
5. mocking하여 test하는 방법을 배웠습니다. (api, react-redux, thunk)

# 느낀 점
1. 처음 생각한것보다 훨씬 더 많은 시간이 들었습니다. 역시 첫 시작이 가장 어렵습니다.
2. mocking하여 test하는 방법을 몰라서 어려운 부분이 많았습니다.
3. api를 직접 사용해서 코드를 작성하니 웹 애플리케이션 느낌이 나서 좋았습니다.
4. 최대한 복붙을 안하려고 하는편인데, 1달 동안 조금은 익숙해진 느낌이 들어서 좋았습니다.

# 아쉬운 점
1. tdd 사이클에서 리팩토링을 계속 건너띈 점. 
2. 클로저 함수에 대한 이해가 낮은 점.
3. 백지에서 코드를 작성할 때 어떤걸 import 해야하는지 막히는 부분이 있습니다.

# 앞으로
1. 틈 날때 마다 뒤 돌아보면서 코드를 점검하는 습관을 길러야 겠습니다.
2. 클로저 함수에 대해 공부를 해야겠습니다.
3. 익숙하지 않은 라이브러리를 익숙하게 만들어야 겠습니다.

2020-07-05 14:47 UTC, kc7851 commented
어랏..ㅋㅋ 이거 마크다운 지원하는군요 ㅋㅋ 모르고 그냥 작성했는데...

2020-07-05 14:56 UTC, hannut91 commented
앞으로가 기대되는군요! 클로저 함수는 어어어어엄청 많이 쓰이므로 공부하시면 좋습니다 ㅎㅎ

2020-07-05 14:56 UTC, merged