과제 5-1
CodeSoom/react-week5-assignment-1 pull request #2
Opened 2020-06-30 10:03 UTC by aumilkyeong

앱 구성요소가 지역, 카테고리, 조회결과 세가지로 나눠진다고 판단했습니다.
현재 지역 컨테이너 작업 중이며 테스트/컴포넌트 만들어서 하나씩 진행중입니다.

2020-06-30 13:23 UTC, wholemann requested changes
최근에 과제 제출을 못 하셔서 우려가 됐습니다만

나름 잘 따라오신 걸 느꼈네요.

몇 가지 아쉬운 부분 comment 남겨드렸습니다.

TDD에서 핵심은 사용하는 측에서 사용법을 먼저 결정하고
그에 맞춰 실제 로직을 구현하는 겁니다.

또한 지금은 RegionsContainer에 대한 사용법과 구현을 확정한 뒤 이를 사용하는 App 테스트도 맞춰가야 하는데
앞서간 느낌이 있습니다. 이는 미래의 구현을 예측 했을 때 벌어지는 전형적인 현상인데요. 지금은 앱이 간단하고 익숙한 Todo의 응용이라 문제가 없지만 요구사항이 조금만 복잡해져도 TDD에 큰 어려움을 느끼게 됩니다.

어떤 상황에서도 TDD의 규칙을 지키려고 하는 게 중요합니다.

다음 세 가지 규칙을 지켜보길 권합니다:)

1. 실패한 단위 테스트를 만들기 전에는 제품 코드를 만들지 않는다.
2. 컴파일이 안 되거나 실패한 단위 테스트가 있으면 더 이상의 단위 테스트를 만들지 않는다.
3. 실패한 단위 테스트를 통과하는 이상의 제품 코드는 만들지 않는다.

2020-06-30 13:23 UTC, wholemann commented on src/App.test.jsx
> +    expect(dispatch).toBeCalledTimes(1);
지금은 App에선 dispatch 호출 여부를 체크하는 것으로 충분합니다.

dispatch에 의한 상태 변화는 reducer 테스트를 믿는 거죠:)

2020-06-30 13:23 UTC, wholemann commented on src/App.test.jsx
> +    });
이 부분은 앞서간 느낌입니다. 결국 뒤의 commit에서 이 부분은 제거됐죠.

이미 RegionsContainer를 만들었기 때문에 RegionsContainer 테스트를 먼저 작성하고

구현을 확실히 한 뒤 RegionsContainer를 사용하는 App의 테스트를 수정하면

이런 오류를 방지할 수 있습니다👍

2020-06-30 13:23 UTC, wholemann commented on src/actions.js
> +    const regions = await fetchRegions();
액션은 보통 테스트 코드를 작성하고 진행하는 TDD로 진행하진 않지만

api.js의 fetchRegions가 먼저 구현되기 보단

loadRegions 안에서 fetchRegions란 비동기 함수 사용이 확정되면
그 다음 fetchRegions의 실제 구현을 하는 게 좋습니다.

TDD의 핵심 아이디어는 해당 API(또는 함수)를 사용하는 측(클라이언트)에서 사용 방식을 먼저 결정하고
그 다음 실제 로직을 구현하는 겁니다. 보통 TDD로 구현한다면 최초의 클라이언트는 테스트 코드가 되겠죠.

하지만 이런 아이디어는 테스트 코드가 없어도 실천 가능합니다:)

2020-06-30 13:23 UTC, wholemann commented on src/reducer.js
>  export default function reducer(state = initialState, action) {
실제 구현보단 reducer 테스트 코드가 먼저 작성됐어야 합니다.

2020-06-30 13:23 UTC, wholemann commented on src/App.test.jsx
>  jest.mock('react-redux');
```suggestion
jest.mock('react-redux');
jest.mock('./services/api');
```

실제 프로젝트 구조상 __mocks__가 src/services 보단 상위 계층이기 때문에

순서를 바꾸는 게 좋겠습니다.

2020-07-02 06:16 UTC, aumilkyeong commented on src/App.test.jsx
>  jest.mock('react-redux');
done

2020-07-02 12:24 UTC, wholemann commented on src/reducer.test.js
> +        expect(state.regions).not.toHaveLength(0);
```suggestion
        expect(state.regions).toHaveLength(1);
```

전달한 상태의 배열 내부 요소가 1개이기 때문에 명확히 표현해주는 게 좋겠습니다.

2020-07-02 12:26 UTC, wholemann commented on src/reducer.test.js
> +  context('without action matched', () => {
이 부분 하나 때문에 맥락이 갈린다고 하기엔 앞선 context에 속한 테스트가 너무 비대한 느낌이네요.

지금 상황에선 context 2개가 없어도 무방할 듯 합니다.

2020-07-02 12:28 UTC, wholemann commented on src/RegionsContainer.jsx
> +  }));
```suggestion
  const regions = useSelector((state) => state.regions);
```

단일 상태를 가져올 땐 이렇게 해도 무방합니다.

2020-07-02 12:39 UTC, wholemann commented on src/RegionsContainer.jsx
> +    <Regions regions={regions} />
Container는 보통 List를 담고 있는데

지금은 좀 먼저 분리된 느낌이네요.

그리고 Regions에서 또 Region으로 분리됐는데 약간 과도한 추상화가 아닌가 생각됩니다.

JSX가 가지는 장점인 코드에서 UI 구성을 직관적으로 알아보기 힘든 수준이 됐을 때나
상태를 이용한 복잡한 처리가 있을 때 컴포넌트 분리를 해도 늦지 않습니다.

개인적으론 지금은 Container에서 ul과 button으로만 표현해도 충분한 수준인 듯 합니다.
아니면 Region 배열을 ul로 감싸서 생성하는 정도면 되겠네요.

저는 보통 그럴 때 Region 컴포넌트를 별도의 파일로 분리하진 않고 RegionsContainer.jsx에서 RegionsContainer 컴포넌트 위에
선언합니다. 그러다가 복잡해지면 분리하는 수순이죠.

2020-07-02 12:41 UTC, wholemann requested changes
몇 가지 참고하실 comment 남겨뒀습니다.

컴포넌트 분리는 보통 경험적인 기준이 꽤 작용합니다만

기본적으로 미리 분리하는 건 좀 지양할 필요가 있습니다ㅎㅎ

공수만 늘어나는 경우가 많거든요. 눈으로 봐도 너무 명확하고 간단한 건 굳이 미리 분리할 필요는 없어요ㅎㅎ

참고하시고 진행하시면 좋겠습니다.

질문은 언제든 DM으로 주세요!

2020-07-05 15:38 UTC, wholemann requested changes
일단 테스트를 모두 통과하는 상태로 만들어 보시면 좋겠습니다ㅎㅎ

그리고 몇 가지 아쉬운 부분에 대해 comment 남겼습니다.

각 테스트의 관심사에 대해서 고민해보시면 좋은 공부가 될 겁니다.

질문은 언제든 DM 주세요ㅎㅎ

2020-07-05 15:38 UTC, wholemann commented on src/CategoriesContainer.test.jsx
> +    expect(container).toHaveTextContent('한식(V)');
이건 컴포넌트의 관심사가 아닙니다.

CategoriesContainer는 그저 selectedCategory 상태를 redux가 쏴주면 그에 맞게 render를 해줄 뿐이죠.

컴포넌트 테스트는 click을 했더니 dispatch가 호출됐다(action이 발생했다) 까지만 관심사입니다.

이걸 테스트 하는 순간 상태 관리를 분리한 의미가 없어집니다.

2020-07-05 15:38 UTC, wholemann commented on __mocks__/react-redux.js
> +export const useSelector = jest.fn((selector) => selector({}));
```suggestion
export const useSelector = jest.fn();
```

2020-07-05 15:38 UTC, wholemann commented on src/App.jsx
> +import CategoriesContainer from './CategoriesContainer';
```suggestion
import RegionsContainer from './RegionsContainer';
import CategoriesContainer from './CategoriesContainer';

import {
  loadRegions,
  loadCategories,
} from './actions';
```

2020-07-05 15:38 UTC, wholemann commented on src/CategoriesContainer.test.jsx
> +  it('contains category names', () => {
```suggestion
  it('renders list of category', () => {
```

는 어떨까요?

2020-07-05 15:38 UTC, wholemann commented on src/CategoriesContainer.test.jsx
> +  it('selects a category and update display', () => {
```suggestion
  it('listens click event', () => {
```

요정도면 의도에 충실할 것 같네요.

2020-09-12 06:36 UTC, merged