[5주차] 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #22
Opened 2020-10-19 11:13 UTC by oceanide2

- 초기 구현 시작

2020-10-20 16:05 UTC, Kihyun92 requested changes
좋습니다~ `Red-Green-Refactoring` 사이클을 잘 지키면서 해주고 계신듯하네요 👍

2020-10-20 16:05 UTC, Kihyun92 commented on src/Regions.jsx
> +        <li key={id}><button type="button">{name}</button></li>
줄바꿈 처리를 해주면 더 읽기 좋겠네요 :)

2020-10-20 16:05 UTC, Kihyun92 commented on src/Regions.test.jsx
> +  const { getByText } = render(<Regions regions={regions} />);
```suggestion
  const { getByText } = render((
    <Regions regions={regions} />
  ));
```

이 부분도 코드는 짧지만, 줄바꿈이 들어가주면 읽기 좋을 것 같아요~

2020-10-20 16:05 UTC, Kihyun92 commented on src/reducer.js
> +
물론 잘 해주시겠지만, 이번 과제도 가능하면 `if` 문을 사용하지 않고 처리해보면 좋을 것 같아요~

2020-10-20 17:07 UTC, oceanide2 commented
아래 코드와 같이 fetchRegions()를 추가한 다음에, App.test.jsx에서 ```expect(dispatch).toBeCalled()```가 호출이 안된다고 에러가 납니다. 에러가 왜 발생하는지를 잘 모르겠습니다. 도움을 좀 부탁 드리겠습니다.
```
async function loadRegions({ dispatch }) {
  const regions = await fetchRegions();

  dispatch(setRegions(regions));
}
```

2020-10-21 13:37 UTC, oceanide2 commented
아래 내용은 슬랙에서 문의드렸었고, 일단 해당  테스트에 대해서는 나중으로 미루고 진행하겠습니다. 

> 아래 코드와 같이 fetchRegions()를 추가한 다음에, App.test.jsx에서 `expect(dispatch).toBeCalled()`가 호출이 안된다고 에러가 납니다. 에러가 왜 발생하는지를 잘 모르겠습니다. 도움을 좀 부탁 드리겠습니다.
> 
> ```
> async function loadRegions({ dispatch }) {
>   const regions = await fetchRegions();
> 
>   dispatch(setRegions(regions));
> }
> ```

2020-10-22 00:13 UTC, oceanide2 commented
- 지역과 카테고리를 API에서 불러와서 화면에 표시하는 것까지 코드를 작성하였습니다.
- 금주 강의 내용을 참고하여 Red-Green-refactoring 과정을 최대한 맞추어 보려고 하고 있지만 과정이 뒤죽박죽 섞이는 느낌입니다. 전체 기본 구조를 완성하기 전까지 각 컴포넌트마다 테스트 코드를 최소로 작성하고 기본 구조를 완성한 후에 테스트 코드를 추가하는 방향으로 해보고 있습니다.
이렇게 진행하다가 보니 TDD과정에 맞추어 테스트 코드를 먼저 작성하는 느낌이 아닌 그냥 코드를 먼저 작성하고 있는 듯한 느낌도 있습니다.
- TDD 과정이라는 것이 금방 익숙해지지는 않겠지만 최소한 어디서 부터 시작할지에 대한 방향과 전략이 필요할 것 같은데 여기서부터 해매고 있다는 생각이 듭니다.

2020-10-22 04:03 UTC, Kihyun92 commented
잘 하고 계십니다~👍 구현하려는 기능을 생각해보고, 그에 따른 최소 테스트코드를 작성하고, 실제 구현하고, 다시 테스트코드 추가(리펙토링)하는 과정이 뒤죽박죽 섞이는 느낌이 드실 수도 있지만, `Red-Green-Refactoring`의 사이클을 최소한으로 가져감으로써 지속적으로 개선하는데 집중해보시면 좋을 것 같아요~ 테스트 코드를 추가하는 것도 일종의 Refactoring 단계인거니까요. 

어떻게 시작하는게 좋을지가 고민되시면 아샬님의 강의 영상에서 어떻게 시작하시는지를 집중해서 봐보셔도 좋을 것 같아요 :)

그리고 에러 내용은 제가 확인이 늦었네요 😭 혹시 도움이 필요하시면 또 말씀주세요!

2020-10-22 06:57 UTC, Kihyun92 requested changes
좋네요 👍  다음 기능들도 차근차근 진행해보시면 좋을 것 같아요~
문의주시면 최대한 빠르게 대응하겠습니다 🙇🏻

2020-10-22 06:57 UTC, Kihyun92 commented on src/App.test.jsx
> +  });
지금 같은 상황에서는 context로 분리하는게 아니라 `describe`로 분리하는게 나을 것 같아요~ 그리고 공통 코드는 상위로 올릴 수 있을 것 같구요.

`context`는 주로 `with <-> without`

when log in <-> when log out

처럼 같은 맥락에서 별개의 사례일 때 context를 사용합니다.
혹은 it 만으로는 설명이 너무 길어지는 경우에 사용하기도 합니다.

context 사용법은 아래 문서와 아샬님의 문서를 참고해주세요~
- https://www.betterspecs.org/
- https://github.com/ahastudio/til/blob/main/blog/2018/12-08-given-when-then.md

2020-10-22 06:57 UTC, Kihyun92 commented on src/CategoriesContainer.test.jsx
> +test('<CategoriesContainer', () => {
'<' 는 제거해도 될것같네요~

2020-10-22 06:57 UTC, Kihyun92 commented on src/reducer.js
> +    const { regions } = action.payload;
```suggestion
  setRegions(state, { payload: { regions } }) {
```
좀 더 심플하게 쓸 수도 있을 것 같아요~

2020-10-22 06:57 UTC, Kihyun92 commented on src/reducer.test.js
> +  context('setRegions', () => {
이 부분도 `describe`로 해도 될 것 같아요~

2020-10-23 08:45 UTC, oceanide2 commented
- RegionsContainer와 CategoriesContainer 컴포넌트를 클릭하면 체크표시와 RestaurantsContainer를 테스트 데이터로 화면에 표시하는 것까지 진행하였습니다.
- services/api와 actions.js에 포함된 async/await 함수 등은 테스트 코드를 어떻게 작성해야할지를 잘 모르겠습니다. 참고할 만한 것이 있다면 알려주시면 감사하겠습니다.

2020-10-23 17:14 UTC, Kihyun92 requested changes
답변이 늦어 죄송합니다,,😭 
`Red-Green-Refactoring` 사이클을 잘 가져가고 계신 것 같아요. 좋습니다 👍  
남은 `레스토랑 목록 보기` API 연동도 금방 하실 수 있을 것 같아요 :) 
질문주신 API에 대한 테스트의 경우에는 jest에 `mock-function`에 대한 문서를 참고해보시면 좋을 것 같아요~
- https://jestjs.io/docs/en/mock-functions#mocking-modules

혹시 진행하시다가 막히는 부분 있다면 말씀주세요!

2020-10-23 17:14 UTC, Kihyun92 commented on src/Regions.test.jsx
> +    it('renders button text', () => {
`renders button text`는 조금 명확하지 않은 것 같아요~ `renders regions name`과 같이 현재 테스트하는 것에 대해 조금 더 명확히 해주는 건 어떨까요?

2020-10-23 17:14 UTC, Kihyun92 commented on src/Regions.test.jsx
> +    it('called onClick', () => {
`called onClick`도 좋지만, `onClick`만 봐서는 어떤 기능을 하는 버튼인지 의도가 전달되지 않을 수 있을 것 같아요. 버튼을 클릭함으로써 어떤 결과가 발생하는지를 표현해보는 건 어떨까요? `handleClickRegion`을 실행한다도 좋고, `dispatch`가 발생한다는 어떤가요?

2020-10-25 03:11 UTC, oceanide2 commented
- 레스토랑 목록조회까지는 만들었지만 fetch가 포함된 api 테스트는 구현하지 못했습니다. 말씀해주신 자료는 읽어보았지만 조금 더 공부를 해야할 것 같습니다. 그래서 api 테스트 관련부분은 TDD 절차를 따르지는 못했고 그냥 코드만 작성되었습니다.

2020-10-25 07:09 UTC, Kihyun92 approved these changes
고생하셨습니다! 쉽지 않은 과제였는데, `Red-Green-Refactoring` 사이클도 잘 적용하시고, Redux와 API 연동 부분을 잘 수행해주셨어요.

이번 과제를 통해 어떤걸 배우셨는지, 그리고 더 해보고 싶은 부분이 있는지 고민해보시면 좋을 것 같아요~ 😁
과제 풀이 영상 꼭 봐보시고, 몇가지만 수정해주시면 될 것 같네요~

2020-10-25 07:09 UTC, Kihyun92 commented on src/actions.js
> +    if (selectedRegion.length === 0 || selectedCategory.length === 0) {
`if (!selectedRegion || !selectedCategory) {` 이렇게 처리해줘도 괜찮을 것 같네요~

2020-10-25 07:09 UTC, Kihyun92 commented on src/App.jsx
> +    <div>
div 태그로 감싸기 보다 fragment를 사용해주면 좋을 것 같아요~
- https://ko.reactjs.org/docs/fragments.html#short-syntax

2020-10-26 00:29 UTC, oceanide2 commented on src/actions.js
> +    if (selectedRegion.length === 0 || selectedCategory.length === 0) {
selectedRegion과 selectedCategroy의 초기 데이터 타입을 array로 해놓아서 ! 연산자로는 동작하지 않는 것 같습니다. 제가 찾아보기로는 빈 배열, 빈 객체, 빈 함수에 !를 붙이면 flasey가 아니라 truthy로 처리되는 걸로 보여서 초기 데이터 타입을 []에서 ''로 변경하고 ! 연산자를 적용하였습니다. 헷갈리는 사항을 지적해주셔서 감사합니다 :)

2020-10-26 00:29 UTC, oceanide2 commented on src/App.jsx
> +    <div>
말씀하신대로 수정하였습니다. :)

2020-10-26 14:04 UTC, merged