Restaurant Lookup - 개발중
CodeSoom/react-week5-assignment-1 pull request #23
Opened 2020-10-19 12:58 UTC by gringrape

2020-10-19 14:02 UTC, gringrape commented
## 작업 내용
레스토랑 지역 목록 보기 기능에서 서버 데이터를 이용하기 전 부분까지 구현하였습니다.
## 작업 후기
TDD 로 개발하는 틀을 익히기 위해서 지난주 아샬님 피드백 영상을 외운 후에 진행했습니다.
아직 Red-Green-Refactoring 순서로 아귀가 잘 맞아떨어지는 것 같지는 않아서 좀 더 반복해야할 것 같습니다.

2020-10-19 14:49 UTC, hannut91 requested changes

2020-10-19 14:49 UTC, hannut91 commented on src/Regions.jsx
> +      ))}
스터디때 배운 구조 분해 할당으로 중복되는 `region`을 없앨 수 있을까요?

2020-10-20 12:58 UTC, gringrape commented
## 작업내용
지역 목록을 서버에서 가져오는 부분을 구현하였습니다.
## 주안점
TDD 사이클을 커밋으로 대응시키는데 집중했습니다.
Red 부분이 꼭 테스트를 더 만드는것만은 아니고, 현재는 없지만 구현하기 원하는 것(목표)을
써놓는 상태라고 생각했는데, 피드백 주시면 감사하겠습니다.
## 작업후기
강의를 외우고, 혼자 해보고, 다시 한번 해보면서 제출하다 보니 너무 똑같아 지는것 같습니다.
안심이 안되는 부분의 테스트를 보완하고, 특히 로딩시에 로딩중 메세지 보여주는 부분을 테스트하고 구현해보고 싶습니다.

2020-10-20 15:41 UTC, hannut91 commented
어떤 피드백을 드려야할지 잘 모르겠네요. DM으로 자세히 문의주시면 답변드릴게요. ㅎㅎ

2020-10-21 11:23 UTC, gringrape commented
> 어떤 피드백을 드려야할지 잘 모르겠네요. DM으로 자세히 문의주시면 답변드릴게요. ㅎㅎ

감사합니다 ㅎ 정리해서 질문드릴게요.

2020-10-21 14:53 UTC, gringrape commented
## 작업 내용
- 레스토랑 카테고리 목록 보기
- 서버에서 데이터를 가져오는중에 '로딩중' 표시
- api, action 테스트

## 작업 후기
- loading 이라는 boolean state 를 설정해서, 로딩중을 구현하였습니다. status 라고 해서, 서버요청이 실패했을경우 메세지도 추가할 수 있을 것 같습니다.

2020-10-21 17:06 UTC, hannut91 requested changes

2020-10-21 17:06 UTC, hannut91 commented on src/App.test.jsx
> +      setState(state);
테스트를 준비하는 과정을 위에 적어주면 좋을 것 같아요.

```js
context('when state has been loaded', () => {
  beforeEach(() => {
    setState({});
  });

  it('renders state, has called dispatch', () => {
    ...
  });
});

2020-10-21 17:06 UTC, hannut91 commented on src/redux/actions.js
> +      });
```js
const [categories, regions] = await Promise.all([
  fetchCategories(),
  fetchRegions(),
]);

dispatch(setCategories(categories));
dispatch(setRegions(regions));
dispatch(updateLoading(false));
```

이렇게하면 depth가 줄어서 더 좋을 것 같아요

2020-10-22 16:36 UTC, gringrape commented
## 작업내용
- 레스토랑 목록 보기
- 리듀서, 액션 분리
## 상태
### category
  - categories
  - loading
  - selectedId
### region
  -  regions
  - loading
  - selectedName
### restaurant
  - restaurants
  - loading

## 고민한 지점
### 상태를 분리하는 기준
옵션 1. category, region 등 도메인에 따라 분리
옵션2. loading 은 loading 끼리, collection 은 collenction 끼리 나누기

UI 가 도메인 별로 잘나누어져 있으므로 옵션1이 편하게 느껴져서 그렇게 나누었습니다.

2020-10-23 04:19 UTC, hannut91 commented on src/App.jsx
> +  })));
여기 소괄호가 하나 더 들어간 것 같아요. 없어도 기능상 문제가 없을거에요

2020-10-23 04:25 UTC, hannut91 commented on src/actions/asyncActions.js
> +    dispatch(updateRegionsLoading(true));
```js
[updateCategoriesLoading, updateRegionsLoading].forEach((action) => {
  dispatch(action(true));
);
```

음.. 이렇게 하는건 너무 복잡해보이겠죠? 허허

2020-10-23 04:26 UTC, hannut91 commented on src/components/App.jsx
> +    loading: category.loading && region.loading,
둘중 하나라도 로딩이면? 이 맞지 않나요? 

`category.loading || region.loading`

2020-10-23 07:31 UTC, gringrape commented on src/actions/asyncActions.js
> +    dispatch(updateRegionsLoading(true));
감사합니다 ㅎ 이부분이 확실히 복잡해 보이는군요 ㅜ 
말씀해주신거 참고해서 여러가지로 시도해보겠습니다

2020-10-24 14:46 UTC, gringrape commented
## 작업내용
- 비동기액션을 각 콜렉션 별로 분리.
- 불명확한 내용 리팩토링.
## 질문
### 1. 상태 이름 
상태를 category, region, restaurant 이렇게 나누고 하위에 콜렉션과 로딩을 두었는데,
category 밑에 categories 가 있으니 잘 안맞네요 ㅜ. 이름 지으시는 노하우나 혹시 이런상황에서는
어떻게 나누실지 의견을 구하고 싶습니다.
### 2. 지역 선택 id vs name?
선택된 지역을 상태에서 이름으로 저장하게 되어있는데, 아이디로 해야하나 고민이 되네요.
사실 api 에서 이름을 변수로 요구해서 이렇게 한 영향도 있는데, 지역은 이름으로도 유니크한것 같기도 하고.
이부분도 의견을 구하고 싶습니다.

2020-10-25 05:22 UTC, hannut91 commented
1. 이름짓는 노하우라는건 잘 모르겠네요. 이름이란건 언제든 변경될 수 있습니다. 처음에 좋다고 생각했던 이름도 나중에 점점 기능이 변경됨에 따라 혹은 도메인 지식에 대해 더 습득함에 따라 이전의 이름이 지은것이 아에 잘못될 수도 있고 더 좋은 이름이 생겨날 수도 있습니다.

리듀서를 너무 빨리 나눴다고 생각되신다면 다시 합치면 됩니다 ㅎㅎ

2. 선택의 문제인 것 같네요. 저라면 id로 일관되게 했을 것 같습니다. 왜냐하면 name이 겹치지 않을 것이라는 것을 누가 보장할까요? id는 DB가 보장합니다.

2020-10-25 06:05 UTC, hannut91 approved these changes

2020-10-25 06:05 UTC, hannut91 commented on src/actions/asyncActions.js
> +    return dispatch(updateCategoriesLoading(false));
여기서는 return하지 않는게 좋을 것 같아요. 실제로 반환한 값을 사용하는 것이 아니니까요

2020-10-25 06:05 UTC, hannut91 commented on src/components/categories/CategoriesContainer.test.jsx
> +  it('calls dispatch when clicked', () => {
when clicked는 테스트 대상인 것 같아요. 결과가 아니라

2020-10-25 06:05 UTC, hannut91 commented on src/services/api.test.js
> +  );
`mockResolvedValue`는 이미 resolved된 값을 반환하기 때문에 `Promise`객체를 만들어서 넣어줄 필요가 없습니다.

```js
global.fetch = jest.fn().mockResolvedValue({ json: async () => data });
```

2020-10-26 14:35 UTC, hannut91 commented
채널에 회고를 남겨주셔서 머지합니다! 고생하셨어요 ㅎㅎ

2020-10-26 14:35 UTC, merged