[Week5] Assignment 1 - 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #26
Opened 2020-10-20 13:35 UTC by wjy5446

# 목표
- TDD로 기능 구현
- 레스토랑 지역 목록 보기 기능
- 레스토랑 카테고리 목록 보기 기능
- 레스토랑 목록 보기 기능
- 커버리지 100% 달성요구사항

# 진행사항
- [x] 디자인과 관련된 테스트 코드 및 코드 작성
- [x] 함수 호출 관련된 테스트 코드 및 코드 작성
- [ ] redux를 이용한 컴포넌트 작성

2020-10-20 15:02 UTC, hannut91 requested changes

2020-10-20 15:02 UTC, hannut91 commented on src/App.jsx
> +  const resultList = ['양천주가', '밀면넘어져요'];
나름대로 널리 쓰이는 의미가 있는 단어를 다른 의미로 사용하면 안됩니다. List라는 이름은 프로그래머에게 자료형 List라는 특수한 의미를 가지고 있습니다.  따라서 변수가 실제로 List가 아니라면 변수 이름에 List가 있어서는 안됩니다. 여러개를 나타낸다면 단순히 복수형을 사용하는게 좋습니다. 

See also
  - 클린코드 - 2장 의미 있는 이름 - 그릇된 정보를 피하라 - http://www.kyobobook.co.kr/product/detailViewKor.laf?barcode=9788966260959

2020-10-20 15:02 UTC, hannut91 commented on src/Buttons.test.jsx
> +  });
handle*이라고 이름을 붙이는 이유는 특정 이벤트가 발생했을 때 그 이벤트를 처리하는 함수이기 때문입니다.  

```js
function handleClick() {
  alert('버튼이 클릭됐어요!');
}

<Button onClick={handleClick} />
```

위의 예제를 보면 보면 Click 했을 때 handleClick이 처리한다 라고 읽을 수 있습니다. 그래서 이벤트 처리 함수를 컴포넌트로 전달할 때는 on으로 시작하는 이름으로 전달합니다.

2020-10-20 15:02 UTC, hannut91 commented on src/Buttons.test.jsx
> +});
![image](https://user-images.githubusercontent.com/14071105/96604873-8d01de80-1330-11eb-9e3a-56136c288473.png)

빈 줄을 추가해야하는 이유는 GitHub의 컨벤션 때문에 그렇습니다. GitHub은 변경사항을 표시할 때 변경전 부분과 변경 후 를 모두 보여줍니다. 

```js
console.log('Hello');
```

만약 위와 같이 빈 줄이 없는 코드에서 아래에 코드를 추가하게 되면 Git은 다음과 같이 표시합니다.

```js
- console.log('Hello');
+ console.log('Hello');
+ console.log('world!');
```

저는 단순히 아래 한 줄만 추가했는데 왜 세줄이 변경되었다고 나오는 걸까요? 그 이유는 줄바꿈 문자 \n가 들어갔기 때문입니다. 

```js
- console.log('Hello');
+ console.log('Hello');\n
+ console.log('world');
```

만약 미리 빈 줄을 하나 추가한 상태에서 아래에 새로운 코드를 작성할 경우에는 다음과 같이 보여집니다.

```js
+ console.log('world');
```

이미 \n이 추가되어 있기 때문이죠. 따라서 코드 마지막 줄에 빈 줄 하나를 항상 추가해주는게 좋습니다.

```suggestion
});
// 새로운 코드
```

2020-10-21 11:19 UTC, wjy5446 commented on src/App.jsx
> +  const resultList = ['양천주가', '밀면넘어져요'];
클린코드 한번 읽어 보야 겠네요. 변수명 추천 감사드립니다.

2020-10-21 11:50 UTC, wjy5446 commented on src/Buttons.test.jsx
> +  });
아래처럼 handleClick으로 전달 받아서 onClick에 지정해 주기 위해서 handle로 했는데, 말씀해주신 것 들어보니 이렇게 하면 Buttons는 `<Buttons haldeClick={handleClick}` 처럼 나오네요.
```jsx
export default function Buttons({ buttonNameList, handleClickSelect }) {

  return (
            <button onClick={handleClickSelect}>
              {buttonName}
            </button> )
}
```

2020-10-21 11:52 UTC, wjy5446 commented on src/Buttons.test.jsx
> +});
그렇군요. 그래서 eslint에서 밑줄을 추가하라고 나오는 거였군요. 감사합니다.

2020-10-21 16:32 UTC, hannut91 requested changes

2020-10-21 16:32 UTC, hannut91 commented on src/App.test.jsx
> +  }));
매번 초기화 되어야 하는 로직들은 `beforeEach`에 넣는게 좋을 것 같아요.

2020-10-21 16:32 UTC, hannut91 commented on src/Buttons.jsx
> +            </button>
여기서 button의 type은 `click`이 맞을 것 같아요. submit은 form안에서만 사용해야 해요.

그리고 이렇게 하는건 `buttonName`이 3번 쓰이고 있는데 이렇게 하면 2번 밖에 안쓰일 것 같아요 ㅎㅎ
```js
<button
  name={name}
  onClick={onClickSelect}
  type="click"
>
  {buttonName}{(buttonName === selectedButton) && '(V)'}
</button>
```

2020-10-21 16:32 UTC, hannut91 commented on src/Buttons.test.jsx
> +      />));
렌더하는 부분이 계속 반복되고 있는 것 같아요. 함수로 추출하는건 어떨까요?

See also
  - https://refactoring.com/catalog/extractFunction.html
  - https://github.com/hannut91/refactoring-practice/tree/master/6.1-extract-function

2020-10-21 16:32 UTC, hannut91 commented on src/ButtonsContainer.jsx
> +    const updateInfo = {
`info`라는 이름이 무슨 역할을 하는지 잘 모르겠어요. 너무 보편적인 이름때문에 아무런 도움이 안되는 것 같아요. 더 좋은 이름을 찾아보는게 좋을 것 같습니다

2020-10-21 16:32 UTC, hannut91 commented on src/List.jsx
> +          <li key={index}>{item}</li>
key를 `index`로 사용하는 것은 권장되지 않습니다.

See also
  - https://reactjs.org/docs/lists-and-keys.html#keys

2020-10-21 16:32 UTC, hannut91 commented on src/List.test.jsx
> +});
`items가 주어지면`이라는 말이 이해하기 어려워요. 왜냐하면 주어지지 않았을 경우도 뭔가 있을 것 처럼 보입니다. 정말로 주어지지 않은 경우를 테스트를 추가하던지 아니면 빼는게 더 이해가 쉬울 것 같아요

2020-10-21 16:32 UTC, hannut91 commented on src/ListContainer.jsx
> +}
`results`가 뭔지 잘 모르겠어요.

2020-10-21 16:32 UTC, hannut91 commented on src/reducer.test.js
> +});
하나의 테스트가 하나의 일을해서 좋긴한데 너무 길어서 이해하기 어려운 것 같아요. 객체로 한 번에 비교하는 건 어떨까요? jest의 `toEqual` matcher를 사용하면 가능할거에요.

See also
  - https://jestjs.io/docs/en/using-matchers

2020-10-21 16:32 UTC, hannut91 commented on src/reducer.test.js
> +  });
잘못됐다기 보다 `정의되어있지 않은`액션이 더 정확할 것 같아요. 잘못됐다는 것은 `type` 속성이 존재하지 않는 다던지, 그런 생각이 들어요

2020-10-22 13:28 UTC, wjy5446 commented on src/Buttons.jsx
> +            </button>
type을 click이라고 작성하니 eslint에서 걸리네요. 그래서 button이라는 type을 사용했습니다.!! 
button은 제시한 방법대로 쓰면 줄일 수 있네요 ㅎㅎ

2020-10-22 13:57 UTC, wjy5446 commented on src/ButtonsContainer.jsx
> +    const updateInfo = {
selectedinfo를 좀 더 명확히 알 수 있도록 selectedButton으로 변경합니다.

2020-10-22 14:21 UTC, wjy5446 commented on src/List.jsx
> +          <li key={index}>{item}</li>
redux의 state구조를 단순히 리스트 넣는 게 아니라, {id, name}구조의 리스트로 변경합니다. 
그리고 key로 입력한 id로 넣어주었습니다.

2020-10-22 14:25 UTC, wjy5446 commented on src/List.test.jsx
> +});
해당 테스트 코드에서 필요없는 context를 제거했습니다.

2020-10-22 14:29 UTC, wjy5446 commented on src/ListContainer.jsx
> +}
results를 restaurants로 이름을 변경했습니다.

2020-10-22 14:32 UTC, wjy5446 commented on src/reducer.test.js
> +});
toEqual를 이용해서 작성하는 게 더 간단하네요!

2020-10-22 14:32 UTC, wjy5446 commented on src/reducer.test.js
> +  });
`정의되어 있지 않은`이란 용어가 더 나은 것 같네요.

2020-10-22 14:43 UTC, wjy5446 commented on src/Buttons.test.jsx
> +      />));
renderButtons 함수를 생성해서 반복적인 코드를 줄였습니다.

2020-10-22 14:51 UTC, wjy5446 commented on src/App.test.jsx
> +  }));
해주신 피드백이 beforeEach에 useDispatch와 useSelector를 넣어주는 걸로 말씀해주신게 맞나요?

2020-10-22 16:17 UTC, hannut91 commented on src/App.test.jsx
> +  }));
맞습니다 ㅎㅎ

2020-10-23 00:19 UTC, hannut91 requested changes

2020-10-23 00:19 UTC, hannut91 commented on src/App.test.jsx
> +    restaurants: [{ id: 1, name: '밀면' }],
테스트에서 사용되는 데이터들이 반복해서 사용되고 있습니다. 테스트용 데이터를 미리 만들어놓고 사용하여 중복을 줄일 수 있고, 테스트의 복잡성을 낮출 수 있습니다. 또 복잡한 계산같은 경우 믿고 이미 테스트가 된 데이터들을 저장해놓을 수 있습니다. 이러한 테스트용 데이터를 fixture라고 부릅니다. fixtures라는 폴더를 하나 만들고 여기에 테스트용 데이터들을 모아놓고 가져다가 사용하는건 어떨까요?

2020-10-23 00:19 UTC, hannut91 commented on src/Buttons.test.jsx
> +  it('버튼을 클릭하면 handleClickSelect 함수가 출력됩니다.', () => {
함수가 출력되는 것 보다는 실행됐습니다 라고 표현하는 건 어떨까요?

2020-10-23 00:19 UTC, hannut91 commented on src/Buttons.test.jsx
> +    it('해당 버튼 문구에 "(V)"가 추가됩니다.', () => {
해당 버튼이 무엇인가요?

2020-10-23 00:19 UTC, hannut91 commented on src/Buttons.test.jsx
> +    it('ButtonsNameList의 이름을 가진 버튼들이 출력됩니다.', () => {
ButtonNameList는 너무 세부 구현의 이름인 것 같아요

2020-10-23 00:19 UTC, hannut91 commented on src/actions.test.js
> +  it('호출하면 intializeSelectButtons action이 반환합니다. ', () => {
호출하면이라는 단어는 없어도 괜찮을 것 같아요

2020-10-23 00:19 UTC, hannut91 commented on src/reducer.js
> +        [action.payload.type]: action.payload.value,
action.payload가 반복되어서 복잡해 보입니다. 구조 분해 할당을 이용해서 단순화 할 수 있을까요?

See also
  - https://ko.javascript.info/destructuring-assignment

2020-10-23 11:28 UTC, wjy5446 commented on src/Buttons.test.jsx
> +  it('버튼을 클릭하면 handleClickSelect 함수가 출력됩니다.', () => {
실행했습니다.가 더 맞는 것 같네요.

2020-10-23 11:31 UTC, wjy5446 commented on src/Buttons.test.jsx
> +    it('해당 버튼 문구에 "(V)"가 추가됩니다.', () => {
`선택된 버튼 문구에 "(V)"가 추가됩니다.`라는 테스트명이 더 나은 것 같네요.

2020-10-23 11:33 UTC, wjy5446 commented on src/Buttons.test.jsx
> +    it('ButtonsNameList의 이름을 가진 버튼들이 출력됩니다.', () => {
ButtonsNameList에서 ButtonNames로 이름을 변경했는데 여기만 수정하지 않았네요.

2020-10-23 11:36 UTC, wjy5446 commented on src/actions.test.js
> +  it('호출하면 intializeSelectButtons action이 반환합니다. ', () => {
없어도 되겠네요.

2020-10-23 11:43 UTC, wjy5446 commented on src/reducer.js
> +        [action.payload.type]: action.payload.value,
구조 분해 할당을 사용하니 좀더 깔끔해 지네요.

2020-10-23 11:55 UTC, wjy5446 commented on src/App.test.jsx
> +    restaurants: [{ id: 1, name: '밀면' }],
fixtures폴더 만들고, 그 안에 data.js안에 
```
const data = {
  locations: [{ id: 1, name: '서울' }, { id: 2, name: '대구' }],
  foodTypes: [{ id: 1, name: '한식' }, { id: 2, name: '일식' }],
  selectedButtons: {
    location: '',
    foodType: '',
  },
};

export default data;
```

이런 식으로 넣고 data를 꺼내서 사용하면 될까요?

2020-10-24 04:14 UTC, hannut91 commented on src/App.test.jsx
> +    restaurants: [{ id: 1, name: '밀면' }],
`loactions`라는 `데이터`를 저장해놓고 사용하면 좋을 것 같아요 ㅎㅎ 이건 아에 상태를 전부다 넣은 것 같아요. 우리가 사용하고 있는 데이터란 무엇인가 생각해보시면 좋을 것 같아요

2020-10-24 05:21 UTC, hannut91 requested changes

2020-10-24 05:21 UTC, hannut91 commented on src/App.jsx
> +    dispatch(intializeSelectButtonsAsync());
함수가 async하게 동작하는지는 중요한 정보가 아닐 것 같아요. 컴포넌트는 단순히 액션만 발행할 뿐이에요

2020-10-24 05:21 UTC, hannut91 commented on src/Buttons.jsx
> +  buttonNames,
버튼 이름을이라고 하면 이름의 모임일 것 같은데 아이디와 이름을 같이 가지고 있는 것 같아요. buttons는 어떨까요?

2020-10-24 05:21 UTC, hannut91 commented on src/Buttons.jsx
> +              {(name === selectedButton) && '(V)'}
이름과 선택된 버튼을 비교하고 있는 것 같아요. 버튼과 이름을 비교하는게 이해하기 어려운 것 같아요. 이름은 다른 이름과 비교하는게 더 자연스럽게 읽히는 것 같아요

2020-10-24 05:21 UTC, hannut91 commented on src/CategoryContainer.jsx
> +    const selectedButtonValue = {
변수의 이름이 오히려 이해를 어렵게하는 것 같아요. Inline variable 리팩터링을 하는 건 어떨까요?

See also
  - https://refactoring.com/catalog/inlineVariable.html

2020-10-24 05:21 UTC, hannut91 commented on src/CategoryContainer.test.jsx
> +  it('버튼이 클릭되면 setSelectInfo action이 dispatch 됩니다.', () => {
테스트 이름이 수정이 안된 것 같아요

2020-10-24 05:21 UTC, hannut91 commented on src/actions.js
> +  const categories = await fetchCategories();
지역목록을 모두 가져온 다음에 카테고리 목록을 가져오고 있습니다. 동시에 두 요청을 보내려면 어떻게 해야하나요?

2020-10-24 05:21 UTC, hannut91 commented on src/Buttons.jsx
> +              onClick={onClickSelect}
버튼을 클릭했을 때 버튼의 있는 텍스트를 상태로 관리하고 있더라구요. 실제 값과 버튼의 텍스트가 다를 때는 문제가 발생할 수 있어요

2020-10-24 12:05 UTC, wjy5446 commented on src/App.jsx
> +    dispatch(intializeSelectButtonsAsync());
저는 intializeSelectButtons라는 액션을 발행하는 함수와 해당 액션을 발행하는 thunk라는 함수를 구분하기 위해서 Async라는 이름을 사용했습니다. 그럼 단순히 Async라는 이름 말고 다른 함수명을 사용하는 게 좋을 까요? 예를 들어 `getRegionAndCategory` 이란 이름을 사용하는 게 좋을 까요?

2020-10-24 12:07 UTC, wjy5446 commented on src/Buttons.jsx
> +  buttonNames,
기존에는 단순히 버튼 이름만 전달해서 buttonNames라고 명명했는데, 지금은 아이디와 이름은 전달하기 buttons라고 해야 겠네요.

2020-10-24 12:14 UTC, wjy5446 commented on src/Buttons.jsx
> +              {(name === selectedButton) && '(V)'}
이 피드백은 제가 이해를 잘 못하는 것 같네요. 멘토님이 말씀해주신 게 selectedButton이란 이름보다는 selectedButtonName과 같이 이름과 이름이 비교할 수 있도록 작성하는 게 더 좋은 방법이라고 말씀하시는 건가요?

2020-10-24 12:19 UTC, wjy5446 commented on src/CategoryContainer.jsx
> +    const selectedButtonValue = {
inline variable로 작성하니 더 보기 편해졌네요 !!
혹시 멘토님께서는 inline variable 작성 기준이 있으신가요??

2020-10-24 12:21 UTC, wjy5446 commented on src/CategoryContainer.test.jsx
> +  it('버튼이 클릭되면 setSelectInfo action이 dispatch 됩니다.', () => {
그러네요. 피드백 감사합니다.!!

2020-10-24 12:24 UTC, wjy5446 commented on src/actions.js
> +  const categories = await fetchCategories();
저도 프라미스에 대해서 익숙하지는 않지만, 검색해보니 `Promise.all()`이란 걸 사용하면 동시에 요청을 보낼수 있지 않을까요?

2020-10-24 12:30 UTC, wjy5446 commented on src/Buttons.jsx
> +              onClick={onClickSelect}
과제를 진행하다보니 restaurants의 정보를 api로 가져오려고 했을 때, category는 id를 사용했네요 ;; 
그래서 object로 상태를 관리하도록 수정했습니다.!!

2020-10-24 13:08 UTC, wjy5446 commented
- 우선 관제를 진행하다보니 리액트에 아직 미숙해서 인지 에러가 많이 발생하네요. 그래서 급한 마음으로 디버깅을 하다보니 TDD가 전혀 진행되지 않아네요.

- 그래도 몇몇 궁금한 사항이 있어서 질문 남깁니다. 

## 질문사항

1. api.js 파일에 해당 url에서 데이터를 받아오는 비동기 함수가 있는 데 이는 어떻게 테스트 코드를 작성하는 게 좋을 까요?
```javascript
export async function fetchRegions() {
  const url = 'https://eatgo-customer-api.ahastudio.com/regions';
  const response = await fetch(url);
  const data = response.json();
  return data;
}
```

2020-10-25 04:12 UTC, hannut91 commented on src/CategoryContainer.jsx
> +    const selectedButtonValue = {
무엇이 더 이해하기 좋을까? 라는 질문을 던져보시면 좋을 것 같아요. Inline variable이 있으면 extract variable이 있습니다. 서로 반대되는 기능인데 둘다 리팩터링 방법이 존재합니다. 선택의 문제에요. 식이 충분히 이해할 수 있다면 inline variable 으로 작성하고, 추가적인 설명이 필요하거나, 단계가 필요하다면 extract variable 리팩터링을 합니다.

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.3-extract-variable
  - https://github.com/hannut91/refactoring-practice/tree/master/6.4-inline-variable

2020-10-25 04:12 UTC, hannut91 commented on src/actions.js
> +  const categories = await fetchCategories();
맞습니다 ㅎㅎ

2020-10-25 05:03 UTC, hannut91 commented
1. fetch를 mocking해서 처리해줄 수 있을 것 같아요.
2. selectedButtons가 변경될 때 useEffect가 호출되는건 우리가 테스트 할 필요는 없겠죠? 리액트를 테스트하는 것이 되니까. 그러면 이 useEffect에서 실행되는 로직에 대해서만 테스트할 수 있겠죠

2020-10-25 05:08 UTC, hannut91 requested changes

2020-10-25 05:08 UTC, hannut91 commented on src/App.jsx
> +    dispatch(intializeSelectButtonsAsync());
네 ㅎㅎ `getRegionsAndCategories`가 더 낫겠죠? 여러개니까

2020-10-25 05:08 UTC, hannut91 commented on src/App.test.jsx
> +  it('컴포넌트가 생성되면 dispatch가 호출됩니다.', () => {
`컴포넌트가 생성되면`이라는 말은 없어도 될 것 같아요

2020-10-25 05:08 UTC, hannut91 commented on src/Buttons.jsx
> +              {(name === selectedButton) && '(V)'}
네네 맞습니다

2020-10-25 05:08 UTC, hannut91 commented on src/CategoryContainer.jsx
> +    }
indexOf로 비교하는 것 보다는 `buttonText.includes`로 하는게 더 의도가 드러날 것 같아요. 혹은 정규식을 사용할수도 있겠죠

2020-10-25 05:08 UTC, hannut91 commented on src/CategoryContainer.jsx
> +    const buttonText = event.target.textContent;
버튼의 내용과 데이터가 다를경우에는 문제가 발생할 수 있을 것 같아요

2020-10-25 05:08 UTC, hannut91 commented on src/ListContainer.jsx
> +    }
```js
if (!region || !category) {
  return
}
```

이렇게 표현할 수도 있겠네요

2020-10-25 12:00 UTC, wjy5446 commented on src/CategoryContainer.jsx
> +    const selectedButtonValue = {
감사합니다.

2020-10-25 12:23 UTC, wjy5446 commented on src/App.test.jsx
> +  it('컴포넌트가 생성되면 dispatch가 호출됩니다.', () => {
네 피드백 반영하겠습니다.

2020-10-25 12:26 UTC, wjy5446 commented on src/CategoryContainer.jsx
> +    }
includes가 좀 자연스럽게 읽히네요.

2020-10-25 12:28 UTC, wjy5446 commented on src/ListContainer.jsx
> +    }
좀 더 읽기 쉬워 지네요. 감사합니다.

2020-10-25 13:35 UTC, wjy5446 commented
## 질문 사항

- 현재 아래 코드와 같이 thunk 함수 테스트만 남겨두고 있는데, 해당 코드 테스팅은 어떻게 하는지 모르겠습니다. 혹시 어떻게 진행하면 좋을 까요?
```
export const getRegionAndCategories = () => async (dispatch) => {
  const regions = await fetchRegions();
  const categories = await fetchCategories();

  dispatch(intializeSelectButtons({ regions, categories }));
};
```

2020-10-25 16:02 UTC, hannut91 commented
액션에서 주요 관심사가 무엇인지 생각해보시면 좋을 것 같습니다. 예를들어서 레스토랑 목록을 가져오는 것을 볼게요.

```js
export const loadRestaurants = () => async (dispatch, getState) => {
  const restaurants = await restaurantService.getRestaurants();
  
  dispatch(setRestaurants(restaurants));
}
```

이 비동기 액션에서 하는 일은

서버에서 레스토랑 목록을 가져온다.

가져온 레스토랑 목록을 setRestaurants액션을 통해 dispatch한다.

restaurantService에서 레스토랑 목록을 요청한 후 레스토랑을 업데이트 하는 setRestauarnts라는 액션을 다시 dispatch합니다. 하지만 레스토랑 목록을 어떻게 가져오는지는 주요한 관심사가 아닙니다. 그래서 getRestaurants는 mocking하여 처리하고 올바르게 가져왔다고 가정하고 액션이 올바르게 처리되는지 테스트합니다.

```js
import thunk from 'redux-thunk';

import configureStore from 'redux-mock-store';

const middlewares = [thunk];
const mockStore = configureStore(middlewares);

const restaurants = [
  { id: 1, name: '마녀주방', category: '한식', address: '강남' },
];

getRestaurants.mockResvoledValue(restaurants);

test('loadRestaurants', async () => {
  store = mockStore({});
  
  await loadRestaurants();
  
  const actions = store.getActions();
  
  expect(actions[0]).toEqual(setRestaurants(restaurants));
});
```

See also
  - https://github.com/reduxjs/redux-mock-store

2020-10-26 12:43 UTC, wjy5446 commented
# 질문사항

- 제가 reducer를 object literal lookup을 이용해서 작성했는데, 실제로도 이런 방식으로 reducer를 작성하나요? 제가 실제로 작성해보니 예외처리해야 되는 경우도 많고, switch문에 비해서 오히려 코드가 복잡하게 보이네요.

2020-10-26 14:32 UTC, hannut91 commented
Object literal lookup은 reducer이외에도 많이 사용합니다. 나중에 redux toolkit을 사용하면 사실 많이 사용할 필요가 없긴합니다. 나중에 더 좋은 방법을 배우시게 될거에요

2020-10-26 14:34 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 반복적으로 연습하게 될테니 여기서 마무리하면 좋을 것 같습니다!

이번 과제를 통해서 무엇을 배우셨나요? 다음 과제에서 더 시도해보고 싶으신 것이 있으신가요?

2020-10-27 15:23 UTC, wjy5446 commented
# 3주차 회고
## 1. 한 일
- TDD 실습
- thunk
- promise, async-await

## 2. 배운점

- useSelector와 useDispatch에 대한 mock 함수는 beforeEach에서 넣어 주는 것이 좋다. 
- button을 단순히 click 용도로 사용한다면 type을 button으로 넣어주는 것이 좋다.
- redux의 state를 리스트로 저장할 때에는 반드시 id가 포함된 객체 형태로 넣어주는 것이 좋다. (map을 사용할 때, id를 지정해줘야 하는 경우가 있음)
- result, item이런 추상적인 변수명 보다는 restaurants, regions와 같은 구체적인 변수명을 사용하는 것이 좋다.
- thunk 함수명을 작성할 때에도 thunk을 명시하기 위해서 뒤에 Async을 사용하는 것보다는 실질적인 함수로 표현해 주는 것이 좋다.

- 태스트명을 작성할 때에도, 상대방이 이해하기 쉽게 작성하는 것이 좋다.
- 자주 사용되는 예시 데이터는 fixtures를 폴더를 만들어서 따로 관리한다.
- promise에 대한 mock을 작성할 때에는 `{function name}.mockResolvedValue`를 사용해서 나타내면 된다.
- thunk에 대한 테스팅은 `redux-mock-store`을 통해서 이루어진다. 아래와 같이 mockStore을 만들어주고, mockStore에서 thunk함수를 dispatch했을 때, store에서 해당 actions를 받는 지 확인해주면 된다.

```javascript
import thunk from 'react-thunk'
import configureStore from 'redux-mock-store'

const middlewares = [thunk]
const mockStore = configureStore(middlewares)

getRegions.mockResolvedValue(regions);

test('thunk_func_name', () => {
  const store = mockstore({});
  await store.dispatch(getRegions());
  expect(store.getActions()).toEqual([getRegions()]);
})
```

## 3. 느낀 점 & 자기 선언
 
이번에도 TDD는 매우 익숙하지가 않았다. 비동기를 코드에 작성하려고 하다보니 에러가 무지하게 발생하게 되고, 이 에러를 해결하는 데 급급한 나머지 코드를 먼저 작성하고, 그 이후에 커버리지를 보면서 테스트 작성하는 형식으로 코드를 작성하게 되었다. 우선적으로 TDD을 좀 잘 작성하려면 급한 마음부터 진정하고 들어가야 겠다라는 생각을 하게 되었다. (급하면 코드 작성에만 집중하게 된다.....) 그리고 아샬 님에 TDD 작성하는 모습을 보면 내가 너무 RED-GREEN-REFAC에 집착하지 않았나 싶다. 아샬님의 경우, 코드를 작성하고, 테스트 코드를 작성하는 부분도 존재한다. 그런 면에 있어서 TDD에 너무 완벽하게 하려는 자세을 좀 줄이고 코드에 집중하는 것이 더 좋지 않나 라는 생각도 들었다. 

그래서 다음에 TDD를 작성할 때에는 첫 번째 안정된 마음으로 코드를 작성하고, 두 번째 TDD 방법에 대한 집착을 좀 줄이고 작성해야 겠다.

2021-01-17 12:53 UTC, merged