Add a test for Button component
CodeSoom/react-week5-assignment-1 pull request #29
Opened 2020-10-20 15:39 UTC by hyejineee

## 기능 

- [ ] 레스토랑 지역 목록 보기 기능
- [ ] 레스토랑 카테고리 목록 보기 기능
- [ ] 레스토랑 목록 보기 기능

## 요구사항
- [ ] TDD로 기능 구현
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

2020-10-21 16:59 UTC, hannut91 requested changes

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonItem.jsx
> +export default function Button({ children, onClick, checked }) {
파일이름이랑 컴포넌트이름이랑 똑같이 짓는건 어떨까요?

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonItem.jsx
> +export default function Button({ children, onClick, checked }) {
`checked`보다 `selected`는 어떨까요?

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonItem.test.jsx
> +describe('ButtonItem', () => {
여기 테스트이름도 `Button`은 어떨까요?

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonItem.test.jsx
> +  const handleClick = jest.fn();
각 테스트는 다른 테스트에 영향을 줘서도 안되고, 다른 테스트에 의존해서도 안됩니다. 그러면 테스트를 유지보수하기 굉장히 어려워지고 테스트가 의도치 않게 동작할 수 있습니다.  예를들어서

```js
describe('Component', () => {
  const handleClick = jest.fn();
  
  const renderComponent = () => render((
    <Component onClick={handleClick} />
  ));
  
  test('click test', () => {
    const { getByText } = renderComponent();
    
    fireEvent.click(getByText('클릭'));
    
    // 통과
    expect(handleClick).toBeCalled();
  });
  
  text('non click test', () => {
    const { getByText } = renderComponent();
    
    // 실패!
    expect(handleClick).not.toBeCalled();
  });
});
```

테스트 코드가 위에서부터 순서대로 실행이 되는데 위의 테스트에서 이미 클릭을 해서 handleClick은 호출이 된 상태가 되었습니다. 그래서 클릭이 안되어있어야 할 테스트에서 실패하게 됩니다. 이 것은 우리가 의도한게 아니라 테스트 환경을 적절히 초기화 시키지 않아서 생긴 문제입니다. 따라서 위의 문제는 아래와 같이 초기화를 해주어야 합니다.

```js
describe('Component', () => {
  const handleClick = jest.fn();
  
  // 테스트가 실행되기 전에 실행  
  beforeEach(() => {
    // mocking 함수들을 초기화
    jest.clearAllMocks();
  });
  
  const renderComponent = () => render((
    <Component onClick={handleClick} />
  ));
  
  test('click test', () => {
    const { getByText } = renderComponent();
    
    fireEvent.click(getByText('클릭'));
    
    // 통과
    expect(handleClick).toBeCalled();
  });
  
  text('non click test', () => {
    const { getByText } = renderComponent();
    
    // 통과
    expect(handleClick).not.toBeCalled();
  });
});
```

mocking한 함수 뿐만 아니라 테스트끼리 상태가 공유되는 것들은 모두 초기화해주는게 좋습니다

See also
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks
  - https://jestjs.io/docs/en/setup-teardown

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonItem.test.jsx
> +  });
```js
describe('click', () => {
  it('calls onClick handler', () => {
      const { getByText } = renderButton();
      
      fireEvent.click(getByText('서울'));

      expect(handleClick).toBeCalled();
  });
});
```

이렇게 테스트 대상을 명시적으로 쓰고 어떤 일이 일어나는지 작성해주는건 어떨까요?

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonItem.test.jsx
> +  });
`context`안에 `it`으로 테스트 대상을 적어주는게 좋을 것 같아요

2020-10-21 16:59 UTC, hannut91 commented on src/ButtonList.jsx
> +export default function ButtonList({ labels, onClick, checkedValue }) {
`checkedValue`가 무엇인지 이해하기 어려운 것 같아요. 선택된 아이디를 나타내고 싶으셨던 거죠? 밑에 코드를 보니까 `id`랑 비교하고 있는 것 같아서요

2020-10-21 16:59 UTC, hannut91 commented on src/reducer.js
> +  return state;
`reducers[type]`이 없으면 주어진 `state`를 바로 반환하여 일찍 종료하고, 우리가 실제로 원하는 기능을 아래에 써주는건 어떨까요? 우리가 진짜로 원하는 기능은 맨 아래 코드이고, 만약 다른 경우가 있을 경우 일찍종료하도록 의도를 드러낼 수 있을 것 같아요

```js
if (!reducers[type]) {
  return state;
}

return reducers[type]({ state, payload });
```

2020-10-22 02:22 UTC, hyejineee commented on src/ButtonItem.jsx
> +export default function Button({ children, onClick, checked }) {
@hannut91 원래 Button이였던 컴포넌트에 <li>를 추가하면서 파일 이름을 ButtonItem으로 수정했었어요! Item이랑 Button이랑 굳이 나눌 필요가 없다고 생각해서 ButtonItem했는데 윤석님 생각은 어떠신가요???👀👀👀

2020-10-22 02:22 UTC, hyejineee commented on src/ButtonItem.jsx
> +export default function Button({ children, onClick, checked }) {
네넵 수정하겠습니다!

2020-10-22 02:24 UTC, hyejineee commented on src/ButtonItem.test.jsx
> +  const handleClick = jest.fn();
아 테스트를 변경할때 같이 해줬어야 하는데 까먹었네용ㅎㅎㅅㅎ 수정하겠습니다!

2020-10-22 02:24 UTC, hyejineee commented on src/ButtonItem.test.jsx
> +  });
넵 알겠습니다!!

2020-10-22 02:27 UTC, hyejineee commented on src/ButtonItem.test.jsx
> +  });
전반적으로 코드에 구멍이 많은 것 같아여,,,, 수정하겠습니다!!

2020-10-22 02:28 UTC, hyejineee commented on src/ButtonList.jsx
> +export default function ButtonList({ labels, onClick, checkedValue }) {
넹넹! 선택된 지역 또는 카테고리의 id를 받는 props에요! selectedId로 수정하면 괜찮을까요???

2020-10-22 02:28 UTC, hyejineee commented on src/reducer.js
> +  return state;
넵 수정하겠습니다!!

2020-10-22 03:02 UTC, hannut91 commented on src/ButtonItem.jsx
> +export default function Button({ children, onClick, checked }) {
저는 파일이름만 똑같이하면 문제 없어보여요 ㅎㅎ근데 ButtonItem이 버튼이긴 하죠? 클릭이 있으니까요 ㅎㅎ 그러면 무슨무슨 버튼으로 끝나는게 좋지 않을까요?

2020-10-22 03:11 UTC, hyejineee commented on src/ButtonItem.jsx
> +export default function Button({ children, onClick, checked }) {
흠... 그럼 button item 이랑 button으로 컴포넌트를 분리하는게 좋을 것 같네욤ㅎㅎㅎㅅㅎ 이렇게 수정할게요!!

2020-10-22 15:59 UTC, hannut91 commented on src/ButtonList.jsx
> +export default function ButtonList({ labels, onClick, checkedValue }) {
좋습니다 ㅎㅎ

2020-10-22 17:15 UTC, hannut91 requested changes

2020-10-22 17:15 UTC, hannut91 commented on src/container-component/CategoryContainer.jsx
> +      selectedId={selectedCategory}
`selectedId`라는 속성에 `selectedCategory`라고 하니까 조금 이해가 어려운 것 같아요. id와 category는 다르니까 넣어주는 `selectedCategory`가 selectedCategoryId같은 이름이 되어야 할 것 같아요

2020-10-22 17:15 UTC, hannut91 commented on src/container-component/CategoryContainer.test.jsx
> +  }));
애네들도 모든 테스트에서 동일하게 실행되어야 하므로 `beforeEach`안에 넣어주는게 좋을 것 같아요.

2020-10-22 17:15 UTC, hannut91 commented on src/presentational-component/ButtonList.test.jsx
> +    const { getByText } = renderButtonList(1);
수강생의 정보를 화면에 출력하는 함수가 있다고 가정해볼게요.

```js
printPersonal(윤석, 30, 하남, 12);
```

이것만 봐서는 각 값이 무엇을 의미하는지 파악하기 어렵습니다. 어렴풋이 이름이랑 사는 곳 정도는 가늠할 수 있겠지만요. 그래서 의미를 드러내기 위해서 값 앞에다가 이름을 줘서 전달할 수 있습니다.

```js
printPersonal(name = "윤석", age = 30, address = "하남", attendanceCount = 12);
```

그러면 이제 각각 전달하는 의미가 무엇인지 바로 파악이 됩니다. 하지만 이러한 형식의 named parameter는 다른 언어들 예를들어 코틀린에서는 지원하지만 자바스크립트에서는 지원하지 않습니다. 대신에 우리는 Object를 사용해서 동일한 결과를 얻을 수 있습니다.

```js
printPersonal({name: "윤석", age: 30, address: "하남", attendanceCount: 12});
```

그러면 각각 무엇을 의미하는지 바로 드러낼 수 있어서 코드를 읽는 입장에서도 더 도움이 되겠죠? 그래서 자바스크립트에서는 객체를 이용해서 파라미터를 굉장히 많이 사용합니다. 이렇게 할 경우 장점이 5가지 정도가 있습니다.

* 파라미터에 이름을 표현해줄 수 있다

예시에서 본 것 처럼 각 파라미터가 무엇을 나타내는지 표현해줄 수 있습니다.

* 옵셔널 데이터를 다루기 쉬워진다. 

만약 처음 예제에서 주소 정보가 필수 입력 파라미터가 아니라면 다음과 같이 호출 해야 합니다.

```js
printPersonal(윤석, 30, '', 12);
```

그러면 기본 값으로 주어야 하고, 어디에 빈 값을 넣어야 하는지도 인지하고 있어야 합니다. 만약 파라미터를 객체로 했었따면

```js
printPersonal({name: "윤석", age: 30, attendanceCount: 12});
```

그냥 그 속성으로 안넘기면 됩니다. 따라서 부가적인 데이터를 다루기 쉬워집니다.

* 순서에 상관없이 파라미터를 입력할 수 있다.

각 파라미터 순서에 맞춰서 파라미터를 넘겨주지 않고, 이름으로 넘겨주기 때문에 자리를 신경쓰지 않아도 되어서 순서를 신경쓰지 않고 파라미터를 넘겨줄 수 있습니다.

* 파라미터의 갯수가 늘어나더라도 괜찮다.

처음 예제는 파라미터가 계속 늘어나게 되면 계속 길어지는데, 객체로 분리할 경우 객체로 표현하여 짧게 표현할 수 있습니다.

```js
const person = {name: "윤석", age: 30, attendanceCount: 12};
printPersonal(person);
```js

* 객체로 의미있는 단위로 묶을 수 있다.

같은 속성을 가진 파라미터들은 객체로 묶어서 의미를 전달할 수 있습니다.

```js
const user = {name: "윤석", age: 30, address: "하남"};
const attendance = {
  absentCount: 12, 
  attendanceCount: 30,
  isPass() {
    return this.attendanceCount > 20;
  },
};
printPersonal(user, attendance);
```

See also
  - https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object
  - https://refactoring.com/catalog/introduceParameterObject.html
  - https://www.freecodecamp.org/news/elegant-patterns-in-modern-javascript-roro-be01e7669cbd/

2020-10-22 17:15 UTC, hannut91 commented on src/reducer.js
> +  selectedCategory: -1,
선택되지 않은 경우를 -1로 표시하신 것 같아요. null로 아에 비어있다는 것을 표현하는건 어떨까요?

2020-10-23 05:45 UTC, hyejineee commented on src/container-component/CategoryContainer.jsx
> +      selectedId={selectedCategory}
아 아하!! 넵 수정하겠습니다!

2020-10-23 05:47 UTC, hyejineee commented on src/container-component/CategoryContainer.test.jsx
> +  }));
네넵 알겠습니다~

2020-10-23 05:50 UTC, hyejineee commented on src/presentational-component/ButtonList.test.jsx
> +    const { getByText } = renderButtonList(1);
```js
const { getByText } = renderButtonList(1);
```
renderButtonList()의 파라미터를 객체로 넘겨주어서 의미를 나타내도록 하라는 거 맞으시져???

2020-10-23 05:50 UTC, hyejineee commented on src/reducer.js
> +  selectedCategory: -1,
넵 수정하겠습니다!!

2020-10-23 09:48 UTC, hyejineee commented
@hannut91 api에 대해서 테스트 만들어서 했는데 이렇게 하는게 맞는 건지 모르겠어여,,,

2020-10-23 12:14 UTC, hannut91 commented on src/presentational-component/ButtonList.test.jsx
> +    const { getByText } = renderButtonList(1);
맞습니다 ㅎㅎ 너무 장황하게 설명했네요.

2020-10-23 14:04 UTC, hyejineee commented on src/presentational-component/ButtonList.test.jsx
> +    const { getByText } = renderButtonList(1);
아니요ㅎㅎㅅㅎ 많은 정보를 얻을 수 있어서 좋았습니다ㅎㅎㅎㅎ

2020-10-23 14:39 UTC, hyejineee commented
api 테스트 하는 부분에서 fetch mocking 하는 과정을 jest 문서를 참고해서 다음과 같이 수정했습니다!

See also 
  - https://jestjs.io/docs/en/mock-functions#mocking-modules
```js
 global.fetch.mockResolvedValue({
      json: () => (regions),
    });
```

2020-10-24 04:13 UTC, hannut91 requested changes

2020-10-24 04:13 UTC, hannut91 commented on src/presentational-component/Restaurants.jsx
> +        ))
구조분해 할당을 사용해서 반본적으로 사용되는 `restaurant`을 없애는건 어떨까요?

2020-10-24 04:13 UTC, hannut91 commented on src/reducer.js
> +}
여기도 구조 분해 할당을 이용해서 간단하게 표현할 수 있을 것 같아요.

```js
function setRestaurants({ state, payload: { restaurants} }) {
  return {
    ...state,
    restaurants,
  };
}
```

2020-10-24 04:13 UTC, hannut91 commented on src/reducer.test.js
> +  });
결과가 동작하지 않는 다는 것은 무엇이 동작하지 않는지 이해하기 어려운 것 같아요. 이전 상태를 반환하는 것을 테스트하고 싶으셨던 거죠? 단정문도 지금 잘못된 것 같아요

2020-10-24 04:13 UTC, hannut91 commented on src/services/api.test.js
> +    });
이부분이 계속 반복되는 것 같네요. 함수로 추출해서 분리해줄 수 있을 것 같아요

```js
function mockFetch(data){
  global.fetch.mockResolvedValue({
    json: () => (data),
  });
}
```

2020-10-24 04:13 UTC, hannut91 commented on src/reducer.test.js
> +      await loadRegions()(dispatch);
비동기 액션 같은 경우에는 따로 테스트하는게 좋을 것 같아요. 

예를들어서 레스토랑 목록을 가져오는 것을 볼게요.

```js
export const loadRestaurants = () => async (dispatch, getState) => {
  const restaurants = await restaurantService.getRestaurants();
  
  dispatch(setRestaurants(restaurants));
}
```

이 비동기 액션에서 하는 일은

1. 서버에서 레스토랑 목록을 가져온다.

2. 가져온 레스토랑 목록을 setRestaurants액션을 통해 dispatch한다.

restaurantService에서 레스토랑 목록을 요청한 후 레스토랑을 업데이트 하는 setRestauarnts라는 액션을 다시 dispatch합니다. 하지만 레스토랑 목록을 어떻게 가져오는지는 주요한 관심사가 아닙니다. 그래서 getRestaurants는 mocking하여 처리하고 올바르게 가져왔다고 가정하고 액션이 올바르게 처리되는지 테스트합니다.

```js
import thunk from 'redux-thunk';

import configureStore from 'redux-mock-store';

const middlewares = [thunk];
const mockStore = configureStore(middlewares);

const restaurants = [
  { id: 1, name: '마녀주방', category: '한식', address: '강남' },
];

getRestaurants.mockResvoledValue(restaurants);

test('loadRestaurants', async () => {
  store = mockStore({});
  
  await loadRestaurants();
  
  const actions = store.getActions();
  
  expect(actions[0]).toEqual(setRestaurants(restaurants));
});
```

See also
  - https://github.com/reduxjs/redux-mock-store

2020-10-24 04:13 UTC, hannut91 commented on src/container-component/RestaurantContainer.jsx
> +    }
region과 category가 선택이 안됐을 경우에는 `null`이니까 null인지 확인하는건 어떨까요?

2020-10-24 04:13 UTC, hannut91 commented on src/container-component/RestaurantContainer.jsx
> +      dispatch(loadRestaurants({ region: name, categoryId: category }));
`id`랑 `region`이란 비교하는게 저는 조금 이해하는게 어려운 것 같아요. 이름을 좀 맞춰주면 좋을 것 같아요.

2020-10-26 13:00 UTC, hyejineee commented on src/presentational-component/Restaurants.jsx
> +        ))
네넵 수정하겠습니다!!

2020-10-26 13:03 UTC, hyejineee commented on src/reducer.test.js
> +  });
흠 단정문을 context('when dispatch undefined action) it('returns unchanged state)라고 하면 어떨까요???

2020-10-26 13:03 UTC, hyejineee commented on src/services/api.test.js
> +    });
네넵 수정하겠습니다!!

2020-10-26 13:06 UTC, hyejineee commented on src/reducer.test.js
> +      await loadRegions()(dispatch);
넵 문서 살펴보고 수정하겠습니다!!

2021-01-17 12:53 UTC, merged