week5-1 make restaurant search app
CodeSoom/react-week5-assignment-1 pull request #30
Opened 2020-10-21 07:19 UTC by JamieShin0201

안녕하세요~^^

지역정보 출력하는 부분까지 완료후 PR 보냅니다.

아직 TDD가 익숙하지 않아서 ㅠ.ㅠ 뒤죽박죽 될때가 있네요!

계속해서 과제 수행해 나가겠습니다!

감사합니다 ㅎ.ㅎ

2020-10-21 17:28 UTC, hannut91 reviewed
잘 진행중이신 것 같습니다 ㅎㅎ 먼저 단순한 케이스를 잘 구현해주셨어요. 그 다음에 이제 점점 다른 경우의 테스트를 추가하면서 기능을 만드시면 좋을 것 같습니다.

2020-10-22 09:10 UTC, JamieShin0201 commented
안녕하세요~^_^

1. 카테고리 출력되도록 구현
2. 카테고리 클릭스 체크되도록 구현
3. 지역 클릭시 체크되도록 구현

3가지 구현하였고 마지막으로 선택된 카테고리 + 지역으로 레스토랑 목록 가져오도록 구현하겠습니다.

감사합니다 ㅎㅎ

2020-10-23 00:33 UTC, hannut91 requested changes

2020-10-23 00:33 UTC, hannut91 commented on src/App.jsx
> +import CategoriesContainer from './CategoriesContainer';
컨테이너 컴포넌트 임포트들은 붙여놓는 것은 어떨까요?

2020-10-23 00:33 UTC, hannut91 commented on src/Categories.jsx
> +        const value = (id === selectedCategoryId) ? `${name}(V)` : name;
버튼에 이름을 보여주는 일과 선택됨 상태를 보여주는 것은 사실 서로 다른 일을 하고 있는거에요. 선택됨 상태를 보여주는 컴포넌트로 분리할 수도 있을거에요.

2020-10-23 00:33 UTC, hannut91 commented on src/CategoriesContainer.jsx
> +    dispatch(setSelectedCategory(categoryId));
setSelecetCategory는 너무 구현에 의존한 이름인 것 같아요. 구현이 조금만 바껴도 퍼블릭 인터페이스도 같이 바뀌게 될 것 같아요. selectCategory라는 이름읃 어떨까요

2020-10-23 00:33 UTC, hannut91 commented on src/CategoriesContainer.test.jsx
> +            id: 1,
1이 왜 1인지 이해하기 어려운 것 같아요.  categories를 이용해서 categories[0].id는 어떨까요?

2020-10-23 00:33 UTC, hannut91 commented on src/Regions.test.jsx
> +    it("appends '(V)' button text content", () => {
이것도 너무 구현에 의존한 이름인 것 같아요. 선택됨을 표시한다고 하면 어떨까요?

2020-10-23 07:09 UTC, JamieShin0201 commented
안녕하세요.^^

1. 리뷰 받은 부분 일부분 수정하였습니다.
2.  선택된 카테고리 + 지역으로 레스토랑 목록 가져오도록 구현하였습니다.
2. 선택된 상태 컴포넌트 분리는 더 생각해보고 작성하겠습니다.

2020-10-24 05:55 UTC, hannut91 requested changes

2020-10-24 05:55 UTC, hannut91 commented on src/Regions.test.jsx
> +  context('not equals selectedRegionName and button text content', () => {
context에는 with without when만 사용할 것을 권장하고 있습니다. 의미상 이해할 수 있게 잘 써주셨지만 저럳 프리픽스를 붙여주는 것도 좋을 것 같아요

See also
  - https://www.betterspecs.org/#contexts

2020-10-24 05:55 UTC, hannut91 commented on src/reducer.test.js
> +      expect(state.regions).toHaveLength(3);
왜 3인지 이해하기 어려운 것 같아요. regions의 길이로 표현해주는건 어떨까요?

2020-10-24 15:22 UTC, JamieShin0201 commented
안녕하세요 ㅎ.ㅎ 

리뷰보고 전반적으로 수정하였습니다.

actions.js 테스트와 api.js 테스트 마저 진행 해보겠습니다

감사합니다 ^_^

2020-10-25 05:19 UTC, hannut91 approved these changes
사소한 것 말고는 더 이상 커멘트 드릴게 없네요 ㅎㅎ 고생하셨어요. 과제풀이 영상을 통해 꼭 복습해보셨으면 좋겠습니다.

이번주 과제를 통해서 무엇을 배우셨나요? 다음에 더 시도해보고 싶은 것은 무엇인가요?

2020-10-25 05:19 UTC, hannut91 commented on src/Categories.test.jsx
> +  context('click category button', () => {
`context`에는 `when, with, without`만 사용할 것을 권장합니다 ㅎㅎ `when`이라는 텍스트가 빠진 것 같네요. 혹은 `describe`로 쓰는게 좋을 것 같아요

2020-10-25 05:19 UTC, hannut91 commented on src/Regions.test.jsx
> +    it("renders 'V' mark on the clicked button", () => {
V마크는 구현에 의존한 테스트인 것 같아요. V마크보다는 사실 선택된 것을 표시하는게 목적인 것 같아요. 기능이 조금만 바뀌더라도 V가 아닌 다른 마크로 바뀌거나 스타일만 바껴도 테스트 이름까지 바껴야 할 것 같아요

2021-01-17 12:53 UTC, merged