Smilee
CodeSoom/react-week5-assignment-1 pull request #31
Opened 2020-10-21 13:00 UTC by smilee

2020-10-21 16:39 UTC, hannut91 reviewed
굉장히 단순한 케이스부터 시작해서 한 단계씩 진행하고 계신 게 인상적이네요 ㅎㅎ😀

2020-10-24 15:32 UTC, smilee commented
이제 Redux Thunk를 적용할 차례입니다.

2020-10-25 05:00 UTC, hannut91 requested changes

2020-10-25 05:00 UTC, hannut91 commented on src/Button.jsx
> +      {selected ? '(V)' : null}
이렇게 써줘도 될거에요

```js
{selected && '(V)'}
```

2020-10-25 05:00 UTC, hannut91 commented on src/Button.test.jsx
> +  context('while not selected', () => {
context에서는 `with, without, when`만 쓸 것은 권장합니다.

See also
  - https://www.betterspecs.org/#contexts

2020-10-25 05:00 UTC, hannut91 commented on src/Button.test.jsx
> +  const onClick = jest.fn();
버튼이 클릭 됐을 때, 그 이벤트를 다루는 함수의 이름이니 `handleClick`이 맞을 것 같아요

2020-10-25 05:00 UTC, hannut91 commented on src/reducer.test.jsx
> +        expect(state.regions).toHaveLength(7);
왜 length가 7인지 이해하기 어려운 것 같아요. length 비교를 `regions.length`로 비교하거나 혹은

```js
expect(state.regions).toEqual(regions);
```

라고 써줘도 될 것 같아요

2020-10-25 05:00 UTC, hannut91 commented on src/reducer.test.jsx
> +        expect(state.categories).toHaveLength(7);
여기도 마찬가지로 왜 `7`인지 이해하기 어려운 것 같아요

2020-10-25 05:00 UTC, hannut91 commented on src/reducer.test.jsx
> +        expect(state.restaurants).toHaveLength(3);
여기도 마찬가지로 왜 `3`인지 이해하기 어려운 것 같아요

2020-10-25 05:00 UTC, hannut91 commented on src/RestaurantsContainer.test.jsx
> +  it('renders', () => {
여기 위에 빈 줄을 추가해서 구분해주면 좋을 것 같아요

2020-10-25 05:00 UTC, hannut91 commented on src/Restaurants.jsx
> +      }
```js
restaurants?.map(({ id, name }) => (
  <li key={id}>{name}</li>
))
```

이렇게 써줘도 올바르게 동작할까요? 아마 undefined가 나와서 어떻게 화면에 보여질지는 잘 모르겠네요

See also
  - https://ko.javascript.info/optional-chaining

2020-10-25 05:00 UTC, hannut91 commented on src/ButtonContainer.jsx
> +      selected={filter && (name === filter.regionName || id === filter.categoryId)}
버튼이 두 가지 일을 해서 이렇게 된 것 같아요. regions container와 categories container를 나누는건 어떨까요?

2020-10-25 08:59 UTC, smilee commented on src/Button.test.jsx
> +  context('while not selected', () => {
저 리스트에 `while`을 추가해도 괜찮을 것 같지만 그냥 `when`으로 바꿨습니다.

2020-10-25 09:03 UTC, smilee commented on src/Button.jsx
> +      {selected ? '(V)' : null}
적용했습니다.

2020-10-25 09:05 UTC, smilee commented on src/Button.test.jsx
> +  const onClick = jest.fn();
지금 컨테이너 컴포넌트에서 `handleClick`을 `onClick`으로 받고있는데, `handleClick`으로 받는 것이 더 좋을까요?

2020-10-25 09:27 UTC, smilee commented on src/Restaurants.jsx
> +      }
동작하네요! 전에는 따로 설정을 해줘야 했던 것 같은데.. ㅎㅎ

2020-10-25 09:51 UTC, hannut91 commented on src/Button.test.jsx
> +  const onClick = jest.fn();
컨테이에서는 onClick이란 이름으로 props를 받는게 맞고, 그 처리를 하는 함수 이름이 handleClick 입니다.

2020-10-25 10:24 UTC, smilee commented on src/Button.test.jsx
> +  const onClick = jest.fn();
다시 보고 이해했습니다!

2020-10-25 10:34 UTC, smilee commented on src/ButtonContainer.jsx
> +      selected={filter && (name === filter.regionName || id === filter.categoryId)}
그렇게 하는 것도 좋은 것 같습니다. 특히 처리하는 종류가 더 다양해지면 나누는 것이 더 좋을 것 같습니다. 😄

2021-01-17 12:53 UTC, merged