[week5-assignment-1] 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #33
Opened 2020-10-21 16:02 UTC by goodzzong

## 목표
- Redux Thunk를 이용해서 서버에서 정보를 불러와서 보여주는 앱을 작성하기

## 목표 조건
- TDD로 기능 구현
- 레스토랑 지역 목록 보기 기능
- 레스토랑 카테고리 목록 보기 기능
- 레스토랑 목록 보기 기능
- 커버리지 100% 달성

## 고민
- Red - Green - Refactoring 으로 Commit 하여 작성하려 할 때 저것을 기준으로 모든걸 지키면서 commit 을 해야할지 너무 작은 변경 파일은 좀 더 큰 단위로 묶어서 commit 해야 할 지에 대한 생각.

2020-10-22 07:34 UTC, Kihyun92 requested changes
`Red-Green-Refactoring` 사이클을 잘 진행해주셨네요~ 그리고 fixture 추가해주신것도 좋네요 :)
나머지 기능들도 차근차근 추가해보시면 좋겠습니다 :)

2020-10-22 07:34 UTC, Kihyun92 commented on src/Categories.jsx
> +            {categorie.name}
```suggestion
        {categories.map(({ id, name }) => (
          <li key={id}>
            {name}
```
이런식으로 표현하는건 어떤가요?

2020-10-22 07:34 UTC, Kihyun92 commented on src/Categories.jsx
> +    <>
하위에 ul태그만 있기 때문에 `fragment`로 감쌀 필요 없을 것 같아요~

2020-10-22 07:34 UTC, Kihyun92 commented on src/CategoriesContainer.jsx
> +    <>
이 부분도 `fragment` 제거해주세요~

2020-10-22 07:34 UTC, Kihyun92 commented on src/Regions.jsx
> +  }
단순히 인자를 받아서 props에 넘겨주는 함수같네요. `button 태그` 내에서 바로 `onClick`을 호출하는건 어떤가요?

2020-10-22 07:34 UTC, Kihyun92 commented on src/actions.js
> +}
```suggestion
export function updateRegion(region) {
  return {
    type: 'updateRegion',
    payload: {
      region,
    },
  };
}
```
`regionName`이라는 key 값을 사용하기보다 argument와 같은 `region`로 처리하는건 어떨까요?

2020-10-22 07:34 UTC, Kihyun92 commented on src/reducer.js
> +  }
if를 사용하지 않고 처리할 수 있을까요? :)

2020-10-22 13:57 UTC, goodzzong commented on src/reducer.js
> +  }
객체로 처리 하면 좀 더 괜찮아 질 것 같네요!

2020-10-22 13:58 UTC, goodzzong commented on src/Categories.jsx
> +            {categorie.name}
좀 더 명확한 것 같습니다!

2020-10-23 18:08 UTC, Kihyun92 requested changes
리뷰가 늦었네요 😭 
TDD로 구현하는데 집중해주신 것 같아 좋습니다~ 👍 
커밋 내역들을 보니 `Red-Green`에 해당하는 테스트를 작성하고 실제 구현하는 작업이 하나의 커밋에 있는 것 같아요~ 이번 과제의 의도를 고민해보시면서 가능하면 구분해서 커밋해주시면 좋을 것 같습니다~

그리고 불필요한 fragment들이 아직 존재하는 것 같아요~ 확인해주세요! ☺️

2020-10-23 18:08 UTC, Kihyun92 commented on src/Categories.test.jsx
> +    ));
`Categories` 컴포넌트를 render해주는 부분이 중복되는 것 같아요~ 한번 더 추상화하여 it 함수 밖에서 공통으로 사용하는건 어떨까요?

2020-10-23 18:08 UTC, Kihyun92 commented on src/Categories.test.jsx
> +    const handleClick = jest.fn();
handleClick을 mocking 해주는 부분도 render 함수를 추상화하면 사용될 수 있으니 보다 상위인 it함수 밖에 선언해주면 좋을 것 같아요~

2020-10-23 18:08 UTC, Kihyun92 commented on src/Regions.test.jsx
> +    ));
Regions.test도 마찬가지로 중복되는 render 함수를 보다 상위에서 선언해주면 좋겠네요~

2020-10-23 18:08 UTC, Kihyun92 commented on src/reducer.js
> +  }
if 문을 사용하지 않고 처리하려면 어떻게 해야할까요? 

`Object literal lookup`으로 처리해보면 어떨까요?
- https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

2020-10-23 18:08 UTC, Kihyun92 commented on src/reducer.test.js
> +    it('change region value', () => {
`changes regions`라고만 해도 될 것 같아요~

2020-10-23 18:08 UTC, Kihyun92 commented on src/reducer.test.js
> +      expect(state.categories).toHaveLength(5);
카테고리가 바뀌는 경우에 대해 테스트를 해주셨네요!

이때 5라는 고정된 값보다는 상태가 바뀔때마다 대응이 가능하도록 처리할 순 없을까요?

2020-10-24 03:46 UTC, goodzzong commented on src/reducer.js
> +  }
잘 읽었습니다!
감사합니다!

2020-10-24 17:34 UTC, Kihyun92 requested changes

2020-10-24 17:34 UTC, Kihyun92 commented on src/reducer.js
> +  region: '',
선택된 region이라는 의도를 명확하게 전달할 수 있는 네이밍이면 어떨까요?

2020-10-25 12:59 UTC, Kihyun92 commented
과제는 잘 진행해보셨나요? 남은 부분은 스스로 진행해보셔도 좋고, 아샬님의 강의를 보고 보완해보셔도 좋을 것 같습니다~

2020-10-26 00:29 UTC, goodzzong commented
비동기 코드를 테스트 하는 부분을 어떤식으로 해야 할지 찾아보고 이해하려 했는데 아직 부족하네요. 
 아직 덜 이해가 된 것 같습니다 ㅠ 오늘 좀 더 보완해보고 fail  나는 부분 수정하겠습니다

2021-01-17 12:53 UTC, merged