Look up restaurants
CodeSoom/react-week5-assignment-1 pull request #40
Opened 2021-02-22 05:55 UTC by HongJungKim-dev

## 02-22 회고

어려웠던점

모르는것

2021-02-22 12:04 UTC, HongJungKim-dev commented
App에서 Locations와 Categories 컴포넌트를 분리하는 과정에서 App테스트는 무엇을 할지 아직 모르겠어서 기존의 Locations와 Categories에 대한 테스트들을 통합으로 남겨뒀습니다.

2021-02-22 12:11 UTC, HongJungKim-dev commented
## 02-22 TIL

* Facts
----------

* Findings
----------
 뽀모도로 기법을 이용하니 가끔

2021-02-22 13:12 UTC, HongJungKim-dev commented
3757087a540e26af8b60c4f6abcd107efa439d28

2021-02-22 16:03 UTC, Kihyun92 requested changes
빠른 PR 너무 좋습니다 💯 

TDD cycle을 잘 지키면서 하고 계신 것 같아요 ㅎㅎ

다음 작업이 기대되네요~~

2021-02-22 16:03 UTC, Kihyun92 commented on src/Locations.jsx
> +    <div>
`div` 태그가 필요한가요? 필요없다면 제거해도 될 것 같아요~

2021-02-22 16:03 UTC, Kihyun92 commented
> [3757087](https://github.com/CodeSoom/react-week5-assignment-1/commit/3757087a540e26af8b60c4f6abcd107efa439d28)
> handleClick 구체적인 구현 안하고 test만 통과하려고 했는데 의도한 바대로 되지 않고 오류가 났습니다.

혹시 어떤 오류가 발생하나요? 스크린샷을 첨부해주시면 리뷰하는데 더 좋을 것 같아요~~

2021-02-22 16:09 UTC, Kihyun92 commented on src/Locations.test.jsx
> +    const { getByText } = render((<Locations onClick={onClick} />));
```suggestion
    const { getByText } = render((<Locations locations={locations} onClick={onClick} />));
```

locations를 넘겨줘야할 것 같아요.

테스트마다 반복되는 render 부분은 함수로 바깥에서 관리해도 좋을 것 같아요~

2021-02-22 16:43 UTC, HongJungKim-dev commented
> 혹시 어떤 오류가 발생하나요? 스크린샷을 첨부해주시면 리뷰하는데 더 좋을 것 같아요~~
에러메시지는 다음과 같습니다.
![image](https://user-images.githubusercontent.com/58525009/108739640-2f003480-7578-11eb-85f4-313a6fca8b84.png)
![image](https://user-images.githubusercontent.com/58525009/108739693-3cb5ba00-7578-11eb-8505-00a19c3b2b5e.png)

2021-02-22 16:50 UTC, Kihyun92 commented
> > 혹시 어떤 오류가 발생하나요? 스크린샷을 첨부해주시면 리뷰하는데 더 좋을 것 같아요~~
> 
> 에러메시지는 다음과 같습니다.
> ![image](https://user-images.githubusercontent.com/58525009/108739640-2f003480-7578-11eb-85f4-313a6fca8b84.png)
> ![image](https://user-images.githubusercontent.com/58525009/108739693-3cb5ba00-7578-11eb-8505-00a19c3b2b5e.png)

에러 메시지를 보니 [이 커맨트](https://github.com/CodeSoom/react-week5-assignment-1/pull/40#discussion_r580375720)와 관련 된 것 같네요~ 확인부탁드려요 😊

2021-02-23 04:19 UTC, HongJungKim-dev commented on src/Locations.jsx
> +    <div>
네 수정하겠습니다.

2021-02-23 04:21 UTC, HongJungKim-dev commented on src/Locations.test.jsx
> +    const { getByText } = render((<Locations onClick={onClick} />));
네 수정하도록 하겠습니다.

2021-02-23 09:33 UTC, HongJungKim-dev commented
이 부분이 아무값도 들어가지 않습니다. 이 부분을 '서울'이런식으로 하드코딩하면 클릭시 '서울'로 값이 변하면서 v표기로 바뀌는건 정상적으로 동작합니다. event.target.value이 부분에서 값이 제대로 안나옵니다.

2021-02-23 12:05 UTC, HongJungKim-dev commented
다양한 locations 정보들은 이후에 api에서 받아올 것이므로 임시로 다른 폴더의 파일에서 불러오는것으로 했기 때문에 이것은 state의 속성이라고 판단하지 않았습니다. 이런식으로 진행해도 되는지 궁금합니다.

2021-02-23 12:26 UTC, HongJungKim-dev commented
![Uploading image.png…]()

2021-02-23 13:12 UTC, Kihyun92 commented
> [c9e2e1b](https://github.com/CodeSoom/react-week5-assignment-1/commit/c9e2e1b07708d99e8ee66ba5b6f7758cc5be4827) 11~13줄
> 다양한 locations 정보들은 이후에 api에서 받아올 것이므로 임시로 다른 폴더의 파일에서 불러오는것으로 했습니다.
> 그래서 이러한 정보들은 state의 속성이라고 판단하지 않았습니다. 이런식으로 진행해도 되는지 궁금합니다.

fixture의 데이터를 사용했다는 말씀이시죠? 넵 추후에 API를 통해 가져올 것이기 때문에 괜찮을 것 같아요~

2021-02-23 13:18 UTC, Kihyun92 commented
> [a150515](https://github.com/CodeSoom/react-week5-assignment-1/commit/a150515619083920a2560fbbc6ddef02eac5d076)
> 이 부분이 아무값도 들어가지 않습니다. 이 부분을 '서울'이런식으로 하드코딩하면 클릭시 '서울'로 값이 변하면서 v표기로 바뀌는건 정상적으로 동작합니다. event.target.value이 부분에서 값이 제대로 안나옵니다.
> 테스트코드도 다 통과하고 오류는 뜨지 않는데 화면 출력이 '서울(V)'이런식으로 되지 않습니다.
> 
> selectedlocationname은 카멜표기법으로 작성하고자 했으나 다음과 같은 warning이 나와서 카멜표기법으로 안했습니다. 단지 waring이니 카멜표기법으로 하는게 나을까요?
> ![image](https://user-images.githubusercontent.com/58525009/108826761-0e7fbb00-7608-11eb-9cc7-fc7ea68ef613.png)

2021-02-23 13:29 UTC, Kihyun92 requested changes

2021-02-23 13:29 UTC, Kihyun92 commented on src/actions.js
> +    type: 'undateSelectedLocation',
오타가 있네요~

2021-02-23 13:29 UTC, Kihyun92 commented on src/LocationsContainer.jsx
> +  }
https://github.com/CodeSoom/react-week5-assignment-1/pull/40#issuecomment-784196654

이 커맨트 한번 참고 부탁드립니다~

2021-02-23 13:29 UTC, Kihyun92 commented on src/LocationsContainer.test.jsx
> +  useSelector.mockImplementation((selector) => selector({ locations }));
`beforeEach` 함수를 사용해서 테스트가 실행될 때마다 항상 일정한 상태에서 시작할 수 있도록 해주는게 좋을 것 같아요.

그러지 않으면 테스트가 다른 테스트들에 영향을 미칠 수 있고, 그러면 테스트가 올바르게 동작하지 않거나 유지보수하기 힘들어질 거에요.

2021-02-24 10:19 UTC, HongJungKim-dev commented
>beforeEach 함수를 사용해서 테스트가 실행될 때마다 항상 일정한 상태에서 시작할 수 있도록 해주는게 좋을 것 같아요.

>그러지 않으면 테스트가 다른 테스트들에 영향을 미칠 수 있고, 그러면 테스트가 올바르게 동작하지 않거나 유지보수하기 힘들어질 거에요.

2021-02-24 10:23 UTC, HongJungKim-dev commented
button에 value 가 없는데 event.target.value로 가져오려는 방식은 잘못된 것 같아요. 의도하지 않는 값이 넘어갈 수 있을 것 같네요.

>버튼에서 onClick을 할때 핸들러에 어떤 값을 넘겨주도록 하는건 어떤가요?
>onClick={() => handleClick(id)}

>왜 저런 경고 문구가 나왔는지 찾아보셔도 좋을 것 같네요 ㅎㅎ
에러메시지를 검색해도 잘 못찾았던것 같습니다. 검색하는 법과 알맞은 해결책을 찾는법을 더 알아봐야할것 같습니다.
해당 부분 value넘겨주기도 해보고, onClick={() => handleClick(id)} 이런식으로도 시도해보다가 어느 부분을 놓쳤는지 해결은 못했습니다. 현재 전자인 상태로 커밋에 올라가 있는 상태고 이 상태에서는 에러는 안나는데 V표기는 안되는 상태입니다.

잘 해결 못하고 시간이 꽤 걸려서 다른 부분 하고 있었습니다. 그래서 다시 시도해야할것 같습니다.

2021-02-24 12:36 UTC, HongJungKim-dev commented
a9d0149ddfe0cba514c0bd4f144879f18e8c0614
redux-thunk적용해서 App을 리팩토링하고 나서 오류가 자동으로 해결되었습니다. 어떤 오류가 왜 해결되었는지 보고 있습니다.

2021-02-24 13:52 UTC, HongJungKim-dev commented
# 02-23TIL

Facts
- 5주차 과제에서 container, redux부분을 일부 구현했습니다.

- 공부할때 뽀모도로 기법으로 공부했습니다.

- 프로그래머스 문제를 하나 풀었습니다.

Feelings
- container, redux부분을 들어가고부터 어렵과 과제하는 시간이 많이 걸리는것 같습니다.

Affirmations
- 조급해하지말고 뽀모도로 기법을 적용하여 공부합니다.

2021-02-24 13:52 UTC, HongJungKim-dev commented
# 02-24 TIL

2021-02-24 14:10 UTC, Kihyun92 commented
점점 어렵다는 느낌을 받으실 수 있지만, 이번주 다음주만 꾸준히 진행해주셔도 그 다음은 수월하게 하실 수 있을거에요 👍🏼 

그리고 문제를 고민해보고 해결해보신것 너무 좋네요 😊

슬랙 채널에 공유하는 것도 좋을 것 같아요~ 동일한 문제를 겪는 동료들이 있을 수 있고, 관련해서 더 의논을 나눠볼 수 있을테니까요 ㅎㅎ

2021-02-24 14:21 UTC, Kihyun92 requested changes
차근차근 진행해보시는게 좋습니다~ 👍🏼

2021-02-24 14:21 UTC, Kihyun92 commented on src/App.test.jsx
> +import { useDispatch, useSelector } from '../__mocks__/react-redux';
```suggestion
import { useDispatch, useSelector } from 'react-redux';
```

이미 jest.mock을 통해서 해당 모듈들은 __mocks__/react-redux에 있는 모듈들로 대체하도록 처리했기 때문에 위와 같이 임포트하는게 맞을 것 같아요~

2021-02-24 14:21 UTC, Kihyun92 commented on src/Categories.jsx
> +            selectedcategoryname={selectedcategoryname}
이 두 값이 필요한 이유가 무엇일까요?

event.target.value를 가져오기 위함이라면 `onClick={() => onClick(category.id)}`과 같이 처리해주는건 어떨까요?

2021-02-24 14:21 UTC, Kihyun92 commented on src/CategoriesContainer.jsx
> +      value={selectedcategoryname}
value에 해당 값은 왜 넘겨주는건가요? 사용하지 않고 있는 값 같아요~

2021-02-24 14:21 UTC, Kihyun92 commented on src/reducer.js
> +  }
이번 과제도 `if`나 `switch`를 사용하지 않고 해결해주세요~

2021-02-24 14:21 UTC, Kihyun92 commented on src/LocationsContainer.jsx
> +import locations from '../fixtures/locations';
App에서 location을 fetch 해준 것 같아요. 아직도 fixture에서 값을 가져와야하나요?

2021-02-25 11:58 UTC, HongJungKim-dev commented
## 미해결 오류
Categories, Locations에서 다음과 같은 오류가 납니다.
![image](https://user-images.githubusercontent.com/58525009/109150260-f648a100-77ab-11eb-91e5-094450db49b2.png)
이는 상위 컴포넌트인 CategoriesContainer, LocationsContainer에서 state.categories나 state.locations가 업데이트 되어도 undefined인 상태여서 인것 같은데 아직 해결중입니다.

reduer를 if대신에 객체로 리팩토링하는 과정에서 오류가 났는데 해결중입니다.
![image](https://user-images.githubusercontent.com/58525009/109150458-40ca1d80-77ac-11eb-9254-fb191e3fa648.png)

2021-02-25 12:50 UTC, HongJungKim-dev commented
bf1acd00b3644f883d117704632dd87fbfe30f53
3번째 줄에 props로 받지않고 fixtures로 일단 import해서 통과시켰어야 했습니다. 다음 커밋에 그런식으로 변경하였습니다.

2021-02-25 13:29 UTC, HongJungKim-dev commented
> 점점 어렵다는 느낌을 받으실 수 있지만, 이번주 다음주만 꾸준히 진행해주셔도 그 다음은 수월하게 하실 수 있을거에요 👍🏼

> 그리고 문제를 고민해보고 해결해보신것 너무 좋네요 😊

> 슬랙 채널에 공유하는 것도 좋을 것 같아요~ 동일한 문제를 겪는 동료들이 있을 수 있고, 관련해서 더 의논을 나눠볼 수 있을테니까요 ㅎㅎ

아주 어렵다고 느끼고 있지만 매일 PR하면서 꾸준히 하려고합니다. 그런데 주차마다 개념에 대한 공부와 실습을 진행하면서 나올 수 있는 질문들은 하지 못하고 과제하기에 벅차다고 느낍니다. 더 많이 생각해보고 질문하고 싶은데 따라가기 급한 느낌입니다.

2021-02-25 13:35 UTC, HongJungKim-dev commented
TDD cycle로 하려고 노력했으나 중간에 오류가 미해결된 채로 다음것으로 하게 되었습니다. 그러한 사항들은 커밋메시지에 '~시도했으나 오류를 해결해야합니다.' 이런식으로 작성하였습니다. 좀 더 고민해보고 해결해보겠습니다.

2021-02-25 15:59 UTC, Kihyun92 commented
> TDD cycle로 하려고 노력하면서도 중간에 오류가 잘 해결되지 않으면 미해결된 채로 남기고 다음것으로 하는 경우도 많았습니다. 그러한 사항들은 커밋메시지에 '~시도했으나 오류를 해결해야합니다.' 이런식으로 작성하였습니다. 좀 더 고민해보고 해결해보겠습니다.

가능하면 PR의 files changed에서 해당 라인에 커맨트를 남겨주시면 리뷰하는데 도움이 될 것 같아요 :)

2021-02-25 16:10 UTC, Kihyun92 requested changes
충분히 잘 고민하고 문제들을 해결하고 계십니다 👍🏼 

마음이 급하면 눈 앞에 있는 부분도 놓치기 쉬운 것 같아요 :) 조금 더 천천히 문제들을 처리해보는건 어떨까요?

슬랙에 공유를 해보신거 너무 좋습니다 💯

2021-02-25 16:10 UTC, Kihyun92 commented on src/Categories.jsx
> +            {category.name === selectedcategoryname ? `${selectedcategoryname}(V)` : category.name}
category.name에 상황에 따라 체크가 뒤에 붙고 안붙고가 차이나는 것 같아요~ 개선할 수 없을까요?

2021-02-25 16:10 UTC, Kihyun92 commented on src/CategoriesContainer.jsx
> +    const categoryName = event.target.value;
onClick을 통해 넘겨주는 인자가 event 객체인가요? 이 처리가 필요한지 확인해보시면 좋을 것 같습니다~

2021-02-25 16:10 UTC, Kihyun92 commented on src/Locations.jsx
> +      {locations.map((location) => (
`id`와 `name` 정보가 사용되는 것 같아요~ 구조분해할당으로 처리해보면 어떨까요?

2021-02-25 16:10 UTC, Kihyun92 commented on src/LocationsContainer.jsx
> +    selectedlocationname: state.selectedlocationname,
`selectedlocationname`을 `Lower camel case`로 표현할 수 없을까요?

(ex: `thisIsAnExample`)

2021-02-25 16:10 UTC, Kihyun92 commented on src/actions.js
> +    dispatch(setLocations(categories));
`setLocations`을 사용하는게 맞나요?

2021-02-26 03:38 UTC, HongJungKim-dev commented
> selectedlocationname을 Lower camel case로 표현할 수 없을까요?

> (ex: thisIsAnExample)

lower camel case를 적용해서 warning이 떠서 다시 적용하지 않았는데 지금 다시 해보니 해당 waring이 발생 안합니다.

2021-02-26 03:45 UTC, HongJungKim-dev commented
# Todo 정리

### 1. Categories, Locations 
Categories, Locations에서 catgories, locations 상태를 업데이트하는데 undefined가 되는것을 수정해야합니다.

### 2. reducer 리팩토링
reduer를 if대신에 객체로 리팩토링하는 과정에서 오류가 났는데 해결해야합니다.

### 3. 버튼 V표기
클릭시 V표기를 추가하는 과정을 구현했지만 제대로 작동하지 않아서 수정해야합니다.

2021-02-26 06:06 UTC, HongJungKim-dev commented
# 참고자료
actions.test
* https://yeoulcoding.tistory.com/189

2021-02-26 12:01 UTC, HongJungKim-dev commented
# 질문
1. 아래 사진이 api로부터 정보를 불러오는것을 App에서 하든, index에서 하든, 하위컴포넌트에서 하든 처음 한번 불러오는것인지 궁금합니다.
![image](https://user-images.githubusercontent.com/58525009/109297700-c5cd3980-7875-11eb-8475-39cbca2c08dd.png)
참고자료
* https://redux.js.org/tutorials/fundamentals/part-6-async-logic

Api로부터 정보들을 load하는 과정을 어느 컴포넌트에 위치할것인지

2021-02-26 12:33 UTC, HongJungKim-dev commented
405ccd9b6d1b9667950f9895c07c9cf777267791

2021-02-26 12:37 UTC, HongJungKim-dev commented
## 02-26 회고
Feelings
비동기 테스트가 아직 익숙치 않고 많이 어렵게 느껴집니다. actions테스트를 몇 줄을 하는것도 엄청나게 오래 걸렸습니다. 참고자료 이해도 아직 덜 한것 같습니다. 

Affirmations
비동기 테스트 공부 더 해서 내일은 actions와 api 테스트를 끝내고 싶습니다.

2021-02-26 15:50 UTC, Kihyun92 commented
> # 질문
> ### 1. api로부터 load시 불러오는 횟수
> 아래 사진이 api로부터 정보를 불러오는것을 App에서 하든, index에서 하든, 하위컴포넌트에서 하든 처음 한번 불러오는것인지 궁금합니다.

데이터를 fetch 하는 횟수는 상황마다 다를 것 같아요. 일반적인 상황에서는 최초 컴포넌트 랜더시 한번 가져올 것 같아요. 필요에 따라 데이터를 새로 가져와야하는 경우엔 추가적으로 호출할 수 있을거구요.

> ### 2. Api로부터 정보들을 load하는 과정을 어느 컴포넌트에 위치할것인지

이 또한 유동적으로 필요한 곳에서 할 것 같아요. 다만, 중요한건 load를 처리하는 컴포넌트가 불필요하게 리렌더링 되지 않는다는 조건이 붙을 것 같아요.

이번 과제를 예시로 들면 카테고리 컨테이너에서 load를 처리해도 상관없습니다. 불필요하게 렌더링만 이루어지지 않는다면요.

이건 리액트에서 랜더링을 처리하는 경우에 대해 봐보면 좋을 것 같아요 ㅎㅎ
- https://medium.com/vingle-tech-blog/react-%EB%A0%8C%EB%8D%94%EB%A7%81-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-f255d6569849

혹시 잘못됐거나 더 의논이 필요한 부분이 있다면 편하게 말씀주세요~

2021-02-26 15:55 UTC, Kihyun92 commented
> ## 미해결 오류
> [405ccd9](https://github.com/CodeSoom/react-week5-assignment-1/commit/405ccd9b6d1b9667950f9895c07c9cf777267791) actions.test.jsx 21줄
> 
> mockResolvedValue가 is not a function 오류가 나서 해결을 못했습니다.
> fetchLocationsMock자체를 가짜함수가 아닌 fetchLocations를 불러와서 fetchLocations.mockResolvedValue로 해봤는데도 동일한 오류가 납니다.
> 그런데 테스트코드이기에 가짜함수인 fetchLocationsMock로 해야하는것이 맞다고 생각하는데 틀린것인지 모르겠습니다.
> ![image](https://user-images.githubusercontent.com/58525009/109299886-20b46000-7879-11eb-85ec-fca0028f9b13.png)
> 
> 해당 오류에 대해 검색해서 찾아봤지만 아직 공부가 덜 되어서 그런지 적용할만한 것은 찾기 힘들었습니다. 자료도 충분하게 나오지 않았습니다. 아래는 cannot read property 'mockResolvedValue' of undefined 에러메시지여서 조금 다른 경우인것 같습니다.
> https://stackoverflow.com/questions/61627298/jest-mockresolvedvalue-is-not-a-function

api를 mocking 해주셨네요. 그런데 호출하는 함수가 잘못된것같아요.

/services/__mocks__/api 에는 fetchLocationsMock이 아닌 fetchLocations가 들어있는 것 같습니다.

```javascript
import { fetchLocations } from './services/api';

jest.mock('./services/api');
```

이렇게 mocking 해보시겠어요?

2021-02-26 16:10 UTC, Kihyun92 requested changes
고민을 많이 해보면서 동료들과 고민을 나누는 모습이 너무 좋습니다 👍🏼 

시간을 투자해서 고민하고 문제를 해결하는게 저는 오히려 도움이 될거라고 생각해요.

개인적으로 `TDD: By Example`의 책에서 감명 깊게 본 문구가 있습니다. 물론 TDD 관련된 얘기지만, 저도 삽질을 많이 하면서 개발을 해왔어서 그런지 제 관점에서 생각해서 와닿더라구요 ㅎㅎ

`코드가 가르쳐주는 모든 교훈을 학습할 기회를 갖게 된다. 처음 생각나는대로 후딱 완료해버리면 두번째 것, 더 나은 것에 대해 생각할 기회를 잃게 된다.`

홍중님이 문제를 해결하려고 그만큼 많이 찾아보고 고민하는 과정이 결국 도움이 될거에요. 화이팅입니다 😊

2021-02-26 16:10 UTC, Kihyun92 commented on src/components/App.jsx
> +  }
locationName && categoryName 인 경우에 loadRestaurants을 dispatch 해주셨네요! 예외처리는 useEffect 내부에서 처리해주는게 좋습니다.

```suggestion
    useEffect(() => {
      if (locationName && categoryName) {
        dispatch(loadRestaurants(locationName, categoryName));
      }
    }, [locationName, categoryName]);
```

그리고 결국 지역과 카테고리를 선택한 경우에 레스토랑 정보를 불러오면 될 것 같아요. `loadRestaurants`을 `dispatch` 해주는 위치가 이곳이 좋을까요?

2021-02-26 16:10 UTC, Kihyun92 commented on src/components/Categories.jsx
> +            onClick={() => onClick(name)}
name은 변할 수 있는 값일 것 같아요. DB에서 변하지 않음을 보장하는 id를 넘기는건 어떨까요?

2021-02-26 16:10 UTC, Kihyun92 commented on src/components/Restaurants.jsx
> +      {restaurants.map(({ id, name }) => (<li key={id}>{name}</li>))}
map 콜백 내부의 li 태그의 처리하는 부분은 줄을 바꿔서 처리를 해주는게 좋을 것 같아요~

2021-02-27 12:04 UTC, HongJungKim-dev commented
![image](https://user-images.githubusercontent.com/58525009/109386635-486dfb80-793f-11eb-898b-422447118039.png)
App과 reducer에서 오류 처리하고 코드리뷰 주신것중에 categories에서 id로 받는것, load하는 과정 위치 등을 수정해야합니다.

2021-02-27 12:16 UTC, HongJungKim-dev commented
https://github.com/CodeSoom/react-week5-assignment-1/pull/40#discussion_r583741632

2021-02-27 15:34 UTC, Kihyun92 commented
> [#40 (comment)](https://github.com/CodeSoom/react-week5-assignment-1/pull/40#discussion_r583741632)
> 
> > 그리고 결국 지역과 카테고리를 선택한 경우에 레스토랑 정보를 불러오면 될 것 같아요. loadRestaurants을 dispatch 해주는 위치가 이곳이 좋을까요?
> 
> loadRestaurants를 dispatch하는 과정이 App이 아닌 다른 컴포넌트에 있어야한다는 말씀인가요?

App 컴포넌트에서 선택한 값들의 변경 유무에 따라 dispatch 해주는 것 보다, `결국 지역과 카테고리를 선택한 경우에 레스토랑 정보를 불러오면 될 것 같아요` 이 관점에서 더 나은 위치가 어딜지 생각해서 커맨트 드렸던 것 같아요 :)

2021-02-27 15:52 UTC, Kihyun92 requested changes

2021-02-27 15:52 UTC, Kihyun92 commented on src/containers/LocationsContainer.jsx
> +      value={selectedLocationName}
value 로 넘기고 있는것 같아요

2021-02-28 14:42 UTC, Kihyun92 approved these changes
쉽지 않은 과제였는데 고생하셨습니다~

강의 풀이 영상 보시면 좋을 것 같아요~

해결하지 못한 문제들은 시간이 되신다면 해결해보셔도 좋을 것 같습니다 :)

2021-03-03 15:56 UTC, merged