전국 식당찾아보기!
CodeSoom/react-week5-assignment-1 pull request #43
Opened 2021-02-22 11:38 UTC by shinhyogeun

처음에 App을 중심으로 필요한 component들을 만날 때마다 component를 TDD로 만들었습니다. 
그래서 일단은 지역 리스트를 만드는 것부터 시작하였습니다. 
**필요한 컴포넌트 -> 그 컨테이너 -> 그 부분의 reducer구현** 이런 식으로 진행하려고합니다!
그런데 지금 fetch를 이용하여 데이터를 가져오는 것을 하였는데 App.test에서 api mock이 없어도 test가 깨지지 않습니다..
강의에서는 깨져서 목킹을 해주는 것을 보았지만 저는 깨지지가 않습니다.
혹시 몰라서 서버를 돌려서 잠깐 확인해봤을때는 정상적으로 불러옵니다..😭 
이 이유에 대해서 찾아보는데 시간이 되어서 일단은 PR을 보냅니다!😭
감사합니다😊

2021-02-22 16:27 UTC, Kihyun92 requested changes
빠르게 풀리퀘스트를 만들어 주셨군요 💯 

커밋 메시지를 보니 `TDD cycle`을 잘 지키며 진행해주시고 계신 것 같습니다 ㅎㅎ

이번주도 화이팅입니다~ 😊

2021-02-22 16:27 UTC, Kihyun92 commented on src/RegionListContainer.jsx
> +    return dispatch(changeSelectedRegion(Number(event.target.name)));
number로 형변환하여 처리하고 있군요! 형변환 없이 해결할 수 없을까요?

2021-02-22 16:27 UTC, Kihyun92 commented on src/RegionList.jsx
> +export default function RegionList({ regions, selectedRegionID, onClick }) {
List는 많은 의미로 유추가 가능한 것 같아요. `Regions`라는 컴포넌트 네이밍은 어떤가요?

2021-02-22 16:27 UTC, Kihyun92 commented on src/reducer.js
> +  }
이전 과제들과 마찬가지로 `if`나 `switch`를 사용하지 않고 해결할 수 있을까요?

2021-02-22 16:27 UTC, Kihyun92 commented on src/reducer.test.js
> +  const preveState = {
이전 상태값을 의미하는 것 같아요.

> 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.

과제 제한 조건을 지키면서 한번 해보시면 좋을 것 같아요~

이 경우에는 `preventState`나 `initialState`와 같은 네이밍은 어떤가요?

2021-02-22 16:36 UTC, Kihyun92 commented
> 그런데 지금 fetch를 이용하여 데이터를 가져오는 것을 하였는데 App.test에서 api mock이 없어도 test가 깨지지 않습니다..
강의에서는 깨져서 목킹을 해주는 것을 보았지만 저는 깨지지가 않습니다.

강의 영상 19분 정도에 처리하는 부분을 말씀하시는건가요? 지금은 redux-thunk를 사용해서 처리를 해두셔서 상황이 달라진 것 같은데 맞나요? ㅎㅎ 한번 확인해보시고 말씀주세요 :)

2021-02-23 04:22 UTC, shinhyogeun commented on src/RegionListContainer.jsx
> +    return dispatch(changeSelectedRegion(Number(event.target.name)));
id를 그냥 직접받으면 되는 건데 왜이럴까요 저.. 하하..😭

2021-02-23 04:22 UTC, shinhyogeun commented on src/RegionList.jsx
> +export default function RegionList({ regions, selectedRegionID, onClick }) {
넵 바꾸겠습니다!

2021-02-23 04:45 UTC, shinhyogeun commented on src/reducer.js
> +  }
저번에 계산기 만들던 과제처럼 바꿔봤습니다.🤔

2021-02-23 04:45 UTC, shinhyogeun commented on src/reducer.test.js
> +  const preveState = {
preventState로 변경하였습니다!

2021-02-23 08:07 UTC, shinhyogeun commented
오늘은 Categories에 대해서 만들어 보았습니다. 만들기 시작하자마자 Categories와 Regions가 목록안에 버튼이 있는 것과 그 때 일어날 일이 너무 같아서 하나의 Buttons로 만들어 보았습니다.

분리를 해서 Buttons와 CategoriesContainer와 RegionsContainer를 만들었습니다. (각각의 Container는 Buttons를 그립니다.)

2021-02-23 13:51 UTC, Kihyun92 requested changes
리뷰 드린것 보다 더 잘 반영해주신 것 같아요! 👍🏼

2021-02-23 13:51 UTC, Kihyun92 commented on src/App.test.jsx
> +  beforeEach(() => { jest.clearAllMocks(); });
줄바꿈 처리를 하거나 한줄로 사용하려면 아래와 같이해줘도 되지 않을까요?
```suggestion
  beforeEach(() => jest.clearAllMocks() );
```

2021-02-23 13:51 UTC, Kihyun92 commented on src/Buttons.test.jsx
> +  function renderList(list, ID) {
`ID`라고 대문자로 한 이유가 있나요? `id` 라고만 해줘도 될 것 같네요~

2021-02-23 13:51 UTC, Kihyun92 commented on src/Buttons.test.jsx
> +  it('선택된 지역은 (V)를 같이 보여준다.', () => {
`선택된 음식`이 맞을 것 같습니다

2021-02-23 13:51 UTC, Kihyun92 commented on src/App.test.jsx
> +    selectedRegionID: 0,
전반적으로 `selectID`와 같이 표현하셨네요~`selectId`와 같이 형식을 맞춰주는게 좋을 것 같아요.

2021-02-23 14:03 UTC, Kihyun92 requested changes
리뷰 드린것 것보다 더 잘 반영해주신 것 같아요 👍🏼

2021-02-23 14:09 UTC, Kihyun92 commented
> 오늘은 Categories에 대해서 만들어 보았습니다. 만들기 시작하자마자 Categories와 Regions가 목록안에 버튼이 있는 것과 그 때 일어날 일이 너
> 
> 무 같아서 하나의 Buttons로 만들어 보았습니다.
> 
> 분리를 해서 Buttons와 CategoriesContainer와 RegionsContainer를 만들었습니다. (각각의 Container는 Buttons를 그립니다.)
> 
> 그리고 react 슬랙에도 올렸지만 제가 정말 기본적인 부분을 놓치고 있는 것 같아서 여기서도 올려봅니다.
> 
> > 강의 영상 19분 정도에 처리하는 부분을 말씀하시는건가요? 지금은 redux-thunk를 사용해서 처리를 해두셔서 상황이 달라진 것 같은데 맞나요? ㅎㅎ 한번 확인해보시고 말씀주세요 :)
> 
> 강의를 보고 redux-thunk를 사용하지 않고 App test를 돌리면 fetch를 모른다고 합니다!
> 
> **fetch는 자바스크립트 기본 함수인데 왜 모른다고하지..?**
> 
> 그 이유를 찾아보니 Node에서 실행되는 test는 fetch라는 함수를 모른다는 이유라고 합니다.(fetch는 브라우저환경에서만 아는 함수라고 하네요)
> 
> 그러면 왜..? redux-thunk를 사용할때는 fetch를 모른다는 오류가 뜨지 않을까요?
> 
> **제 test가 단순히 dispatch가 실행됬는지 안됬는지만을 테스트해서 그럴까요?**
> 
> 그런데 그렇다고 해도 redux-thunk를 사용한다고 해도 그 안에 함수로 들어가면 결국 fetch를 사용하는데요..ㅠㅠ
> 
> 제가 잘못 이해하는 부분을 힌트라도 주시면 감사하겠습니다 ㅠㅠ😭😭😭

redux-thunk를 사용해서 fetch를 모른다는 오류가 뜨지 않는 걸까요?

redux-thunk를 적용하면서 App 컴포넌트에서 구조가 바뀌었죠.

``` javascript
// before
 useEffect(() => {
    loadRegions({ dispatch });
  }, []);

// after
useEffect(() => {
     dispatch(loadRegions());
  }, []);
```

바뀐 코드는 dispatch에 loadRegions를 넘겨주고 있어요. 이때 App.test.js에서는 dispatch를 mocking 해주고 있는 상황이라 무시되는게 아닐까요?

잘못된 부분이 있다면 편하게 말씀주세요! 😊

2021-02-24 09:20 UTC, shinhyogeun commented
.. actions와 api파일을 test코드 작성한다는 것을 몰랐습니다.. 커버리지를 돌리고 나서야 깨달았습니다...ㅠㅠㅠㅠㅠㅠ 

e2e까지는 모두 통과하는데 api, actions작성을 TDD로 하지 않았다는 것이 맘에 걸리네요 ㅠㅠ

내일부터 api와 actions작성을 원래 파일이 없다는 생각으로 다 TDD로 구현해보려고 합니다.

또한 파일정리도 필요해 보입니다🤔

2021-02-24 13:43 UTC, Kihyun92 commented
> 질문이 있습니다!
> 
> **1. useEffect을 테스트할 방법이 있을까요?**
> 
> 테스트를 통과했지만 실행시 실패했습니다. 그 이유는 `useEffect(( ) => { }, [ 👆 ])`** 에서 👆부분에 넣지 않아서 그랬었습니다.
> 
> 저👆부분에 넣어야지 상태가 업데이트 될 때 useEffect가 실행된다고 합니다. 그런데 저 부분을 **왜 test에서 잡지 못했을까**를 생각해보았고
> 
> 어떻게 test를 할 수 있을까를 생각해봤었습니다.. 그런데 방법이 떠오르지 않았습니다. 👆부분을 테스트 하려면 컴포넌트가 변화하는 상태를 지켜보
> 
> 면서 해야할 것같은데 이것은 e2e테스트가 아니면 test가 가능하지 않을까요??
> 
> 감사합니다😊😊😊

간단하게 말해서 일단 `useEffect`의 두번째 인자에 어떤 값을 넣어야하는건 아닙니다.

넣어야 하는 상황에 넣어주는 거에요. 빈 배열로 설정할 경우, 최초 렌더링시에만 첫번째 인자로 넘긴 콜백 함수가 실행됩니다.

빈배열이 아닌 값을 넣어준 경우엔 말씀하신대로 해당 상태가 업데이트될때마다 콜백 함수가 실행되는 거구요.

혹시 잘못된 부분있다면 언제든 말씀주셔요~~

참고
- https://ko.reactjs.org/docs/hooks-effect.html

2021-02-24 13:58 UTC, Kihyun92 requested changes
많은 고민을 해보면서 과제를 해보시는 것 같아요 😊

그리고 `given2`를 사용해보셨군요~ 👍🏼

2021-02-24 13:58 UTC, Kihyun92 commented on src/App.jsx
> +import RestaurantsContainer from './RestaurantsContainer';
컴포넌트 모듈들이라 사이에 공백은 없어도 될 것 같네요 :)

2021-02-24 13:58 UTC, Kihyun92 commented on src/Buttons.jsx
> +            {id === selectedId ? `${name}(V)` : name}
name은 항상 노출되는 정보같아요~

뒤쪽에 추가되는 부분만 예외처리해주는건 어떨까요?

2021-02-24 13:58 UTC, Kihyun92 commented on src/Buttons.test.jsx
> +    expect(handleClick).toBeCalled();
`mocking`한 `click event`에 대해서 테스트를 해주고 있네요.  다만 이 경우에 올바르게 테스트 됐다고 보장할 수 있을까요?

`beforeEach`함수를 사용해서 테스트가 실행될 때마다 항상 일정한 상태에서 시작할 수 있도록 해주는게 좋을 것 같아요.
그러지 않으면 테스트가 다른 테스트들에 영향을 미칠 수 있고, 그러면 테스트가 올바르게 동작하지 않거나 유지보수하기 힘들어질 거에요.

2021-02-24 13:58 UTC, Kihyun92 commented on src/actions.js
> +      .join('');
동일한 id인지를 체크하는 부분같아요~ 

이 부분을 action에서 가져가는게 맞을지, 아니면 reducer나 다른 곳에서 처리해주는게 좋을지 관심사 측면에서 한번 고민해보시면 좋을 것 같아요~ ☺️

2021-02-25 04:13 UTC, shinhyogeun commented on src/actions.js
> +      .join('');
제가 id체크를 actions에서 한 이유는 getState함수를 사용할 수 있다는 것을 구글링하면서 찾아서 그랬습니다~!

저 id체크 과정 자체가 있어야하는지 생각을 해보았고 
```
const initialState = {
  selectedRegion: {id: 1, name : '서울' },
  selectedCategory: {id : 1, name : '한식' },
  regions: [],
  categories: [],
  restaurants: [],
};
```
initialState에서 상태를 위에서처럼 `selectedRegionId -> selectedRegion`, `selectedCategoryId -> selectedCategory`으로 

객체를 통으로 설정해서 위의 과정을 없엤습니다!

그런데 저 위의 **동일한 id인지 체크하는 부분**을 없에지 않는다면 제가 적었던 저 자리가 괜찮지 않나요? **동일한 id인지 체크하는 부분**도 getState함수를 이용해서 기존 정보를 가져와 체크할 수도 있어서 크게 어색해보이지는 않는데 어떻게 생각하시나요?🤔 저기 자리에는 비동기 관련 함수들만 와야 되는 걸까요?🤔

2021-02-25 04:14 UTC, shinhyogeun commented on src/Buttons.test.jsx
> +    expect(handleClick).toBeCalled();
그렇네요! 통과시키기 바빠서 놓쳤습니다.. 바로 반영하겠습니다!

2021-02-25 04:14 UTC, shinhyogeun commented on src/Buttons.jsx
> +            {id === selectedId ? `${name}(V)` : name}
`{name}
  {id === selectedId ? '(V)' : ''}`
다음처럼 바꿨습니다!

2021-02-25 04:15 UTC, shinhyogeun commented on src/App.jsx
> +import RestaurantsContainer from './RestaurantsContainer';
반영하겠습니다~!

2021-02-25 11:55 UTC, shinhyogeun commented
1. restaurants를 보여주는 container에서 selectedRegion혹은 selectedCategory가 변하면 새로 정보를 가져와야하기 때문에  useEffect의 

2번째 인자에 [selectedRegion, selectedCategory] 이렇게 넣어습니다! 이 부분이 없어도 실패하는 test는 없습니다. 있어도 실패하는 test는 없

습니다. 그런데 [selectedRegion, selectedCategory] 이 부분이 없으면 프로그램을 시작하고 각각을 클릭을 해도 정보를 불러오지 않습니다.

 **테스트는 모두 통과해도 실제로 작동이 제대로 되지 않아서 이 부분은 test를 어떻게 할 수 있을까?** 여쭤봤던 것입니다! useEffect가 예정대로 

잘 작동하는지 test하려면 state가 변하고 그 변한 state를 바탕으로 또 다시 그려지는 과정을 test해야하는 것 같아서 e2e test로 검증할 수 있는지 

궁금합니다! (실패가 없어서 첨부드릴 스크린샷이 없습니다..ㅠㅠ)  😭


2. actions.test.js에서 테스트를 할 때 
![스크린샷 2021-02-25 오후 8 52 15](https://user-images.githubusercontent.com/52554235/109149754-5a1e9a00-77ab-11eb-966e-bd9afccfcffe.png)

저기에 async와 await를 써야 test가 통과가 되는데 그 이유가 궁금합니다! 제가 async/await가 필요 없다고 생각하는 이유는 비동기는 

loadRegions안에 있는 fetchRegions를 실행할때 일어나지만 저희가 그 함수를 mocking 했으므로 저 함수는 test할 때 더이상 비동기로 작동하

지 않는다고 생각해서 그랬습니다.

2021-02-25 16:30 UTC, Kihyun92 commented on src/actions.js
> +      .join('');
맞아요 어색하진 않습니다. 개인적으로는 관심사 측면에서 봤을때 액션에서는 단순히 어떤 처리를 할지에 대한 액션만 발생하고, 이제 reducer에서 동일한 id 인지 체크하여 상태를 변경하는게 조금 더 자연스러운 플로우가 아닌가 싶어요. 😊

- https://redux.js.org/understanding/thinking-in-redux/glossary#action

2021-02-25 16:51 UTC, Kihyun92 commented
> 오늘은 비동기때문에 정보를 찾느라 거의 다 시간을 보냈네요 🧐
> 
> actions에 test를 작성하는 것을 위주로 해보려고 했습니다!
> 
> 질문에 답변해주시면 감사하겠습니다~😊
> 
> 1. restaurants를 보여주는 container에서 selectedRegion혹은 selectedCategory가 변하면 새로 정보를 가져와야하기 때문에  useEffect의
> 
> 2번째 인자에 [selectedRegion, selectedCategory] 이렇게 넣어습니다! 이 부분이 없어도 실패하는 test는 없습니다. 있어도 실패하는 test는 없
> 
> 습니다. 그런데 [selectedRegion, selectedCategory] 이 부분이 없으면 프로그램을 시작하고 각각을 클릭을 해도 정보를 불러오지 않습니다.
> 
> **테스트는 모두 통과해도 실제로 작동이 제대로 되지 않아서 이 부분은 test를 어떻게 할 수 있을까?** 여쭤봤던 것입니다! useEffect가 예정대로
> 
> 잘 작동하는지 test하려면 state가 변하고 그 변한 state를 바탕으로 또 다시 그려지는 과정을 test해야하는 것 같아서 e2e test로 검증할 수 있는지
> 
> 궁금합니다! (실패가 없어서 첨부드릴 스크린샷이 없습니다..ㅠㅠ) 😭

선택한 값들이 변경될 때 `useEffect`가 호출되는건 우리가 테스트 할 필요 있을까요? 어떤 의미가 있을까요? 

저라면 `useEffect`에서 실행되는 로직에 대해서만 테스트하고, 말씀하신 부분은 E2E 테스트로 확인해볼 것 같아요 :)

> 2. actions.test.js에서 테스트를 할 때
>    ![스크린샷 2021-02-25 오후 8 52 15](https://user-images.githubusercontent.com/52554235/109149754-5a1e9a00-77ab-11eb-966e-bd9afccfcffe.png)
> 
> 저기에 async와 await를 써야 test가 통과가 되는데 그 이유가 궁금합니다! 제가 async/await가 필요 없다고 생각하는 이유는 비동기는
> 
> loadRegions안에 있는 fetchRegions를 실행할때 일어나지만 저희가 그 함수를 mocking 했으므로 저 함수는 test할 때 더이상 비동기로 작동하
> 
> 지 않는다고 생각해서 그랬습니다.

`mockResolvedValue`를 사용해서 일 것 같아요.
- https://jestjs.io/docs/en/mock-function-api#mockfnmockresolvedvaluevalue

2021-02-25 17:00 UTC, Kihyun92 requested changes
잘 진행해주고 계셔서 리뷰 드릴 내용을 찾기 쉽지 않네요 😅

고민하시는 내용들에 대해서 바로바로 슬랙 채널을 통해서 동료들에게 공유해보는 것도 좋을 것 같습니다 :)

같은 고민을 하는 동료들이있을 수 있고, 의논을 통해 더 나은 방법을 찾을 수 있을 것 같아요 ㅎㅎ

물론 저희들한테 DM 으로 문의주셔도 좋습니다 :)

2021-02-25 17:00 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +  }, [region, category]);
loadRestaurants에 대한 처리가 이곳에 있는게 좋을까요?

이 컴포넌트에서는 단순히 스토어의 레스토랑 정보만 가져오도록 처리할 수 없을까요? 🤔

2021-02-26 06:13 UTC, shinhyogeun commented on src/RestaurantsContainer.jsx
> +  }, [region, category]);
이것을 App으로 올리는 것을 말씀하시는 것같군요! 넵 바꾸겠습니다! 

저는 Container라는 것이 redux와 직접 소통할 수 있는 단위라고 생각해서 useEffect를 Container단으로 내려서 처리하려고 해보았습니

다!  **Container단에서도 dispatch를 사용해서 상태를 변경할 수 있는데 **useEffect는 여기 있어서 어색할 이유가 있나요?🤔**

2021-02-26 10:58 UTC, shinhyogeun commented
비동기 테스트가 어렵네요..ㅠㅠ 어렵다기보다 Promise를 반환하는 것에서 이해가 깊게 안되서 공부해보려고 합니다!

관련 좋은 영상을 봐야겠어요!

남은 주말에는 리팩토링을 하면서 비동기 테스트를 더 자세히 알아봐야할 것같습니다! 👍😊

2021-02-26 10:59 UTC, shinhyogeun commented on src/actions.js
> +      .join('');
그렇네요.. 오.. reducer가 처리하는 것이 더 자연스럽네요.. 감사합니다!

2021-02-26 14:53 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +  }, [region, category]);
App 에서 처리하는것도 좋지요. 하지만 결국 지역과 카테고리를 클릭할때 load 하면되지 않을까요?  관련된 핸들러에서 처리해줘도 좋을 것 같군요 :)

2021-02-26 15:02 UTC, Kihyun92 approved these changes
많은 고민을 해봐주셔서 리뷰하는데 좋았던 것 같아요 👍🏼 

이번 과제는 approve 하겠습니다. 리팩터링은 계속 진행해보시면 좋을 것 같네요 :)

오늘 자정~ 내일 올라올 과제 풀이 영상 꼭 보시면 좋을 것 같습니다 😊

2021-02-26 15:02 UTC, Kihyun92 commented on src/App.test.jsx
> +    it('지역과 category에 맞는 정보를 보여주는 dispatch함수가 실행된다.', () => {
사이에 공백을 추가해줘도 좋겠네요 :)

2021-02-26 15:02 UTC, Kihyun92 commented on src/actions.js
> +  return async (dispatch) => {
레스토랑 정보를 가져올때, `regionName, categoryId`값을 인자로 넘겨받아 처리해주셨어요~

`redux-thunk`의 `getState`를 사용해서 처리해줄 수는 없을까요?

2021-02-27 03:52 UTC, shinhyogeun commented on src/RestaurantsContainer.jsx
> +  }, [region, category]);
오.. 그런데 그러면 '서울'을 계속 누를때마다 정보를 불러오는 것 아닌가요? 

만약 지역과 카테고리를 클릭할 때 load하면 '서울', '한식'상황에서 서울을 계속 누르면 정보는 변함이 없는데 계속 load되는 것 아닌가요? 

내용이 바뀔 때 불러오는 것을 선호해서 useEffect를 사용하려고 했었는데 어떤가요?!🤔

2021-02-27 03:52 UTC, shinhyogeun commented on src/App.test.jsx
> +    it('지역과 category에 맞는 정보를 보여주는 dispatch함수가 실행된다.', () => {
넵 알겠습니다!😊

2021-02-27 04:06 UTC, shinhyogeun commented on src/actions.js
> +  return async (dispatch) => {
정말이네요..와..👍넵 수정하겟습니다!!

2021-02-28 08:38 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +  }, [region, category]);
물론 어느정도 예외처리는 해줘야겠죠? ㅎㅎ 이전값과 다른 경우에만 호출하는 방식으로요. 

지역이나 카테고리 버튼을 누르면 레스토랑 정보를 로드해온다라는 일종의 비지니스 로직에 대한 관심사를 어디에 둘지 측면에서 커맨트 드렸었습니다~

이걸 App 에서 변경 여부를 관리해서 로드하는게 좋을지 아니면 사용하는 쪽에서 클릭이 있으면 로드하는게 좋을지의 차이아닐까요? ㅎㅎ

2021-02-28 14:45 UTC, merged