식당 조회하기 🥘  🍙
CodeSoom/react-week5-assignment-1 pull request #44
Opened 2021-02-22 11:44 UTC by SangHoonly

2021-02-22 16:38 UTC, Kihyun92 commented
풀리퀘스트의 메시지를 적어주세요~ 동료들이 보고 이해할 수 있도록 간단하게 무엇을 했는지와 같은 내용이면 좋습니다. :)

2021-02-22 16:42 UTC, Kihyun92 requested changes
빠른 PR 너무 좋습니다 👍🏼 

커밋 내용을 보니 `TDD cycle`을 잘 지키며 작업해보신 것 같아요 :)

다음 작업 기다리겠습니다~ 😊

2021-02-22 16:42 UTC, Kihyun92 commented on src/Regions.jsx
> +    <div>
`div` 태그가 필요한가요? 필요 없다면 제거해도 좋을 것 같아요~

2021-02-22 16:42 UTC, Kihyun92 commented on src/RegionsContainer.jsx
> +  // JSON데이터 불러와서 regions에 반영하기
일단 `const regions = []`라도 해두는게 좋겠군요 ㅎㅎ

2021-02-24 12:19 UTC, SangHoonly commented
왜 dispatch가 안불려지는지 잘 모르겠네요 흠...

![스크린샷 2021-02-24 오후 9 18 48](https://user-images.githubusercontent.com/54464320/108999641-ebc3d400-76e5-11eb-9e7d-e32104445edc.png)

2021-02-24 13:34 UTC, Kihyun92 commented
> 왜 dispatch가 안불려지는지 잘 모르겠네요 흠...

loadRegions 함수에 dispatch를 넘겨주고 있네요. 그런데 loadRegions는 비동기함수에요.

테스트에서 비동기처리가 되지 않았기 때문에 넘겨준 dispatch가 아직 호출되지 않았다고 나오는 것 같아요~

waitFor 관련 문서를 참고해보시면 좋겠네요~
- https://testing-library.com/docs/dom-testing-library/api-async/#waitfor

2021-02-24 13:38 UTC, Kihyun92 requested changes

2021-02-24 13:38 UTC, Kihyun92 commented on src/App.jsx
> +}
이 부분도 actions 파일에서 관리하는건 어떨까요? 🤔

2021-02-24 13:38 UTC, Kihyun92 commented on src/Regions.jsx
> +        </li>
구조분해할당으로 처리해주는 것도 좋겠네요~

2021-02-24 13:38 UTC, Kihyun92 commented on src/RegionsContainer.jsx
> +  console.log(regions);
불필요한 콘솔은 제거해서 푸시해주세요~

2021-02-24 13:38 UTC, Kihyun92 commented on src/store.jsx
> +  }
이번 과제도 `if`나 `switch`를 사용하지 않고 해결해주세요~ 😊

2021-02-25 11:55 UTC, SangHoonly commented
와 어렵네요... restaurants 데이터를 언제 가져와야 하는지(지역 버튼과 카테코리 버튼을 클릭하였을 시 혹은 리렌더링됬을때 곧바로)지도 감이 안잡히고, 없는 데이터를 get 했을시 생기는 오류 처리또한 어떻게 해야하는지도 감이 안잡히네요...

2021-02-25 11:56 UTC, SangHoonly commented on src/store.jsx
> +  }
넵 추후 리펙토링 단계에서 한번에 수정하도록 하겠습니다!

2021-02-25 12:40 UTC, SangHoonly commented
이렇게 없는 url에서 뜨는 GET 요청 오류는 try error구문으로 잡히지 않던데, 다른 해결방안이 또 있을까요????
![스크린샷 2021-02-25 오후 9 38 36](https://user-images.githubusercontent.com/54464320/109154585-d74d0d80-77b1-11eb-8e7e-3bdd530de31a.png)

2021-02-25 17:03 UTC, Kihyun92 commented
> 와 어렵네요... restaurants 데이터를 언제 가져와야 하는지(지역 버튼과 카테코리 버튼을 클릭하였을 시 혹은 리렌더링됬을때 곧바로)지도 감이 안잡히고, 없는 데이터를 get 했을시 생기는 오류 처리또한 어떻게 해야하는지도 감이 안잡히네요...

조금 단순하지만, 필요할 때 가져오면 됩니다. 언제 restaurants 데이터가 필요한가요? 클릭이 이루어진 이후가 아닐까요? 🤔

2021-02-25 17:04 UTC, Kihyun92 commented
> 이렇게 없는 url에서 뜨는 GET 요청 오류는 try error구문으로 잡히지 않던데, 다른 해결방안이 또 있을까요????
> ![스크린샷 2021-02-25 오후 9 38 36](https://user-images.githubusercontent.com/54464320/109154585-d74d0d80-77b1-11eb-8e7e-3bdd530de31a.png)

요청시에 값이 없다면 요청하지 않도록 처리하는건 어떤가요?

2021-02-25 17:06 UTC, SangHoonly commented
앗...리뷰중이셨군요... 임시적으로 구현은 하였습니다만 테스트케이스 작성을 못해가지고...ㅋㅋㅋ useEffect 두번째 인자값을 사용하여 업데이트 될 시 restaurants를 불러오도록 처리해보았습니다!

2021-02-25 17:16 UTC, Kihyun92 requested changes
ㅎㅎ 안그래도 useEffect를 사용해서 처리해보는게 좋을 것 같다고 커맨트를 남기고 있었는데 수정해보셨군요 👍🏼

2021-02-25 17:16 UTC, Kihyun92 commented on src/Categories.jsx
> +      })}
카테고리명과 체크표시는 관련이 없고, 결국 id가 동일한 경우에 카테고리명 뒤에 체크 표시만 변경되는 것 같아요. 

따로 처리하면 어떨까요?  불필요한 로직들을 덜어낼 수 있을 것 같네요 ㅎㅎ

2021-02-25 17:16 UTC, Kihyun92 commented on src/actions.js
> +export function categoryClick(id) {
클릭보다는 선택한다는 느낌이 드는 것 같아요 ㅎㅎ `selectCategory`는 어떤가요?

2021-02-25 17:16 UTC, Kihyun92 commented on src/RestaurantContainer.jsx
> +  }, [regionName, categoryId]);
loadRestaurants를 여기서 하는게 좋을까요?

카테고리나 지역을 선택한 경우에 레스토랑 정보를 가져온다면 어떨까요?

2021-02-25 17:16 UTC, Kihyun92 commented on src/Restaurants.jsx
> +  }
`restaurants[0] === undefined` 이 경우가 어떤 경우인가요? 명확하지 않은 것 같아요

2021-02-25 18:23 UTC, SangHoonly commented on src/Restaurants.jsx
> +  }
그 부분을 제거하고, api의 fetchRestaurants 함수에서 response가 ok일 시 값을 처리하도록 수정하였습니다!

2021-02-26 07:31 UTC, SangHoonly commented
fetch하는 함수들을 테스트하기 위해, fetch-mock를 사용해보았습니다. 일단 전체적으로 통과해보니 기분은 좋네요. 추가적으로 반복되는 부분들 제거랑 부족한 테스트케이스, 전체적인 리팩토링을 수행하겠습니다!

2021-02-26 07:48 UTC, SangHoonly commented on src/RestaurantContainer.jsx
> +  }, [regionName, categoryId]);
해당 부분을 제거하고 카테고리나 지역을 클릭 시 레스토랑 정보를 가져오는 것으로 코드를 수정하였습니다!

2021-02-26 14:51 UTC, Kihyun92 requested changes
리뷰 드린것보다 더 잘 반영해주시는것 같아요 👍🏼

2021-02-26 14:51 UTC, Kihyun92 commented on src/actions.js
> +  return async (dispatch) => {
redux-thunk를 사용할때 함수를 dispatch 해줄때 두번쨰 인자로 우리는 `getState`를 받아올 수 있어요. 

이렇게되면 `regionName, categoryId`를 넘겨주지 않고 해결할 수 있지 않을까요? :)

2021-02-26 14:51 UTC, Kihyun92 commented on src/RegionsContainer.jsx
> +    const regionName = event.target.name;
event를 받아와야할까요? 카테고리의 경우엔 어떻게 처리해보셨나요?

2021-02-26 14:51 UTC, Kihyun92 commented on src/Restaurants.jsx
> +      {restaurants.map((restaurant) => (
구조분해할당을 적용해도 좋을 것 같네요 :)

2021-02-26 14:51 UTC, Kihyun92 commented on src/reducer.jsx
> +  if (action) {
이번 과제도 `if`나 `switch`를 사용하지 않고 해결해주세요~

2021-02-27 07:29 UTC, SangHoonly commented on src/RegionsContainer.jsx
> +    const regionName = event.target.name;
클릭시 event 대신에 지역 이름을 넘겨주는 것으로 수정하였습니다!

2021-02-27 07:30 UTC, SangHoonly commented on src/actions.js
> +  return async (dispatch) => {
오.. getState를 사용해서 store로부터 최신 state를 받아올 수 있었군요...

2021-02-27 08:26 UTC, SangHoonly commented on src/Restaurants.jsx
> +      {restaurants.map((restaurant) => (
구조분해할당을 적용했고, Regions와 Categories는 추가적으로 삼항 조건 연산자를 적용하여 반복되는 로직들을 줄였습니다!

2021-02-27 09:43 UTC, SangHoonly commented on src/reducer.jsx
> +  if (action) {
넵 수정하였습니다!

2021-02-27 14:39 UTC, Kihyun92 commented on src/RegionsContainer.jsx
> +    const regionName = event.target.name;
name 을 넘기는거도 좋지만, name은 변경될 가능성이 있을 것 같아요. 

DB에서 보장하는 id 값을 사용하는건 어떨까요?

2021-02-27 14:54 UTC, Kihyun92 requested changes

2021-02-27 14:54 UTC, Kihyun92 commented on src/Categories.jsx
> +            name: (categoryId === id) ? `${name}(V)` : name,
뒤에 체크표시와 앞에 네임은 사실 관련이 없는 부분이죠.

뒤에 붙는 체크표시에 대해서만 처리해줘도 좋을 것 같네요 :)

2021-02-27 14:56 UTC, Kihyun92 approved these changes
좋습니다 이번 과제는 Approve하겠습니다~

강의 풀이 영상을 꼭 보시고, 아샬님의 접근 방법을 보시면 좋을 것 같아요 ㅎㅎ

이번 과제를 하면서 어떤 점을 배우셨나요? 더 배우고 싶은 부분이 있나요?

추가로 의논이 필요한 부분이 있다면 말씀주세요 :)

2021-02-28 14:46 UTC, Kihyun92 commented
@SangHoonly 님, 슬랙 채널에 회고 남겨주시면 머지하겠습니다~

2021-03-03 15:53 UTC, merged