레스토랑 목록 조회 서비스 만들기
CodeSoom/react-week5-assignment-1 pull request #47
Opened 2021-02-23 12:05 UTC by yoonhe

2021-02-23 14:30 UTC, Kihyun92 requested changes
커밋 메시지를 보니 `TDD Cycle`을 잘 지키면서 작업해주신 것 같아요 💯

2021-02-23 14:30 UTC, Kihyun92 commented on src/App.jsx
> +import RegionsContainer from './RegionsContainer';
둘 사이에 공백을 추가해주면 좋을 것 같아요~ 가독성 뿐 아니라 외부/내부 모듈을 나누는 등 관심사에 따라 분리될 것 같아요 ㅎㅎ

다시보니 RegionsContainer의 위치만 변경해줘도 될것 같네요 ㅎㅎ

다른 부분도 살펴보고 적용해보세요~

2021-02-23 14:30 UTC, Kihyun92 commented on src/Categories.jsx
> +            {/* 클릭했을때 (V)가 생기는것을 확인해줄 방법을 잘 모르겠습니다... */}
테스트에서 확인할 방법을 모르겠다는 말씀인가요?

그리고 주석보다는 풀리퀘스트의 files changed 에서 해당 부분에 커맨트를 남겨주시는 방법도 있을것 같아요~

2021-02-23 14:30 UTC, Kihyun92 commented on src/Categories.test.jsx
> +    />);
반복 되는 코드가 있는 것 같아요. 어떻게 리팩터링할 수 있을까요?

테스트 코드도 리팩터링의 대상입니다 ㅎㅎ

2021-02-23 14:30 UTC, Kihyun92 commented on src/reducer.jsx
> +  }
이번 과제도 마찬가지로 `if`나 `switch`를 사용하지 않고 해결해보세요~

2021-02-23 14:30 UTC, Kihyun92 commented on src/CategoriesContainer.test.jsx
> +    expect(queryByText('한식(V)')).not.toBeNull();
`Categories` 컴포넌트에서 prop로 넘겨받은`selectCategoryId`가 일치하는 경우에 확인하는게 맞을 것 같아요 ㅎㅎ

2021-02-24 01:21 UTC, yoonhe commented on src/CategoriesContainer.test.jsx
> +    expect(queryByText('한식(V)')).not.toBeNull();
아하... 제가 `Categories `에 `selectId`를 넘겨놓고 테스트를 안했네요... 감사합니다 기현님! 추가해서 PR 날릴게요!

2021-02-24 07:42 UTC, yoonhe commented
1. 아래와같은 `redux-thunk` 함수도 `action 생성자`라고 부르나요??
2. 이런 함수들은 테스트가 필요한지 아닌지가 궁금합니다.

```js
export function loadRestaurants({ selectCategoryId, selectRegionId }) {
  return async (dispatch) => {
    const restaurants = await fetchRestaurants(
      { selectCategoryId, selectRegionId },
    );

    dispatch(setRestaurants(restaurants));
  };
}
```

2021-02-24 12:51 UTC, yoonhe commented on src/reducer.jsx
> +  }
`Lookup table pattern` 사용하여 리팩토링했습니다 ㅎㅎ

2021-02-24 12:55 UTC, Kihyun92 commented
> 1. 아래와같은 redux-thunk 함수도 action 생성자라고 부르나요??

action creator를 사용하는 비동기 액션 함수라고 보는게 맞을 것 같아요. ㅎㅎ

> 2. actions 생성자에 대한 테스트가 필요한지 아닌지가 궁금합니다.

필요한 부분과 필요 없는 부분이 있을 것 같아요. 외부 라이브러리에서 책임지지 않는 부분은 우리가 테스트 해야합니다. 😊

해당 액션에서 주요 관심사가 무엇인지 생각해보시면 좋을 것 같습니다.

> 3.만약 테스트해야한다면...

해야한다면 말씀하신 방법이 적합해 보여요 👍🏼 

thunk 테스트 참고
- https://github.com/reduxjs/redux-mock-store

> 4. 커버리지에서 실행되지 않은 코드에 api파일이 속해있는데 api 테스트코드를 따로 만들어줘야 할까요???

이번 과제 또한 커버리지 100%를 목표로 하기 때문에 필요하다면 해줘야 할 것 같아요 :)

> 5. App 테스트에서 궁금한점이 있습니다

마지막에 말씀하신 부분이 맞는 것 같습니다. ㅎㅎ  어떤 테스트를 의도하신지는 알 것 같아요. 실제 유저 동작처럼 클릭 이후에 가져온 데이터를 화면에 업데이트하고 그걸 확인하고 싶으신 것 같아요~ 

하지만 mocking을 해서 처리하고 있기도 하고, 그 이전에 App 컴포넌트 테스트에서 어디까지 테스트하는게 맞을지 한번 고민해보시면 좋을 것 같습니다. 🤔

혹시 잘못됐거나, 의논이 필요한 부분이 있다면 말씀주세요~

2021-02-24 13:11 UTC, Kihyun92 requested changes

2021-02-24 13:11 UTC, Kihyun92 commented on src/actions.js
> +export function clickCategory(id) {
선택한 카테고리를 처리하기 위한 액션을 생성해보셨네요~ `click` 도 좋지만, `select`는 어떤가요?

2021-02-24 13:11 UTC, Kihyun92 commented on src/Buttons.jsx
> +              : button.name}
`button.name`은 항상 노출되는 값이군요.

뒤쪽에 추가되는 체크 표시에만 예외처리를 해줘도 좋을 것 같아요~

2021-02-24 13:11 UTC, Kihyun92 commented on src/Restaurants.jsx
> +        <li key={restaurant.id}>{restaurant.name}</li>
구조 분해 할당으로 처리해줘도 좋을 것 같네요~

```suggestion
      {restaurants.map(({ id, name }) => (
        <li key={id}>{name}</li>
```

2021-02-25 08:00 UTC, yoonhe commented
`ec2` 테스트 실패하길래 저도 웹에 띄워놓고 재현해보았습니다.

```jsx
I.click('서울');
I.click('한식');

I.see('양천주가');
I.see('한국식 초밥');

I.click('부산');
I.see('밀면넘어져요');
```

첫번째로 서울, 한식 버튼을 눌렀을때 레스토랑 목록에 양천주가, 한국식 초밥이 떠야하는데

아래와 같이 서버에 요청을하면 `양천주가`만 응답 데이터에 담겨옵니다..

[https://eatgo-customer-api.ahastudio.com/restaurants?region=1&category=1](https://eatgo-customer-api.ahastudio.com/restaurants?region=1&category=1)

두번째로 부산, 한식 버튼이 눌렸을때는 `밀면넘어져요`가 아닌 `양천주가` 가 응답 데이터에 담깁니다.
[https://eatgo-customer-api.ahastudio.com/restaurants?region=4&category=1](https://eatgo-customer-api.ahastudio.com/restaurants?region=4&category=1)

뭐가 잘못된것일까요?..

2021-02-25 08:21 UTC, yoonhe commented
> 필요한 부분과 필요 없는 부분이 있을 것 같아요. 외부 라이브러리에서 책임지지 않는 부분은 우리가 테스트 해야합니다. 😊
해당 액션에서 주요 관심사가 무엇인지 생각해보시면 좋을 것 같습니다.

`action creator를 사용하는 비동기 액션 함수`에서는 서버에서 응답받은 데이터를 `setRegions` 등등의 `action` 생성함수에 인자로 넘겨주는 것에대해 관심을 가지면 될것같습니다. 

그래서 테스트코드에서는 서버에서 데이터를 응답받은 후에 실행된 `action creator`의 `type`과 `payload`에 `서버에서 응답받은 데이터`가 잘 들어가있는지를 테스트해보았습니다.
```
const store = mockStore(initialState);

await store.dispatch(loadCategories());
const actions = store.getActions();

expect(actions[0].type).toBe('setCategories');
expect(actions[0].payload.categories).not.toBeUndefined();
```

2021-02-25 10:17 UTC, yoonhe commented
> 하지만 mocking을 해서 처리하고 있기도 하고, 그 이전에 App 컴포넌트 테스트에서 어디까지 테스트하는게 맞을지 한번 고민해보시면 좋을 것 같습니다. 🤔

App 컴포넌트는 그저 redux와 UI컴포넌트들을 연결해주는 역할만 할뿐 상태 변화와 화면을 그리는 로직은 관심사가 아니므로 최초에 렌더링될때 발생되는 일에 대해서만 테스트해주면 될까요?

최초에 렌더링될때 발생되는 일에는
- `useEffect`로 인한 `dispatch` 함수 호출
- `store` 값에 따른 `View`의 상태

2021-02-25 10:29 UTC, yoonhe commented on src/Buttons.jsx
> +              : button.name}
이렇게 변경했습니다 ㅎㅎ
```js
`${button.name}${
    selectId === button.id ? '(V)' : ''
}`
```

2021-02-25 10:29 UTC, yoonhe commented on src/Restaurants.jsx
> +        <li key={restaurant.id}>{restaurant.name}</li>
훨씬 가독성이 좋은거같아요! 반영했습니다

2021-02-25 15:24 UTC, Kihyun92 commented
> ```js
> I.click('서울');
> I.click('한식');
> 
> I.see('양천주가');
> I.see('한국식 초밥');
> 
> I.click('부산');
> I.see('밀면넘어져요');
> ```
> 
> `ec2` 테스트 실패하길래 저도 웹에 띄워놓고 재현해보았는데 ec2와 다르게 결과값이 나와서 질문드립니다
> 
> 첫번째로 서울, 한식 버튼을 눌렀을때 레스토랑 목록에 양천주가, 한국식 초밥이 떠야하는데
> 
> 아래와 같이 서버에 요청을하면 `양천주가`만 응답 데이터에 담겨옵니다..
> 
> `Request URL` 입니다
> https://eatgo-customer-api.ahastudio.com/restaurants?region=1&category=1
> 
> 두번째로 부산, 한식 버튼이 눌렸을때는 `밀면넘어져요`가 아닌 `양천주가` 가 응답 데이터에 담깁니다.
> 
> `Request URL` 입니다
> https://eatgo-customer-api.ahastudio.com/restaurants?region=4&category=1
> 
> 뭐가 잘못된것일까요?..

레스토랑 목록 보기: https://eatgo-customer-api.ahastudio.com/restaurants?region=${regionName}&category=${categoryId}

region에 넘기는 값이 잘못된 것 같아요~ 한번 id가 아닌 네임으로 호출해보시겠어요?

2021-02-25 15:29 UTC, Kihyun92 commented
> > 필요한 부분과 필요 없는 부분이 있을 것 같아요. 외부 라이브러리에서 책임지지 않는 부분은 우리가 테스트 해야합니다. 😊
> > 해당 액션에서 주요 관심사가 무엇인지 생각해보시면 좋을 것 같습니다.
> 
> `action creator를 사용하는 비동기 액션 함수`에서는 서버에서 응답받은 데이터를 `setRegions` 등등의 `action` 생성함수에 인자로 넘겨주는 것에대해 관심을 가지면 될것같습니다.
> 
> 그래서 테스트코드에서는 서버에서 데이터를 응답받은 후에 실행된 `action creator`의 `type`과 `payload`에 `서버에서 응답받은 데이터`가 잘 들어가있는지를 테스트해보았습니다.
> 
> ```
> const store = mockStore(initialState);
> 
> await store.dispatch(loadCategories());
> const actions = store.getActions();
> 
> expect(actions[0].type).toBe('setCategories');
> expect(actions[0].payload.categories).not.toBeUndefined();
> ```

좋습니다 👍🏼  조금 예시를 덧붙이자면 레스토랑 목록을 가져오는 것을 볼까요.
``` javascript
export const loadRestaurants = () => async (dispatch, getState) => {
  const restaurants = await restaurantService.getRestaurants();
  
  dispatch(setRestaurants(restaurants));
}
```
이 비동기 액션에서 하는 일은

`서버에서 레스토랑 목록을 가져온다.`

`가져온 레스토랑 목록을 setRestaurants액션을 통해 dispatch한다.`

restaurantService에서 레스토랑 목록을 요청한 후 레스토랑을 업데이트 하는 setRestauarnts라는 액션을 다시 dispatch합니다. 하지만 레스토랑 목록을 어떻게 가져오는지는 주요한 관심사가 아닙니다. 그래서 getRestaurants는 mocking하여 처리하고 올바르게 가져왔다고 가정하고 액션이 올바르게 처리되는지 테스트합니다.
```javascript
import thunk from 'redux-thunk';

import configureStore from 'redux-mock-store';

const middlewares = [thunk];
const mockStore = configureStore(middlewares);

const restaurants = [
  { id: 1, name: '마녀주방', category: '한식', address: '강남' },
];

getRestaurants.mockResvoledValue(restaurants);

test('loadRestaurants', async () => {
  store = mockStore({});
  
  await loadRestaurants();
  
  const actions = store.getActions();
  
  expect(actions[0]).toEqual(setRestaurants(restaurants));
});
```

참고
- [https://github.com/reduxjs/redux-mock-store](https://github.com/reduxjs/redux-mock-store)

2021-02-25 15:37 UTC, Kihyun92 commented
> > 하지만 mocking을 해서 처리하고 있기도 하고, 그 이전에 App 컴포넌트 테스트에서 어디까지 테스트하는게 맞을지 한번 고민해보시면 좋을 것 같습니다. 🤔
> 
> App 컴포넌트는 그저 redux와 UI컴포넌트들을 연결해주는 역할만 할뿐 상태 변화와 화면을 그리는 로직이 실제로 어떻게 생겼는지에 대해서는 관심사가 아니므로 최초에 렌더링될때 발생되는 일에 대해서만 테스트해주면 될까요?
> 
> 최초에 렌더링될때 발생되는 일은 아래와 같습니다
> 
> * `useEffect`로 인한 `dispatch` 함수 호출 횟수
> * `store` 값에 따른 `View`의 상태
>   
>   * 최초에 렌더링시에는 `store`가 모두 빈배열이므로 테스트해줄 필요가 없을거 같다는 생각이 듭니다
>   * `selectCategoryId, selectRegionId` 두 값이 있을경우에 대한 테스트가 필요할거 같습니다
>     아래의 코드를 위한 테스트가 필요하다 생각합니다
> 
> ```js
> useEffect(() => {
>     if (selectCategoryId && selectRegionId) {
>       dispatch(loadRestaurants({ selectCategoryId, selectRegionId }));
>     }
>   }, [selectCategoryId, selectRegionId]);
> ```
> 
> 궁금한점이 있습니다.
> `App` 에서 dispatch가 실행될때 `loadRegions(), loadCategories()` 등등의 반환값(함수)에
> 대한 테스트는 없어도 되나요?
> 
> 액션 생성자처럼 객체를 반환하는 경우 아래와같이 테스트해주면 되는데.. 함수를 반환하는 경우에는 어떻게 테스트를
> 진행해야할지 잘 모르겠습니다...
> 
> ```js
> toBeCalledWith({
>      type: 'selectRegion',
>      payload: {
>        id: 1,
>      },
>    });
> ```

맞습니다~ 말씀하신대로 처리해보면 좋을 것 같네요👍🏼 

App 컴포넌트의 테스트라는게 참 E2E 테스트와도 경계가 맞닿아 있는 부분같아요. 어느정도를 유닛 테스트로 커버하고, 나머지는 E2E 테스트로 커버할지를 한번 고민해보라는 의미에서 질문을 드려봤습니다 ㅎㅎ

그리고 dispatch에 대한 반환값들 즉 API의 응답값에 대해서는 프론트에서 테스트하는게 맞을까요? 해당 값들이 어떻게 바뀔지 프론트에서는 알수 없는 부분 같아요. ㅎㅎ 

상황마다 다를 수 있지만, 저라면 App에서는 최초 로딩시 dispatch 함수가 호출됐는지 여부만 판단하고, 원하는 값이 넘어왔는지는 E2E 테스트에서 확인할 것 같아요~

2021-02-25 15:53 UTC, Kihyun92 requested changes
리뷰가 늦었네요 🙏

많은 고민을 해보면서 진행해보시는 것 같아요 👍🏼 

이런 의미있는 고민들은 슬랙 채널을 통해 동료들과 나눠봐도 좋을 것 같네요 ㅎㅎ

같은 고민을 하고 있을 수도 있고, 의논을 통해 더 좋은 방법을 찾을 수도 있을 것 같아요~

2021-02-25 15:53 UTC, Kihyun92 commented on src/Buttons.jsx
> +            }
```suggestion
            {button.name}
            {selectId === button.id ? '(V)' : null}
```

개인적으로 가독성에 좋지 않은 것 같아요. 이런 방식으로 처리할 순 없을까요?

2021-02-25 15:53 UTC, Kihyun92 commented on src/Buttons.test.jsx
> +  function renderButtons({ buttons, selectId } = { selectId: null }) {
`default` 값을 처리한거라면 아래처럼 해줘도 되지 않을까요?
```suggestion
  function renderButtons({ buttons, selectId = null }) {
```

2021-02-25 15:53 UTC, Kihyun92 commented on src/Buttons.test.jsx
> +      const buttons = [{ id: 1, name: '한식' }];
buttons 값이 다 같은것 같은데, 혹시 추후에 변경될 가능성이 있나요~? 없다면 인자로 넘기지 않고 renderButtons 함수 안에서 처리해줘도 좋겠네요 :)

2021-02-26 05:43 UTC, yoonhe commented
> restaurantService에서 레스토랑 목록을 요청한 후 레스토랑을 업데이트 하는 setRestauarnts라는 액션을 다시 dispatch합니다. 하지만 레스토랑 목록을 어떻게 가져오는지는 주요한 관심사가 아닙니다. 그래서 getRestaurants는 mocking하여 처리하고 올바르게 가져왔다고 가정하고 액션이 올바르게 처리되는지 테스트합니다.

말씀해주신 부분 참고하여, `loadRegions` 를  `mocking`한 후 `mockResolvedValue`를 이용해 반환값을 조작해주었습니다.

```js
const restaurants = [
  {
    id: 1,
    categoryId: 1,
    name: '양천주가',
    address: '서울 강남구 123456',
    information: '양천주가 in 서울 강남구 123456',
  },
];

fetchRestaurants.mockResolvedValue(restaurants);

describe('laodRestaurants', () => {
  const store = mockStore({});
  it('runs setRestaurants', async () => {
    await store.dispatch(loadRestaurants({
      selectedRegion: { id: 1, name: '서울' },
      selectedCategory: { id: 1, name: '한식' },
    }));

    const actions = store.getActions();

    expect(actions[0].payload.restaurants).toEqual(restaurants);
  });
});
```

위와같이 테스트코드를 구현해보았는데, 제가 기현님꼐서 하신 말씀을 알맞게 이해한게 맞을까요?

2021-02-26 06:04 UTC, yoonhe commented
api 테스트코드도 아래와같이 작성해보았는데.. 제가 알맞게 작성한게 맞을까요?..

`jest` 환경에서는  `fecth`를 사용하지 못하므로 아래와같이 함수를 임의로 만들어준 후 반환값을 가짜로 만들어주었습니다.
```js
function fetchMaker(fetchData) {
  global.fetch = jest.fn().mockImplementation(() => new Promise((resolve) => {
    resolve({
      json: () => (fetchData),
    });
  }));
}
```

가짜 `fetch` 함수를 이용해 아래와같이 테스트를 해주었는데.. `api` 테스트코드 이렇게 짜는게 맞을까요?

```js
it('fetches regions', async () => {
    fetchMaker([{ id: 1, name: '서울' }]);

    const regions = await fetchRegions();

    expect(regions).toHaveLength(1);
    expect(regions[0].name).toBe('서울');
});
```

2021-02-26 11:19 UTC, yoonhe commented
> 그리고 dispatch에 대한 반환값들 즉 API의 응답값에 대해서는 프론트에서 테스트하는게 맞을까요? 해당 값들이 어떻게 바뀔지 프론트에서는 알수 없는 부분 같아요. ㅎㅎ
상황마다 다를 수 있지만, 저라면 App에서는 최초 로딩시 dispatch 함수가 호출됐는지 여부만 판단하고, 원하는 값이 넘어왔는지는 E2E 테스트에서 확인할 것 같아요~

제가 질문을 잘못한거같습니다 ㅎㅎㅎㅎ 

제가 확인하고 싶었던것은 아래처럼 컴포넌트 렌더링시 `dispatch`가 발생될때 `dispatch`가 2번 발생했다는 것을 테스트코드에 작성해주면 실제로 `dispatch`가 2번 발생했지만 그 두번에 `loadRegions`, `loadCategories`가 포함될수도 있고, 혹은 `loadCategories`, `loadRestaurants`가 될수도 있는데 어떤 `thunk 함수`를 함께 `dispatch`하는지에 대해서 테스트하고 싶었습니다.

그런데 기현님 말씀은 `thunk 함수`가 알맞게 `dispatch` 되었는지는 `e2e` 테스트에서 확인하고 `App`에서는 `dispatch`의 실행 횟수만 테스트하면 된다는 말씀이시죠??

```js
useEffect(() => {
    dispatch(loadRegions());
    dispatch(loadCategories());
  }, []);
```

2021-02-26 11:24 UTC, yoonhe commented
@Kihyun92 

기현님... 저 과제 잘하고 있는거 맞나요?... 매일매일 열심히 하고있기는 한데... 제가 방향 잘잡고 하고있는게 맞겠죠?..

2021-02-26 13:50 UTC, Kihyun92 commented
> api 테스트코드도 아래와같이 작성해보았는데.. 제가 알맞게 작성한게 맞을까요?..
> 
> `jest` 환경에서는 `fecth`를 사용하지 못하므로 아래와같이 함수를 임의로 만들어준 후 반환값을 가짜로 만들어주었습니다.
> 
> ```js
> function fetchMaker(fetchData) {
>   global.fetch = jest.fn().mockImplementation(() => new Promise((resolve) => {
>     resolve({
>       json: () => (fetchData),
>     });
>   }));
> }
> ```
> 
> 가짜 `fetch` 함수를 이용해 아래와같이 테스트를 해주었는데.. `api` 테스트코드 이렇게 짜는게 맞을까요?
> 
> ```js
> it('fetches regions', async () => {
>     fetchMaker([{ id: 1, name: '서울' }]);
> 
>     const regions = await fetchRegions();
> 
>     expect(regions).toHaveLength(1);
>     expect(regions[0].name).toBe('서울');
> });
> ```
> 
> 질문이 한가지 더있습니다. fetch를 `mocking` 해줄때 위와같이 해주는 방법과 `fetch-mock`을 사용해주는 방법중 어떤 방법이 더 효율적인가요?? 실제로 실무에서는 어떤것을 더 많이 사용하나요?.. 아니면 상황에따라 선택을 해주는게 맞을까요? 간단한 테스트에는 위와같은 방법을 사용하고..? 좀더 디테일한 테스트가 필요한땐 `fetch-mock`을 사용하는 식으로?

정답은 없는 것 같지만, 저는 API 를 간단하게 mocking 해주고 확인만 하는 식으로 처리합니다. 상황에 따라 `fetch-mock`을 사용할 수도 있겠죠.

사실 API 테스트를 프론트에서 하는게 어떤 의미가 있을까요? API가 잘 동작하는지는 서버에서 확인할 부분이라고 생각해요. 프론트에선 응답값에 대해서 보장할 수 없는 부분이 있죠. 따라서 fetch 함수에 대해서 필요할 때 mocking 해서 테스트를 해주는게 좋을 것 같아요 ㅎㅎ

2021-02-26 13:57 UTC, Kihyun92 commented
> > 그리고 dispatch에 대한 반환값들 즉 API의 응답값에 대해서는 프론트에서 테스트하는게 맞을까요? 해당 값들이 어떻게 바뀔지 프론트에서는 알수 없는 부분 같아요. ㅎㅎ
> > 상황마다 다를 수 있지만, 저라면 App에서는 최초 로딩시 dispatch 함수가 호출됐는지 여부만 판단하고, 원하는 값이 넘어왔는지는 E2E 테스트에서 확인할 것 같아요~
> 
> 제가 질문을 잘못한거같습니다 ㅎㅎㅎㅎ 다음부터는 다시한번 내용을 확인하고 질문을 하도록 할게요 ㅜㅜ!
> 
> 제가 확인하고 싶었던것은 아래처럼 컴포넌트 렌더링시 `dispatch`가 발생될때 `dispatch`가 2번 발생했다는 것을 테스트코드에 작성해주면 실제로 `dispatch`가 2번 발생했지만 그 두번에 `loadRegions`, `loadCategories`가 포함될수도 있고, 혹은 `loadCategories`, `loadRestaurants`가 될수도 있는데 예상하지 않았던 `thunk 함수`가 `dispatch` 될수도 있으므로
> 어떤 `thunk 함수`를 `dispatch`하는지에 대해서 테스트하고 싶었습니다.
> 
> 그런데 기현님 말씀은 `thunk 함수`가 알맞게 `dispatch` 되었는지는 `e2e` 테스트에서 확인하고 `App`에서는 `dispatch`의 실행 횟수만 테스트하면 된다는 말씀이시죠??
> 
> ```js
> useEffect(() => {
>     dispatch(loadRegions());
>     dispatch(loadCategories());
>   }, []);
> ```

렌더시에 `loadRegions, loadCategories`가 포함됐는지에 대한 확인은 e2e 테스트로도 가능한 부분 같습니다. 어떤게 렌더링 됐는지 확인하면 되겠죠 ㅎㅎ

그리고 dispatch의 횟수를 테스트하게되면 나중에 dispatch가 추가되는 경우에는 우리가 테스트에 횟수를 일일히 수정해줘야할 것 같아요. 이게 해당 컴포넌트 테스트의 관심사가 아니라고 생각이 든다면, 초기화 로직을 하나의 dispatch로 처리 가능하도록 action들을 묶어주는 방법도 있을 것 같네요 :)

해당 컴포넌트에서 유닛 테스트의 의미를 한번 생각해보셔도 좋을 것 같아요.

2021-02-26 14:06 UTC, Kihyun92 approved these changes
해은님 충분히 잘해주고 계십니다! 너무 잘해주고 계셔서 리뷰드릴 부분을 찾는게 쉽지 않네요 😂

코드숨의 과정에서는 정답이 없습니다. 이렇게 해야해! 가 아닌 주어진 문제를 해결하기 위해선 어떤 방식으로 해야할지 끊임없이 고민해보도록 하는게 저희의 역할이다보니 잘하고 계신다는 커맨트를 저도 잘 못남겼네요 😅 반성합니다.

고민을 정말 많이 해주고 계시고, 그 과정에서 많은걸 얻고 계실거라고 생각해요. 지금 잘 하고 있는건가. 라는 생각이 드실땐, 과제의 목표가 뭔지 한번 고민해보시고 그걸 달성하려면 어떻게 해야할지에 포커스를 맞춰봐도 좋을 것 같아요 ㅎㅎ 부족하다 싶으면 저희가 리뷰를 드릴거니까요 😊

의논이 필요하다면 지금처럼 적극적으로 말씀해주세요 ㅎㅎ

과제는 approve 하겠습니다. 위에 커맨트 남긴 부분 확인해보시고 추가로 작업을 진행해주셔도 됩니다 👍🏼 

오늘 자정~내일 올라올 풀이 영상 꼭 봐보시면 좋을 것 같아요 😊

2021-02-28 14:45 UTC, Kihyun92 commented
@yoonhe 님, 슬랙 채널에 회고 올려주시면 머지하도록 하겠습니다~

2021-03-03 15:55 UTC, merged