레스토랑
CodeSoom/react-week5-assignment-1 pull request #50
Opened 2021-02-24 15:37 UTC by jjkim01

수요일까지는 못했던 4-2 과제를 진행하느라 첫 PR이 좀 늦어졌습니다.

이번 PR 내용은
1. reducer, actions, store 파일 만들어서 Redux 구조 갖추기
2. Items 컴포넌트를 통해 region 출력하기 (테스트 포함)
입니다.

이 다음 계획은
1. ItemsContainer 만들어서 데이터와 출력부 분리
2. category도 출력하게 하기
3. li로 돼있는 항목들을 button으로 변경
4. button 클릭하면 (V) 표시되도록 구현
5. 다른 항목 클릭하면 (V) 사라지게 구현
6. region, category를 async, await 으로 api에서 받아 뿌려주는 것으로 바꾸기
7. region, category 클릭되면 async, await 으로 api에서 조합된 결과 받아 뿌려주는 것 구현

이런식으로 구현하려고 합니다.
Promise(비동기)가 어디 들어가야 될지 잘 모르겠네요..

질문은 두가지입니다.
1. 다음 **계획**에 대한 내용은 괜찮을까요 ??
2. 계획에서 **비동기로 구현**돼야 할 부분이 어디인가요..?

감사합니다!

2021-02-25 17:27 UTC, Kihyun92 requested changes
어떻게 진행할지 계획을 세워보셨군요 ㅎㅎ 계획을 세우면 진행 방향을 아는데 도움이되죠.

`TDD cycle` 관점에서 진행해보셔도 좋을 것 같아요~ 미리 필요한 것들을 만드는 것보다, 필요할때 만드는거죠.

> 비동기로 구현돼야 할 부분은 사용자가 async 함수 호출하는 부분이 맞나요?

이 질문은 답변드리기 약간 애매한 것 같아요. 데이터를 가져오거나 요청하는 부분을 비동기로 처리해야하고, 그 과정에서 `async, await`를 사용할 수 있겠죠? ㅎㅎ 의도하신 질문에 대한 답변이 맞을지 모르겠네요 :)

2021-02-25 17:27 UTC, Kihyun92 commented on src/Items.jsx
> +      ))}
지역과 카테고리를 각각 분리해줘도 좋을 것 같아요 :)

2021-02-25 17:27 UTC, Kihyun92 commented on src/Items.jsx
> +export default function Items({ region, category }) {
item 이라는 단어가 여러 의미를 떠오르게 하는 것 같아요 ㅎㅎ 조금 더 명확하게 할 수 없을까요?

2021-02-25 17:52 UTC, jjkim01 commented on src/Items.jsx
> +      ))}
수정된 코드에서는 지역과 카테고리를 각각, br 기준으로 분리해봤습니다.

```
<ul>
  {region.map((item, index) => (
    <li key={index}>
      <input type="button" value={item} onClick={onClick(index)} />
    </li>
  ))}

  <br />

  {category.map((item, index) => (
    <li key={index}>
      <input type="button" value={item} onClick={onClick} />
    </li>
  ))}
</ul>
```

2021-02-25 17:57 UTC, jjkim01 commented on src/Items.jsx
> +export default function Items({ region, category }) {
region이랑 category의 공통 분모를 생각하다가 잘 안떠올라서 일단 Item으로 했었습니다..

```
restaurantCombinationElements = ""; 
```
이런 이름도 있을 것 같은데 너무 긴가 싶네요 껄..

변수 명명규칙에 적합한 이름이 잘 안 떠오르는데 혹시 하나 추천해주실 수 있으신가요?

2021-02-26 14:09 UTC, Kihyun92 commented on src/Items.jsx
> +export default function Items({ region, category }) {
> region이랑 category의 공통 분모를 생각하다가 잘 안떠올라서 일단 Item으로 했었습니다..

이름 짓기 애매하단 신호는 해당 컴포넌트가 두가지 이상의 역할을 하고 있다는 의미일 것 같아요 ㅎㅎ 

컴포넌트를 관심사에 맞게 적절히 분리해주면 자연스레 해결 되는 부분 같습니다 :)

2021-02-26 14:27 UTC, Kihyun92 requested changes

2021-02-26 14:27 UTC, Kihyun92 commented on src/reducer.js
> +    }
화면에 체크해주는 처리를 reducer에서 해보셨군요 ㅎㅎ

이전 과정에서 고민해본 관심사 측면에서 봤을때, 화면에 그려지는 부분은 어디서 처리해주는게 좋을지 한번 고민해보셔도 좋을 것 같아요~

2021-02-26 14:27 UTC, Kihyun92 commented on src/reducer.js
> +  if (action.type === 'setItems') {
이번 과제도 `if`나 `switch`를 사용하지 않고 해결해주세요~

2021-02-26 14:27 UTC, Kihyun92 commented
https://github.com/CodeSoom/react-week5-assignment-1/pull/50#discussion_r583662792

위에 커맨트 남긴 부분 한번 고민해보시면 좋을 것 같습니다 :)

2021-02-28 03:13 UTC, jjkim01 commented on src/reducer.js
> +  if (action.type === 'setItems') {
`else`, `switch` 가 사용 안되고, `if`는 되는 걸로 알고있는데 혹시 잘못 말씀하신 것 맞나요 ??

2021-02-28 14:40 UTC, Kihyun92 commented
@jjkim01 님, 슬랙 채널에 회고 올려주세요~

그리고 강의 풀이 영상 꼭 보시면 좋을 것 같습니다

2021-02-28 14:43 UTC, jjkim01 commented
> @jjkim01 님, 슬랙 채널에 회고 올려주세요~
> 
> 그리고 강의 풀이 영상 꼭 보시면 좋을 것 같습니다

옙 감사합니다

2021-03-03 15:58 UTC, merged