[5주차] 레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #57
Opened 2021-05-31 13:57 UTC by Hamill210

- 저와의 약속때문에 일단 PR만 보내겠습니다!
- 구현은 내일해보려고 합니다.

2021-06-01 15:16 UTC, Kihyun92 commented
좋아요 👍🏼  지금처럼 TDD 사이클을 작게 유지하면서 진행해보죠~

2021-06-02 14:42 UTC, Kihyun92 requested changes
잘 진행하고 계시군요 👍🏼

2021-06-02 14:42 UTC, Kihyun92 commented on src/App.jsx
> +import { useDispatch } from 'react-redux';
이 모듈 사이 공백은 제거해도 될 것 같아요~

저는 주로 외부 모듈 / 내부 컴포넌트 모듈을 구분해주기 위해 공백을 사용합니다. 본인 만의 기준이 있어도 좋을 것 같아요~
관련해서 eslint rule도 있으니 참고해보세요~ 
- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

2021-06-02 14:42 UTC, Kihyun92 commented on src/App.test.jsx
> +import { useDispatch, useSelector } from 'react-redux';
마찬가지로 이 셋 모듈간에 공백은 제거해도 될 것 같아요.

2021-06-02 14:42 UTC, Kihyun92 commented on src/App.test.jsx
> +import regions from '../fixtures/regions';
이 모듈 간에 공백도 제거하는건 어떨까요?

2021-06-02 14:42 UTC, Kihyun92 commented on src/reducer.test.js
> +    expect(state.regions).toHaveLength(3);
`3` 이라고 하드코딩 하기보다는, `regions.length` 와 같이 나타내주면 추후 fixture가 변경되더라도 신경쓰지 않아도 되지 않을까요?

2021-06-04 16:20 UTC, Kihyun92 commented
과제가 어떻게 진행중이신지 궁금해요! 진행에 어려움이 있거나 의논이 필요하면 꼭 말씀해주세요 🙏🏻

올라온 과제 풀이 영상을 보시고 직접 과제를 해보셔도 좋을 것 같습니다 😊

2021-06-05 03:24 UTC, Hamill210 commented
> 과제가 어떻게 진행중이신지 궁금해요! 진행에 어려움이 있거나 의논이 필요하면 꼭 말씀해주세요 🙏🏻
> 
> 올라온 과제 풀이 영상을 보시고 직접 과제를 해보셔도 좋을 것 같습니다 😊

이번주 맡은 서비스 출시를 하는 바람에 많이 신경을 쓰지 못했네요 ㅠㅠ... 더군다나 지난주 과제를 너무 대충 이해하고 구현해버려서
이번 주 다시 시작하려니 버벅이는 점이 많아서 지난 주 강의를 다시 듣고 있었습니다. 아마 오늘 내일 빡세게 해서 구현해보려 합니다. ㅎㅎ

2021-06-05 07:20 UTC, Hamill210 commented
정신없이 구현하다보니 지난 리뷰해주신 부분은 아직 반영을 못했습니다. 얼릉 반영하도록 하겠습니다 (_ _)

2021-06-05 13:03 UTC, Hamill210 commented on src/App.jsx
> +import { useDispatch } from 'react-redux';
넵 공백 제거해서 반영해보겠습니다. 피드백 감사합니다~

2021-06-05 13:03 UTC, Hamill210 commented on src/App.test.jsx
> +import { useDispatch, useSelector } from 'react-redux';
넵 이 부분도 반영해보겠습니다. 피드백 감사합니다~!!

2021-06-05 13:04 UTC, Hamill210 commented on src/App.test.jsx
> +import regions from '../fixtures/regions';
넵!

2021-06-05 13:04 UTC, Hamill210 commented on src/reducer.test.js
> +    expect(state.regions).toHaveLength(3);
오 그렇죠... 항상 매직넘버를 사용해서 불편하곤 했는데.. 피드백 감사합니다. 반영해볼게요!!

2021-06-05 17:22 UTC, Kihyun92 requested changes
열심히 진행해주셨군요 👍🏼 

직접 더 구현해보셔도 좋고, 올라온 과제 풀이 영상을 보시고 직접 해보셔도 좋을 것 같습니다!

2021-06-05 17:22 UTC, Kihyun92 commented on src/RestaurantCategoriesContainer.jsx
> +    dispatch(checkCategory(id));
선택했다는 의미로 `check`보다 `selected` 는 어떤가요?

2021-06-05 17:22 UTC, Kihyun92 commented on src/RestaurantCategories.jsx
> +export default function RestaurantCategories({ categories, onClickCategory }) {
컴포넌트 네이밍을 `Categories` 라고만 해도 될 것 같은데 어떤가요?

2021-06-05 17:22 UTC, Kihyun92 commented on src/reducer.js
> +  });
조금 복잡하네요. 선택 여부에 따라 체크하는 로직은 노출해주는 부분에서 하면 어떨까요?

2021-06-06 07:34 UTC, Hamill210 commented on src/RestaurantCategoriesContainer.jsx
> +    dispatch(checkCategory(id));
select랑 check 중에 많이 고민했었는데... ㅎㅎ 피드백 감사합니다!

2021-06-06 07:36 UTC, Hamill210 commented on src/RestaurantCategories.jsx
> +export default function RestaurantCategories({ categories, onClickCategory }) {
Categories는 식당 카테고리라는 걸 스스로 표현하지 못한다고 생각하여 Restaurant을 붙여주었습니다. 왜 Categories로만 해도 되는지 알려주시면 감사하겠습니다!

2021-06-06 07:37 UTC, Hamill210 commented on src/reducer.js
> +  });
저도 구현하면서 많이 복잡하다고 생각은 했습니다..
그러면 이런 로직은 어느 곳에서 구현하는 게 적합한걸까요? 액션함수 내부 또는 액션함수를 호출하는 컨테이너가 적합한지 궁금합니다!

2021-06-06 07:37 UTC, Hamill210 commented
일단... 지역명, 카테고리명 선택 후 레스토랑 정보를 가져오도록 만들긴했습니다.
하지만 다음과 같은 문제가 있는데요
- 레스토랑 정보 가져온 후 지역명, 카테고리명을 초기화시켜주지 않으면 API 무한 호출
    - 그래서 레스토랑 정보 가져온 후, 지역명 or 카테고리명 하나만 선택해도 API 호출하는 로직을 만들지 못하겠습니다.
    - 혹시 제 로직이 왜 API 무한 호출하는지 알려주시면 감사하겠습니다.

2021-06-06 15:42 UTC, Kihyun92 commented on src/RestaurantCategories.jsx
> +export default function RestaurantCategories({ categories, onClickCategory }) {
제가 설명이 짧았네요! 😅

저는 반대로 식당의 카테고리라는 걸 굳이 알려야할 필요가 있을까 라는 생각이 들었어요. 그런데 생각해보니 한식, 중식, 양식등을 카테고리라고만 표현하는게 어색할 수도 있을 것 같네요ㅎㅎ 이 부분은 지금처럼 해도 괜찮을 것 같습니다. 

다만 Regions에 대한 부분에서는 위의 이유와 같이 굳이 레스토랑을 붙일 필요가 없을 것 같아요.

2021-06-06 15:46 UTC, Kihyun92 commented on src/reducer.js
> +  });
이 부분은 `presentational` 영역에서 해주는건 어떨까요?

아래처럼 조금 더 단순하게 처리할 수 있을 것 같아요.

```javascript
<li key={id}>
  <button
    type="button"
    onClick={() => onClickRegion(id)}
  >
    {name}
    {region.id === selectedRegion.id ? '(V)' : null}
  </button>
</li>
```

2021-06-06 15:56 UTC, Kihyun92 reviewed
짧은 시간에 많은 작업을 해주신 것 같아요!  👍🏼 👍🏼 

과제 풀이 영상을 보시고 직접 해보셔도 좋을 것 같습니다 :)

슬랙 채널에 회고 남겨주세요! :)

2021-06-06 15:56 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +  }
`useEffect` hook을 사용해서 life-cycle에 맞게 위 로직이 수행되도록 처리해줘야할 것 같아요!
- https://ko.reactjs.org/docs/hooks-effect.html

다른 방법으로는 RestaurantsContainer에서는 단순히 레스토랑 정보만 가져오도록하고, 지역이나 카테고리를 눌렀을때 레스토랑을 fetch 해줄 수 있을 것 같아요~

2021-06-13 13:30 UTC, merged