Restaurant search
CodeSoom/react-week5-assignment-1 pull request #59
Opened 2021-06-01 12:22 UTC by dngwoodo

2021-06-01 15:49 UTC, Kihyun92 requested changes
폴더로 관리하기 위해 index.jsx로 처리하신 것 같군요~

![image](https://user-images.githubusercontent.com/35797540/120351410-d68cc000-c33a-11eb-9dbb-13b27e51ae35.png)
저희 팀같은 경우엔 위와 같이 컴포넌트 이름과 파일 이름을 같게 해주기위해 index.ts와 같은 파일을 사용합니다.
```typescript
// index.ts
import PostWrite from './PostWrite';

export default PostWrite;

```
index.ts에서는 해당 컴포넌트를 import하고 다시 export 해주는 처리를 해주고 있어요. 조금 불편하긴 하지만, 이런 방식도 있다는걸 알려드려요 ㅎㅎ

2021-06-01 15:49 UTC, Kihyun92 commented on src/App.test.jsx
> +  });
일단 동일한 테스트 같은데, 다른 의도가 있을까요?

그리고 이 경우에 `dispatch`가 독립적이지 않은 것 같아요. mocking 한 함수를 각 테스트별로 독립적으로 유지되도록 beforeEach에 clear 하는 로직을 추가해주세요~

2021-06-01 15:49 UTC, Kihyun92 commented on src/Button/index.jsx
> +
리액트에서 문제는 없겠지만, 불필요한 공백은 제거해주세요~

2021-06-01 15:49 UTC, Kihyun92 commented on src/RegionContainer/index.test.jsx
> +import RegionContainer from '.';
```suggestion
import RegionContainer from './RegionContainer';
```
위와 같게 처리할 수 없을까요?

2021-06-01 15:49 UTC, Kihyun92 commented on src/RegionContainer/index.test.jsx
> +  });
여기도 mock 함수를 clear 해주는 로직을 추가해주는게 좋을 것 같아요~

2021-06-01 15:49 UTC, Kihyun92 commented on src/reducer/index.js
> +  return state;
`Object Literal Lookup`을 사용해서 표현해볼 수도 있을 것 같아요 😄

참고:
- https://omwri.medium.com/javascript-patterns-lookup-tables-26bbaf693e24
- https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

2021-06-02 15:46 UTC, Kihyun92 requested changes

2021-06-02 15:46 UTC, Kihyun92 commented on src/App.jsx
> +import { loadRegions, loadCategories } from './actions';
```suggestion
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { loadRegions, loadCategories } from './actions';
```
이렇게 공백으로 외부/내부 모듈을 구분하는건 어떤가요?

2021-06-02 15:46 UTC, Kihyun92 commented on src/Button/index.test.jsx
> +    );
매 테스트마다 render 해주는 로직이 반복되는 것 같은데, 함수로 추출해주면 어떨까요?

2021-06-02 15:46 UTC, Kihyun92 commented on src/ButtonContainer/index.jsx
> +  const selected = useSelector((state) => state.search[search]);
```suggestion
  const dispatch = useDispatch();
  
  const selected = useSelector((state) => state.search[search]);

  function handleClick(payload) {
    dispatch(changeSearch({
      search: payload.search,
      value: payload.value,
    }));
  }
```

순서를 이렇게 해주는 건 어떤가요?

2021-06-02 15:46 UTC, Kihyun92 commented on src/Buttons/index.jsx
> +export default function Buttons({ options, search }) {
개인적으로 Buttons 컴포넌트만 봤을때 options, search는 각각 어떤 값인지 변수명만 봐서는 이해하기 어려운 것 같아요.

조금 더 명확하게 해줄 순 없을까요?

2021-06-02 17:22 UTC, dngwoodo commented on src/App.test.jsx
> +  });
https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/e26c6aa27e81e046e689132501f302ad2d046fbb 에서 수정했습니다. test는 한개로 합치고 case도 좀 바꿔봤는데 적절한지 한번 봐주시면 감사하겠습니다!

2021-06-02 17:22 UTC, dngwoodo commented on src/Button/index.jsx
> +
피드백 감사합니다. 삭제했습니다!

2021-06-02 17:22 UTC, dngwoodo commented on src/RegionContainer/index.test.jsx
> +  });
피드백 감사합니다. https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/4087cfe552b3dad00feb128dd8aab272f2e36b85 에서 추가했습니다.

2021-06-02 17:28 UTC, dngwoodo commented on src/App.jsx
> +import { loadRegions, loadCategories } from './actions';
https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/acf0a1e19416a134388f9d53c6fb978d96b8792f 에서 변경했습니다. 개발자마다 공백으로 의미를 나누는 방법은 다르겠지만 전 redux 모듈들, 컴포넌트 모듈들, 상수모듈들 등 이렇게 의미를 부여해서 나눠주고 있는데 이렇게 해주어도 괜찮을까요?

2021-06-02 17:39 UTC, dngwoodo commented on src/Button/index.test.jsx
> +    );
피드백 감사합니다. https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/6114fa63b7a9afbcedbb1af77ad8a8c599ce7cc1 에서 수정했습니다.

2021-06-02 17:40 UTC, dngwoodo commented on src/ButtonContainer/index.jsx
> +  const selected = useSelector((state) => state.search[search]);
피드백 감사합니다. https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/b5f2b7db383fc50cf2994bcfa678e1b55f443dfe 에서 수정했습니다.

2021-06-03 13:15 UTC, dngwoodo commented on src/Buttons/index.jsx
> +export default function Buttons({ options, search }) {
슬랙에서 답변 주신걸로 생각을 해봤는데 Regions나 Categories 컴포넌트로 빼게 되도 ButtonContainer, Button에서 search props가 필요한 구조입니다. 구조를 조금 잘못잡은것 같은데 어떻게 하면 좋을지 고민입니다

2021-06-03 13:55 UTC, Kihyun92 commented on src/App.jsx
> +import { loadRegions, loadCategories } from './actions';
기준이 있다면 괜찮을 것 같아요~ 관련해서 eslint rule을 설정해서 팀간에 컨벤션을 관리하기도 합니다. 참고해 보셔도 좋을 것 같네요

- https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

2021-06-03 14:16 UTC, Kihyun92 requested changes

2021-06-03 14:16 UTC, Kihyun92 commented on src/ButtonContainer/index.jsx
> +  }
```suggestion
  function handleClick({ search, value }) {
    dispatch(changeSearch({
      search,
      value,
    }));
  }
```

이렇게 처리해줄도 있을 것 같아요~

2021-06-03 21:29 UTC, dngwoodo commented
궁금한점
- [ ] 컴포넌트를 재사용성 있게 구성했는가?
- [ ] action을 재사용성 있게 잘 만들었는가?
- [ ] object literal lookup을 적용했는데 reducer안의 function들을 바깥으로 빼는게 좋은가?

2021-06-03 21:44 UTC, dngwoodo commented
이번주에 나름 열심히 한다곤 했는데 일주일이 너무 짧게 느껴지네요. 이번주 과제 리뷰 받을 날이 얼마 남지 않아 아쉽습니다.

> 궁금한점
> 
> * [ ]  컴포넌트를 재사용성 있게 구성했는가?
> * [ ]  action을 재사용성 있게 잘 만들었는가?
> * [ ]  object literal lookup을 적용했는데 reducer안의 function들을 바깥으로 빼는게 좋은가?
> * [ ]  [object literal lookup 정리](https://www.notion.so/Object-Literal-Lookups-0214318dcfd7485ba59746100291592c)에서 미흡한점이 있는가?

2021-06-04 09:40 UTC, dngwoodo commented
> 폴더로 관리하기 위해 index.jsx로 처리하신 것 같군요~
> 
> ![image](https://user-images.githubusercontent.com/35797540/120351410-d68cc000-c33a-11eb-9dbb-13b27e51ae35.png)
> 저희 팀같은 경우엔 위와 같이 컴포넌트 이름과 파일 이름을 같게 해주기위해 index.ts와 같은 파일을 사용합니다.
> 
> ```ts
> // index.ts
> import PostWrite from './PostWrite';
> 
> export default PostWrite;
> ```
> 
> index.ts에서는 해당 컴포넌트를 import하고 다시 export 해주는 처리를 해주고 있어요. 조금 불편하긴 하지만, 이런 방식도 있다는걸 알려드려요 😄

피드백 감사합니다. 트레이너님 방식으로 전부 수정해봤습니다

2021-06-04 09:40 UTC, dngwoodo commented on src/RegionContainer/index.test.jsx
> +import RegionContainer from '.';
피드백 감사합니다. 적용했습니다!

2021-06-04 09:42 UTC, dngwoodo commented on src/reducer/index.js
> +  return state;
감사합니다. 적용했습니다!

2021-06-04 09:42 UTC, dngwoodo commented on src/App.jsx
> +import { loadRegions, loadCategories } from './actions';
감사합니다. 이런 룰이 있는진 몰랐네요!

2021-06-04 09:44 UTC, dngwoodo commented on src/ButtonContainer/index.jsx
> +  }
피드백 감사합니다. 해당 부분은 위에 props에 search가 있어서 중복 오류가 떠서 payload로 전달했었습니다. 현재는 구조를 바꿔서 말씀해주신 것 처럼 적용했습니다!

2021-06-04 18:29 UTC, Kihyun92 requested changes
> * [ ]  컴포넌트를 재사용성 있게 구성했는가?

이 부분은 지금 프로젝트 안에서는 정답을 내리기 어렵네요 ㅎㅎ 아무래도 사용하는 부분도 적고, 네이밍도 조금 아쉬운 느낌이 있는데 이 부분은 어쩔 수 없는 것 같네요.

반복되는 로직을 컴포넌트로 추출해서 재사용하는 것도 중요하지만, 반대로 불필요하게 공통 컴포넌트로 분리하지는 않았는지 주의해야할 것 같아요.
> * [ ]  action을 재사용성 있게 잘 만들었는가?

재사용 가능하도록 하나의 기능만 하도록 잘 만드신 것 같아요.
> * [ ]  object literal lookup을 적용했는데 reducer안의 function들을 바깥으로 빼는게 좋은가?

바깥으로 빼도 좋을 것 같습니다~
> * [ ]  [object literal lookup 정리](https://www.notion.so/Object-Literal-Lookups-0214318dcfd7485ba59746100291592c)에서 미흡한점이 있는가?

잘 작성해서 공유해주신 것 같습니다~! 👍🏼👍🏼
> * [ ]  컴포넌트 폴더이름과 컴포넌트 이름을 맞추면 어떤 이점이 있는가?

폴더 단위로 해당 컴포넌트와 관련된 관심사가 같은 것들(스타일, 테스트 등)이 관리될 것 같아요.
> * [ ]  redux-thunk는 어떻게 테스트해야 되는가? actions를 test해야 될 것 같은데 어떻게 해야될 지 모르겠습니다. services/api부분도 __mocks__는 만들어주었지만 어디서 어떻게 테스트 해봐야 될지 감이 잘 잡히지 않습니다.

thunk에 대한 테스팅은 `redux-mock-store`를 사용하시면 될 것 같아요~

mockStore을 만들어주고, mockStore에서 thunk함수를 dispatch했을 때, store에서 해당 actions를 받는 지 확인해주면 될 것 같아요.
> * [ ]  [ea38e47](https://github.com/CodeSoom/react-week5-assignment-1/commit/ea38e47485d844e1537bce48302534c971450f29) 이 커밋을 보시면 `jest.mock('react-redux');` 를 해주지 않았음에도 테스트가 통과했었는데 왜 통과하는지 모르겠습니다

`react-redux` 모듈 관련 함수들을 mocking 해서 처리해주었기 때문아닐까요?
> * [ ]  [588ef5c](https://github.com/CodeSoom/react-week5-assignment-1/commit/588ef5c3022f0534a9023018eb4ed5e199b7f37c) 에서 api function들도 테스트를 해보려고 spy를 썻는데 제가 생각한대로 동작하지 않는 것 같습니다. 코드는 아래와 같습니다. `expect(spy).toBeCalled();`에서 failed 됩니다.
> 
> ```js
>   import { fetchRegions } from './services/api';
> 
>   jest.mock('./services/api');
> 
>   describe('loadRegions', () => {
>     it('passes "setRegion" action', async () => {
>       const spy = jest.spyOn({ fetchRegions }, 'fetchRegions');
> 
>       await loadRegions()(dispatch);
> 
>       expect(spy).toBeCalled();
>       expect(spy()).resolves.toEqual(regions);
> 
>       expect(dispatch).toBeCalledWith(setRegions(regions));
>     });
>   });
> ```

이 부분은 저도 조금 더 확인해봐야겠습니다. 🤔

2021-06-04 18:29 UTC, Kihyun92 commented on src/container/CategoryButtonsContainer/CategoryButtonsContainer.jsx
> +export default function CategoryButtonsContainer() {
`CategoriesContainer` 라고만 해도 컴포넌트의 역할이 전달 될 것 같아요~

2021-06-04 18:29 UTC, Kihyun92 commented on src/container/RestaurantsContainer/RestaurantsContainer.jsx
> +  }, [region, categoryId]);
`loadRestaurants`에 대한 처리를 해주신 것 같아요~ 이 방법도 좋지만, 이 컴포넌트에서는 단순히 스토어의 레스토랑 정보만 가져오도록 처리할 수 없을까요? 🤔

지역이나 카테고리 버튼을 누르면 레스토랑 정보를 로드해온다라는 일종의 비지니스 로직에 대한 관심사를 어디에 둘지에 대해 고민해보시면 좋을 것 같아요.

그리고 만약 선택해야하는 지역정보가 많아질 경우엔(지역, 카테고리 외에 추가로 선택해야하는 경우) 어떨지도 생각해보시면 좋을 것 같습니다~

2021-06-04 18:29 UTC, Kihyun92 commented on src/presentational/Button/Button.jsx
> +        {selected === name ? `${name}(V)` : name}
name은 항상 노출되는 정보같아요~ 뒤쪽에 추가되는 부분만 예외처리해주는건 어떨까요?

2021-06-04 18:29 UTC, Kihyun92 commented on src/reducer/index.js
> +  return actionType[type]();
```suggestion
  function defaultAction() {
    return state;
  }

  return (actionType[type] || defaultAction)();
```

위와 같이 액션 타입이 없는 경우에 대해 함수로 처리 해줄 수도 있겠네요~

2021-06-05 14:23 UTC, dngwoodo commented on src/container/CategoryButtonsContainer/CategoryButtonsContainer.jsx
> +export default function CategoryButtonsContainer() {
피드백 감사합니다. https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/27c8582f071736cee410ffaf2af10f6d3b51dbbe 에서 변경했습니다!

2021-06-05 14:29 UTC, dngwoodo commented on src/container/RestaurantsContainer/RestaurantsContainer.jsx
> +  }, [region, categoryId]);
https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/828a66ba32bb50c405536f7ff700da2cb0ee32a7 에서 변경했습니다. 

변경점을 말씀드리겠습니다
1. RestaurantsCotnainer에서 useEffect로 region, categoryId가 변경될때마다 실행시켜서 redux의 restaurants 상태값을 변경해서 리랜더링 시켰었는데 피드백을 받고 loadRestaurants thunk 함수에서 처리해주는 것으로 변경했습니다.
2. 그리고 loadRestaurants thunk함수를 CategoriesContainer, RegionsContainer에서 버튼을 클릭할 때 마다 실행되도록 변경했습니다.
3. 테스트 부분도 그에 맞게 변경을 했습니다. CategoriesContainer, RegionsContainer의 test를 보시면 주석처리를 해놓은 부분이 있는데  dispatch가 두개 실행되다보니 어떻게 테스트를 해야 될 지 조금 헷갈립니다. 한번 봐주시면 감사하겠습니다.

2021-06-05 14:39 UTC, dngwoodo commented on src/presentational/Button/Button.jsx
> +        {selected === name ? `${name}(V)` : name}
피드백 감사합니다. https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/f154bb74cf572591f5f94f3892834f51037aec97 에서 변경해줬습니다! 이 부분은 커밋내용을 어떻게 하면 좋을까요? 10분 생각하다가 포기했습니다..ㅋㅋㅋ

2021-06-05 14:48 UTC, dngwoodo commented on src/reducer/index.js
> +  return actionType[type]();
피드백 감사합니다. https://github.com/CodeSoom/react-week5-assignment-1/pull/59/commits/f154bb74cf572591f5f94f3892834f51037aec97 에서 변경해주었습니다!

2021-06-05 15:18 UTC, dngwoodo commented
> > * [ ]   컴포넌트 폴더이름과 컴포넌트 이름을 맞추면 어떤 이점이 있는가?
> 
> 폴더 단위로 해당 컴포넌트와 관련된 관심사가 같은 것들(스타일, 테스트 등)이 관리될 것 같아요.
>

잘 이해가 가지 않습니다. 이렇게 하는 것과 차이가 있을까요?
![스크린샷 2021-06-06 오전 12 12 49](https://user-images.githubusercontent.com/77663233/120896318-efa7b080-c65b-11eb-84f7-790116c98140.png)

 
> > * [ ]   redux-thunk는 어떻게 테스트해야 되는가? actions를 test해야 될 것 같은데 어떻게 해야될 지 모르겠습니다. services/api부분도 __mocks__는 만들어주었지만 어디서 어떻게 테스트 해봐야 될지 감이 잘 잡히지 않습니다.
> 
> thunk에 대한 테스팅은 `redux-mock-store`를 사용하시면 될 것 같아요~
> 
> mockStore을 만들어주고, mockStore에서 thunk함수를 dispatch했을 때, store에서 해당 actions를 받는 지 확인해주면 될 것 같아요.
> 

현재 CategoriesContainer, RegionsContainer, App, actions 테스트에서 `jest.mock('./services/api');` 를 해주었는데 actions를 제외하고는 굳이 안해줘도 테스트가 전부 통과합니다. dispatch 내부적으로 fetch 되는 부분은 굳이 jest.mock 해줄필요가 없을까요?

> > * [ ]   [ea38e47](https://github.com/CodeSoom/react-week5-assignment-1/commit/ea38e47485d844e1537bce48302534c971450f29) 이 커밋을 보시면 `jest.mock('react-redux');` 를 해주지 않았음에도 테스트가 통과했었는데 왜 통과하는지 모르겠습니다
> 
> `react-redux` 모듈 관련 함수들을 mocking 해서 처리해주었기 때문아닐까요?
> 

__mocks__/react-redux에 있는  useSelector, useDispatch를 사용하지 않고 실제로 존재하는 라이브러리의 함수를 mockImplementation을 이용해서 mock 함수로 만들어주었기 때문에 테스트가 통과한것일까요? 그렇다면 굳이 jest.mock을 해 줄 필요가 업는 것일까요?

2021-06-05 15:21 UTC, dngwoodo commented
현재 action 이름중에 changeSearch 라는 action이 있습니다. 이 부분은 changeSelected 로 바꾸고 parameter도 { search, selectedValue}로 바꿔주고 싶은데 괜찮을까요?

```jsx
export function changeSearch({ search, value }) {
  return {
    type: 'changeSearch',
    payload: {
      search,
      value,
    },
  };
}

```

```jsx
export function changeSelected({ search, selectedValue }) {
  return {
    type: 'changeSelected,
    payload: {
      search,
      selectedValue,
    },
  };
}
```

2021-06-05 17:09 UTC, Kihyun92 requested changes
> > > * [ ]    컴포넌트 폴더이름과 컴포넌트 이름을 맞추면 어떤 이점이 있는가?
> > 
> > 
> > 폴더 단위로 해당 컴포넌트와 관련된 관심사가 같은 것들(스타일, 테스트 등)이 관리될 것 같아요.
> 
> 1. 잘 이해가 가지 않습니다. 이렇게 하는 것과 차이가 있을까요?
>    ![스크린샷 2021-06-06 오전 12 12 49](https://user-images.githubusercontent.com/77663233/120896318-efa7b080-c65b-11eb-84f7-790116c98140.png)

조금 겹치는 답인 것 같은데, 각 컴포넌트 관련된 것들을 폴더 별로 관리하게 되니 편리하고 개발자들이 보기 좋다고 생각했습니다.

제가 `컴포넌트 폴더이름과 컴포넌트 이름을 맞추면 어떤 이점이 있는가?` 이 말씀을 잘못 이해한 것 같기도 한데, 혹시 잘못됐다면 어떤 의도인지 조금 더 자세히 설명해주실 수 있을까요?

> 2. 폴더 구조를 index.test.jsx, index.js, RestaurantsContainer.jsx로 잡다보니 index.js는 coverage가 차질 않습니다. 어떻게 처리해줄 수 있을까요?
> 

테스트 파일들 이름도 `CategoriesContainer.test.jsx`와 같이 해주는게 좋을 것 같아요~

-----

> > > * [ ]    redux-thunk는 어떻게 테스트해야 되는가? actions를 test해야 될 것 같은데 어떻게 해야될 지 모르겠습니다. services/api부분도 __mocks__는 만들어주었지만 어디서 어떻게 테스트 해봐야 될지 감이 잘 잡히지 않습니다.
> > 
> > 
> > thunk에 대한 테스팅은 `redux-mock-store`를 사용하시면 될 것 같아요~
> > mockStore을 만들어주고, mockStore에서 thunk함수를 dispatch했을 때, store에서 해당 actions를 받는 지 확인해주면 될 것 같아요.
> 
> 1. 현재 CategoriesContainer, RegionsContainer, App, actions 테스트에서 `jest.mock('./services/api');` 를 해주었는데 actions를 제외하고는 굳이 안해줘도 테스트가 전부 통과합니다. dispatch 내부적으로 fetch 되는 부분은 굳이 jest.mock 해줄필요가 없을까요?

왜 actions를 제외하고는 굳이 jest.mock을 해주지 않아도 테스트가 전부 통과했을까요?

`jest.mock, jest.fn, jest.mockImplementation` 과 같이 mock 해주는 함수들에 대해서 한번 정리해보시는 것도 좋을 것 같습니다~ 

> 2. mockStore를 쓴것과 제가 현재 테스트로 작성한 코드의 차이점이 있을까요?
> 
> ```js
>   describe('loadCategories', () => {
>     it('passes "setCategories" action', async () => {
>       await loadCategories()(dispatch);
> 
>       expect(dispatch).toBeCalledWith(setCategories(categories));
>     });
>   });
> ```
> 

근본적으로는 다르지 않을 것 같아요. mockStore를 사용하면 action에 대한 올바른 payload를 반환하는지에 대한 테스트를 할 수 있기 때문에 권장합니다~

> 3. services/api 함수들은 어떻게 테스트를 해줄 수 있을까요? coverage가 차질 않아 속상합니다..ㅠ
> 

api들을 mocking 해서 간단하게 해당 api를 호출하면 이런 데이터가 온다는 것만 확인해보면 좋을 것 같아요. 사실 API에 대한 테스트를 프론트엔드 단에서 하는게 큰 의미는 없는 것 같아요 😅

-----

> > > * [ ]    [ea38e47](https://github.com/CodeSoom/react-week5-assignment-1/commit/ea38e47485d844e1537bce48302534c971450f29) 이 커밋을 보시면 `jest.mock('react-redux');` 를 해주지 않았음에도 테스트가 통과했었는데 왜 통과하는지 모르겠습니다
> > 
> > 
> > `react-redux` 모듈 관련 함수들을 mocking 해서 처리해주었기 때문아닐까요?
> 
> **mocks**/react-redux에 있는 useSelector, useDispatch를 사용하지 않고 실제로 존재하는 라이브러리의 함수를 mockImplementation을 이용해서 mock 함수로 만들어주었기 때문에 테스트가 통과한것일까요? 그렇다면 굳이 jest.mock을 해 줄 필요가 없는 것일까요?

맞습니다. 결국 mocking 해주는 건 같으니까요.

2021-06-05 17:09 UTC, Kihyun92 commented on src/container/CategoriesContainer/index.test.jsx
> +    // NOTE: loadRestaurants는 이렇게 테스트해보는게 맞을까?
이 정도면 될 것 같아요~

2021-06-05 17:09 UTC, Kihyun92 commented on src/presentational/Restaurant/Restaurant.jsx
> +    </li>
단순히 li 태그로 감싸준것 뿐이라 컴포넌트로 분리하지않고 그냥 사용해도 좋을 것 같아요~

2021-06-05 17:09 UTC, Kihyun92 commented on src/actions/index.js
> +}
`search, value` 가 개인적으로 햇갈리는데, 이게 Buttons 컴포넌트에서 공통적으로 처리하려다 보니 네이밍이 명확하지 않다는 느낌인 것 같아요. 

```javascript
export function changeSelected({ searchLabel, selectedId }) {
  return {
    type: 'changeSelected',
    payload: {
      searchLabel,
      selectedId,
    },
  };
}
```
말씀해주신 부분에서 조금 개인 의견을 보태면 위 예시 처럼 조금 더 각 값들의 의미/역할을 드러내주면 좋을 것 같아요~ (물론 쉽지 않은 것 같습니다 😅)

네이밍만으로 무슨 역할인지 알 수 없다면 공통으로 처리하지 않고 분리해서 명확하게 처리해주는 것도 방법일 것 같네요. 결국 선택한 id 가 중요한거니까요.

2021-06-06 05:24 UTC, dngwoodo commented on src/actions/index.js
> +}
피드백 감사합니다. 제 생각엔 region은 name을 사용하고 category는 id를 사용하기 때문에 selectedId보단 selectedValue가 조금 더 적절하지 않나라고 생각했습니다.

2021-06-06 12:59 UTC, dngwoodo commented
**정리**

1. api 테스트까지 적어서 과제 요구사항을 충족시키고 e2e 테스트까지 돌려보았습니다. 
2. 피드백 주신 mockStore은 다음 과제 때 한번 적용시켜보겠습니다.
3. 그리고 `jest.mock('./services/api');` 를 해주지 않아도 잘 동작하던 부분은 mockFu의 내부로직은 테스트에선 돌아가지 않으니 당연한거였네요. 
4. spyOn은 왜 안되는지 아직도 의문입니다 ㅠ 
5. changeSearch 액션 같은 경우는 우선 searchLabel, selectedValue 로 처리를 해볼 것 같습니다. 프로젝트가 커진다면 따로 액션을 나눠서 하는 것도 의미 전달 부분에서 좋을 것 같습니다.

2021-06-06 15:28 UTC, Kihyun92 commented on src/container/RestaurantsContainer/RestaurantsContainer.jsx
> +  }, [region, categoryId]);
제가 이 커맨트를 놓쳤네요 😅

만약 선택해야하는 지역정보가 많아질 경우엔(지역, 카테고리 외에 추가로 선택해야하는 경우) 어떨지에 대한 부분은 actions에서 처리할때 `getState`를 사용하도록 유도해본 부분이었는데 너무 잘 해주셨네요 😄

2021-06-06 15:31 UTC, Kihyun92 approved these changes
이번주도 너무 고생하셨습니다 👏🏻👏🏻 많은 고민과 의논거리를 던져주셔서 너무 좋았어요. 
개인적으로 바쁜 한주여서 제대로 피드포워드 하지 못했나 하는 아쉬움도 있지만, 너무 잘 해주신 것 같습니다 👍🏼

이번 과제를 통해 무엇을 배우셨나요? 무엇을 더 다뤄보고 싶은지 고민해보셔도 좋을 것 같습니다 ㅎㅎ

과제 풀이 영상 꼭 보시고, 주간회고 채널에 회고 남겨주세요! 😄

2021-06-13 13:28 UTC, merged