레스토랑 조회 구현하기
CodeSoom/react-week5-assignment-1 pull request #60
Opened 2021-06-01 15:51 UTC by hanvit7

안녕하세요 트레이너님 리뷰요청드립니다.

이전 보다 덜 완벽하게, 우선 의식의 흐름대로? 진행하고 있습니다.
잘되고 있는것인지 모르겠지만 이전 보다는 그래도 좀 속도가 나는 것 같습니다. 
비동기까지는 아직 갈길이 머네요 ㅎㅎ

2021-06-02 15:17 UTC, Kihyun92 requested changes
커밋을 보니 TDD cycle을 잘 지켜주고 계신 것 같아요 👍🏼 

테스트 코드도 리팩터링 대상입니다~ 리팩터링 단계에서 불필요한 반복이나 코드 개선을 해주면 좋을 것 같아요 ㅎㅎ

2021-06-02 15:17 UTC, Kihyun92 commented on src/Region.jsx
> +export default function Rigion({ regions }) {
`Rigion` 으로 된 부분이 있는 것 같아요! 전반적으로 확인해주세요~

2021-06-02 15:17 UTC, Kihyun92 commented on src/Region.jsx
> +        </li>
구조분해할당을 사용해도 좋을 것 같군요~

2021-06-02 15:17 UTC, Kihyun92 commented on src/Button.jsx
> +export default function Button({ name }) {
공통 컴포넌트화 하기에는 Button 컴포넌트의 역할이 조금 단순한 것 같습니다 😅  

만약 반복되는 로직이 들어가거나 동일한 스타일의 버튼이 반복되는 경우가 아니라면 굳이 버튼 컴포넌트를 벌써 공통화 해줄 필요는 없을 것 같아요 ㅎㅎ

2021-06-02 15:17 UTC, Kihyun92 commented on src/Region.test.jsx
> +  expect(getByText(regions[1].name)).not.toBeNull();
만약 fixtures가 변경되어서 regions 배열에 인자가 한개가 된다면 어떻게 될까요?

테스트에서 저런 변경에 신경쓰지 않고 확인할 수 있도록 처리해줄 수 없을까요?

2021-06-04 16:20 UTC, Kihyun92 commented
과제가 어떻게 진행중이신지 궁금해요! 진행에 어려움이 있거나 의논이 필요하면 꼭 말씀해주세요😊

올라온 과제 풀이 영상을 보시고 직접 과제를 해보셔도 좋을 것 같습니다~

2021-06-05 15:26 UTC, hanvit7 commented
안녕하세요 트레이너님 
수요일부터 회사일로 바뻐 정신을 못 차리고 있었습니다.
그 여파가 남이있는지 오늘은  몸이 안좋아 하루종일 기절하고 이제 좀 정신차리고 과제 진행중입니다...ㅜㅠ
못다한 부분도 직접 해보고 리뷰 요청 드리겠습니다.

2021-06-06 16:06 UTC, Kihyun92 reviewed
바쁜 한주를 보내신 것 같아요. 이번주도 고생하셨습니다~😊 

커밋을 보니 최대한 TDD cycle을 지키려고 노력하신 것 같아 좋습니다 👍🏼 

과제 풀이 영상을 꼭 보시고, 아샬님은 어떻게 접근하시는지 봐보시면 좋을 것 같습니다 ㅎㅎ

슬랙 채널에 회고 남겨주세요~

2021-06-13 13:30 UTC, merged