Kcena restaurant inquiry
CodeSoom/react-week5-assignment-1 pull request #7
Opened 2020-07-01 13:44 UTC by Kwakcena

현재 레스토랑의 지역 목록을 불러오는 부분까지 완료했습니다. 나머지도 곧 완료 하겠습니다.

2020-07-01 14:15 UTC, hannut91 requested changes
전체적으로 잘 적용하셨는데 TDD가 조금 아쉬워요. 코드를 작성하기 전에 테스트를 먼저 작성하면서 내가 구현해야할 것이 무엇인지 더 명확하게 하는 과정을 추가하면 좋을 것 같고, TDD과정에서 리팩터링이 많이 빠져있는 것 같아요. 리팩터링과정을 꼭 넣어서 해보세요. 검사하겠습니당

2020-07-01 14:15 UTC, hannut91 commented on src/App.test.jsx
> +    }));
`it`안에는 given when then에서 when과 then에 해당하는 부분이에요. given에 대한 것들은 바깥으로 분리시켜주는게 보기 좋을 것 같아요.

```js
const dispatch = jest.fn();

beforeEach(() => {
  dispatch.mockClear();

  useDispatch.mockImplementation(() => dispatch);
  useSelector.mockImplementation((selector) => selector({ regions }));
});
```

2020-07-01 14:15 UTC, hannut91 commented on src/App.test.jsx
> +    expect(getByText('인천')).not.toBeNull();
fixture를 사용하면 더 간단하게 표현할 수 있을 것 같아요

2020-07-01 14:15 UTC, hannut91 commented on src/RestaurantRegions.test.jsx
> +    expect(getByText('인천')).not.toBeNull();
`regions`를 이용해서 더 간단하게 표현해줄 수 있을 것 같아요. 그리고 지역이 하나만 더 추가되더라도 이쪽에 테스트를 수정해야하잖아요  하지만 fixture로 관리하면 fixture만 고쳐줘도 되서 fixture를 사용해서 표현하면 더 좋을 것 같아요

2020-07-01 16:37 UTC, Kwakcena commented on src/App.test.jsx
> +    }));
given when then이 무엇인가요 ?

2020-07-02 00:01 UTC, hannut91 commented on src/App.test.jsx
> +    }));
다음 영상을 참고해주세요.

https://youtu.be/gfTsSBRvdqI

2020-07-02 00:16 UTC, Kwakcena commented on src/App.test.jsx
> +    }));
이 영상 예전에 슬랙에 올라왔을 떄 봣는데 given when then에 대한 언급이 있었나요?!

2020-07-02 00:17 UTC, hannut91 commented on src/App.test.jsx
> +    }));
아 없군요

2020-07-02 00:19 UTC, hannut91 commented on src/App.test.jsx
> +    }));
https://github.com/ahastudio/til/blob/master/blog/2018/12-08-given-when-then.md 이거네요

2020-07-02 11:53 UTC, Kwakcena commented
버튼 클릭시 화면에 체크 모양이 보이도록 하는 부분을 해결 못했어요. 클릭시 category와 region이 제대로 변하는 것 같지도 않네요... 테스트에서는 통과했는데 실제 console.log로 찍어보니 이전값이 찍히는데... 일단 한데까지만 제출하고 이어서 하겠습니다.

TDD 사이클을 지키는데 뭔가 어렵게 느껴지네요 ㅠ 

테스트의 순서를 어떻게 해야 할지 고민이에요.
container를 테스트 하다가 내부에서 쓰고있는 컴포넌트 테스트로 넘어가고, 부모 컴포넌트 -> 자식 컴포넌트 순서로 테스트를 진행해야 하는지, 내부의 자식 컴포넌트를 하나씩 테스트를 완료하고 바깥으로 나오는식으로 해야하는지 햇갈려요. 
그래서 그런지 테스트 순서가 굉장히 복잡해지더라구요.

2020-07-02 13:15 UTC, hannut91 commented
큰 문제에서 작은 문제로, 작은문제에서 큰 문제로 푸는 방법은 둘다 학습하셔야 합니다 ㅎㅎ 정확한것은 `어떻게 문제를 풀 것인가?`에 나오긴 하지만  큰 문제에서 작은 문제로 쪼개나갈 때는 실제로 뭐가 필요한지를 먼저 생각해놓고 풀 수 있다는 장점이 있는 것 같고, 작은 문제를 먼저 풀어서 큰 문제로 확장할 때는 문제 자체가 작기 때문에 단순해서 개발하기 쉽다는 장점이 있지만 실제로 어떻게 쓰일지에 대해서는 충분히 고려하기가 어렵다는 단점이 있어요. 이 과정은 자유롭게 왔다갔다 할 수 있어야 합니다.

See also
  - http://www.kyobobook.co.kr/product/detailViewKor.laf?barcode=9788981723422

2020-07-02 14:10 UTC, hannut91 requested changes

2020-07-02 14:10 UTC, hannut91 commented on src/reducer.test.js
> +  it('set restaurant category into categorys', () => {
`categories`가 맞을 것 같아요!

2020-07-02 14:10 UTC, hannut91 commented on src/reducer.test.js
> +    expect(state.categories).toHaveLength(2);
왜 2 인지 알기가 어려워요. 왜 3이 나 4는 안되나요? 이런 문자를 Magic Literal이라고 불러요. 이건 어떤가요?

```js
expect(state.categories).toEqual(categories);
```

See also
  - https://refactoring.com/catalog/replaceMagicLiteral.html

2020-07-02 14:10 UTC, hannut91 commented on src/RestaurantCategories.test.jsx
> +      expect(getByText(name)).toHaveAttribute('type', 'button');
찾은 요소가 존재하지 않는지 확인하고 속성이 버튼인지 테스트하는 것을 작성하신 것 같아요. 속성을 확인하는 것만으로도 해당 요소가 존재하는걸 확인할 수 있으니 속성만 확인하는건 어떨까요?

2020-07-02 14:10 UTC, hannut91 commented on src/RestaurantCategoriesContainer.test.jsx
> +  it('선택한 지역을 category에 담는다.', () => {
선택한 지역이 아니라 선택한 분류인 것 같아요

2020-07-02 14:10 UTC, hannut91 commented on src/RestaurantCategoriesContainer.test.jsx
> +    fireEvent.click(getByText('한식'));
여기도 `category`를 이요해서 표현해주면 좋을 것 같아요

2020-07-02 14:10 UTC, hannut91 commented on src/RestaurantRegionsContainer.test.jsx
> +    fireEvent.click(getByText('광주'));
여기도 `광주`대신에  `region`으로 표현해주면 좋을 것 같아요

2020-07-02 14:10 UTC, hannut91 commented on src/reducer.js
> +  };
이러면 reducer가 실행될 때 마다 계속 만들어 질 것 같아요. 함수 바깥에 선언하는게 좋을 것 같아요

2020-07-02 14:10 UTC, hannut91 commented on src/reducer.test.js
> +    expect(state.regions).toHaveLength(1);
`expect(state.regions).toEqual(regions)`는 어떨까요?

2020-07-02 14:10 UTC, hannut91 commented on src/reducer.test.js
> +  });
여기도 마찬가지로 Magic literal을 없애면 좋을 것 같아요

2020-07-02 16:24 UTC, Kwakcena commented
리팩토링 해야 할게 이리도 많았군요... 죄송합니다.😭

2020-07-04 10:20 UTC, closed without merging