Implement a Restaurant System by region and category
CodeSoom/react-week5-assignment-1 pull request #9
Opened 2020-07-01 14:31 UTC by daadaadaah

일단 PR 보냈어요~

2020-07-02 00:39 UTC, hannut91 requested changes
먼저 어떤 코드를 구현할지 충분히 고민하신 후 진행한게 보여서 좋았습니다. 먼저 가장 쉬운 경우를 테스트하고(이걸 Happy path라고 부릅니다) 만약 이런 경우는 어떡하지? 예를들어 카테고리 목록을 받아서 보여주는 코드를 작성한 후 만약 여기서 카테고리가 없으면 어떡하지? 라는 고민을 했을 때, 정답이 안떠오르죠. 왜냐하면 정의되어있지 않기 때문이에요. 그러면 나는 카테고리가 비어있으면 비어있다는 메시지가 있었으면 좋겠어라고 결정한다면 테스트를 작성하겠죠

```js
useSelector.mockImplementation((selector) => selector({
  categories: [],
}));

const { getByText } = render(<Categories categories={[]} />);

expect(getByText('카테고리가 없어요')).toBeInTheDocument();
```

그러면 테스트를 실행시키면 실패하겠죠(RED) 그러면 이제 구현하고 다시 테스트를 동작시키면(GREEN) 올바르게 동작하는 걸 테스트가 자동으로 확인해주죠. 이러한 스텝으로 진행하시면 좋을 것 같아요

처음부터 너무 복잡한 것을 테스트하려고 하면 시작하기도 어려울거에요. ㅎㅎ 지금 잘하고 계십니당.

2020-07-02 00:39 UTC, hannut91 commented on src/App.test.jsx
> +      useDispatch.mockImplementation(() => dispatch);
`it`안에는 Given When Then에서 When과 Then에 해당하는 부분이 있어야해요. 이 부분은 바깥으로 빼는게 좋을 것 같아요

```js
describe('App', () => {
  const dispatch = jest.fn();

  beforeEach(() => {
    dispatch.mockClear();

    useDispatch.mockImplementation(() => dispatch);
    useSelector.mockImplementation((selector) => selector({ regions }));
  });
  
  it('renders regions', () => {
  });
});
```

2020-07-02 00:39 UTC, hannut91 commented on src/App.test.jsx
> +  context('render App', () => {
`context`에는 `when, with, without`만 올 수 있어요. 

See also
  - http://www.betterspecs.org/#contexts

2020-07-02 00:39 UTC, hannut91 commented on src/Regions.jsx
> +export default function Regions({ regions, newSelectRegion, onSelectRegion }) {
`newSelectRegion`에서 `new`가 의미하는 바가 무엇인가요? 없으면 어떤 일이 발생하나요?

2020-07-02 00:39 UTC, hannut91 commented on src/Regions.test.jsx
> +    it('run handleSelectRegion', () => {
`with a selected region`가 어떤 의미인지 이해하기 어렵네요. 지역을 선택할 때를 테스트하고 싶으셨던거죠?

2020-07-02 00:39 UTC, hannut91 commented on src/RegionsContainer.jsx
> +  }
`new`가 의미하는 바가 무엇인가요? 없으면 어떤 일이 발생하나요?

2020-07-02 00:39 UTC, hannut91 commented on src/RegionsContainer.test.jsx
> +    it('shows a mark for a selected region', () => {
여기는 변경이 안된 것 같아요

2020-07-02 00:39 UTC, hannut91 commented on src/RegionsContainer.test.jsx
> +  context('with a selected region', () => {
`region`을 선택했을 때를 테스트하고 싶으셨던 거죠?

2020-07-02 00:39 UTC, hannut91 commented on src/reducer.test.js
> +  context('setInitRegions', () => {
테스트 대상을 나타낼 때는 `describe`를 사용하는게 좋을 것 같아요

2020-07-02 07:24 UTC, daadaadaah commented on src/Regions.test.jsx
> +    it('run handleSelectRegion', () => {
네! 그때를 테스트 하고 싶었어요~
수정해야겠네요~ㅎㅎ

2020-07-02 07:28 UTC, daadaadaah commented on src/Regions.jsx
> +export default function Regions({ regions, newSelectRegion, onSelectRegion }) {
selectRegion일 경우, action selectRegion이랑 네이밍이 중복이라서 new를 추가했어요
혹시, 다른 추천해주실만한 워딩 있으신가요? ㅎㅎ

2020-07-02 07:31 UTC, hannut91 commented on src/Regions.jsx
> +export default function Regions({ regions, newSelectRegion, onSelectRegion }) {
`selectedRegion`은 어떤가요?

2020-07-02 07:31 UTC, daadaadaah commented on src/RegionsContainer.jsx
> +  }
region일 경우, store에 있는 regions를 객체로 뽑을 때 region으로 사용하는데, 이거랑 겹칠까봐 new 라는 단어를 붙여봤어요.ㅎㅎ
혹시, 다른 추천해주실만한 워딩 있으시면 추천해주세요~

2020-07-02 07:33 UTC, daadaadaah commented on src/Regions.jsx
> +export default function Regions({ regions, newSelectRegion, onSelectRegion }) {
오! 좋은 워딩이네요~ㅎㅎ

selectedRegion으로 수정할게요😊

2020-07-02 07:44 UTC, daadaadaah commented on src/RegionsContainer.test.jsx
> +  context('with a selected region', () => {
네! 그때를 테스트 하고 싶었어요~
이것도! 수정해야겠네요~ㅎㅎ

2020-07-02 23:27 UTC, daadaadaah commented
정말 세부적으로 commit 날리다보니, 100개가 넘었네요😱

일단 작업한 것까지만 리뷰 부탁드려요(_ _)

restaurants reload 기능은 이따가 추가할게요🙂

2020-07-03 01:51 UTC, hannut91 requested changes
테스트를 작성할 때 `Given`을 더 명확하게 구분하면 좋을 것 같아요

2020-07-03 01:51 UTC, hannut91 commented on src/App.test.jsx
> +  });
이런 초기화 단계는 테스트가 실행하기전, 실행한 후 둘다 해주는게 좋지만 일단은 실행하기 전에만 하면 충분할 것 같아요. 지금은 문제가 없지만 중간에 테스트가 실패하여 종료되는 경우 이 부분을 호출되지 않아서 의도치 않은 문제가 발생할 수 있어요. 예를들면 데이터베이스에 어떤 값을 초기화해주는 로직이 여기에 있었다면 중간에 테스트가 실패하여 초기화하지 않으면 다음번 테스트를 실행할 때 테스트가 올바르게 동작하지 않을거에요.

그리고 dispatch가 `useDispatch` mocking할 때 쓰이니 사용하기전에 clear해주는게 더 자연스러울 것 같아요

```js
beforeEach(() => {
  dispatch.mockClear();
  useDispatch.mockImplementation(() => dispatch);
});
```

2020-07-03 01:51 UTC, hannut91 commented on src/App.test.jsx
> +const dispatch = jest.fn();
테스트에 사용되는 코드들은 `describe`안에 있는게 좋을 것 같아요

2020-07-03 01:51 UTC, hannut91 commented on src/CategoriesContainer.jsx
> +  }
`newSelectedCategory`대신에 category
`newSElectedCategoryId`대신에 categoryId 만 사용해도 충분히 표현될 것 같아요

2020-07-03 01:51 UTC, hannut91 commented on src/RegionsContainer.jsx
> +  }
`region`으로 해도 충분할 것 같아요

2020-07-03 13:20 UTC, daadaadaah commented on src/services/__mocks__/api.js
> +}
지금 보니, api mock을 제대로 하지 않았는데, api 테스트 성공했네요????

제가 테스트를 잘못한 걸까요?

2020-07-03 13:40 UTC, daadaadaah commented on src/services/__mocks__/api.js
> +}
```
export async function fetchInitRegions() {
  return [];
}

export async function fetchInitCategories() {
  return [];
}

export async function fetchInitRestaurants() {
  return [];
}
```

2020-07-04 01:28 UTC, hannut91 requested changes

2020-07-04 01:28 UTC, hannut91 commented on src/RegionsContainer.jsx
> +  }
`regions`에서 카테고리를 불러와서 처리를 해주고 있는 것 같아요. `RegionsContainer`가 regions, category를 모두 알고 있어요.  
`loadRestaurants`안에서 이러한 처리를 해주면 RegionsContainer는 카테고리를 몰라도 될 거에요

2020-07-04 01:28 UTC, hannut91 commented on src/reducer.js
> +
여기 빈 줄이 들어가 있네요

2020-07-04 01:28 UTC, hannut91 commented on src/services/api.test.js
> +      fetch.mockClear();
이게 반복되어서 계속 사용되고 있네요. 중복을 제거할 수 있을까요?

2020-07-05 01:44 UTC, hannut91 approved these changes
조금 아쉬운 부분만 더 커멘트 남겼어요. 고생하셨어요 ㅎㅎ

2020-07-05 01:44 UTC, hannut91 commented on src/Categories.test.jsx
> +        );
여기도 반복적으로 사용되는 것을 함수로 추출하면 중복을 제거할 수 있을거에요

```js
const handleSelectCategory = jest.fn();

beforeEach(() => {
  handleSelectCategory.mockClear();
});

const renderCategories = (selectedCategory) => render(
  <Categories 
    categories={categories} 
    selectedCategory={selectedCategory}
    onSelectCategory={handleSelectCategory}
  />,
)
```

2020-07-05 01:44 UTC, hannut91 commented on src/RegionsContainer.test.jsx
> +}
함수의 내용이 무슨 일을 하는지 충분히 설명하고 있기 때문에 inline function 리팩터링을 해도 괜찮을 것 같아요

See also
  - https://refactoring.com/catalog/inlineFunction.html

2020-07-05 01:44 UTC, hannut91 commented on src/RestaurantsContainer.test.jsx
> +});
RestaurantContainer가 리스토랑 목록을 보여주는 것은 `selectedRegion`와 `selectedCategory`는 상관이 없어요. 근데 테스트에 보면 이 두 값이 있어야지 레스트랑 목록을 보여줄 수 있는 것처럼 묘사되어있어요.

2020-07-05 01:44 UTC, hannut91 commented on src/action.js
> +    const category = categories.find((item) => item.name === selectedCategory);
`selectedCategory`를 저장할 때 카테고리 ID 혹은 category 객체를 저장하고 있었다면 `id`에 바로 접근할 수 있어서 이렇게 찾을 필요가 없을 것 같아요

2020-07-05 01:44 UTC, hannut91 commented on src/action.js
> +      dispatch(setRestaurants(initRestaurants));
`initRestaurants`에서 `init`이 의미하는바가 무엇인가요? `restaurants`로는 부족할까요?

2020-07-05 01:44 UTC, hannut91 commented
이번 과제를 진행하면서 어떤 것을 배우셨나요? 다음 과제를 통해 무엇을 더 시도해보고 싶으신가요?

2020-07-06 08:46 UTC, daadaadaah commented on src/action.js
> +      dispatch(setRestaurants(initRestaurants));
다음 과제때는 init 같은거 빼고 변수명을 지어야겠네요ㅎㅎ

2020-07-06 08:47 UTC, daadaadaah commented on src/action.js
> +    const category = categories.find((item) => item.name === selectedCategory);
ㅎㅎㅎ 맞아요..ㅎㅎ다음 과제때는 object로 해볼게요~~ㅎㅎ

2020-07-07 11:40 UTC, merged